/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountPagination
 */
export interface AccountPagination {
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    hasMore: boolean;
    /**
     * 
     */
    nextOffset: number | null;
}

/**
 * Check if a given object implements the AccountPagination interface.
 */
export function instanceOfAccountPagination(value: object): value is AccountPagination {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    if ((!('nextOffset' in (value as Record<string, any>)) && !('next_offset' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextOffset'] === undefined && (value as Record<string, any>)['next_offset'] === undefined)) return false;
    return true;
}

export function AccountPaginationFromJSON(json: any): AccountPagination {
    return AccountPaginationFromJSONTyped(json, false);
}

export function AccountPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'offset': json['offset'],
        'hasMore': json['has_more'],
        'nextOffset': json['next_offset'],
    };
}

export function AccountPaginationToJSON(json: any): AccountPagination {
    return AccountPaginationToJSONTyped(json, false);
}

export function AccountPaginationToJSONTyped(value?: AccountPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'has_more': value['hasMore'],
        'next_offset': value['nextOffset'],
    };
}

