/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountLimits
 */
export interface AccountLimits {
    /**
     * 
     */
    maxBuckets: number | null;
    /**
     * 
     */
    maxBucketCreationsPerMonth: number | null;
    /**
     * 
     */
    maxFilesPerBucket: number | null;
    /**
     * 
     */
    maxCurrentFiles: number | null;
    /**
     * 
     */
    maxStorageBytes: number | null;
    /**
     * 
     */
    maxFileSizeBytes: number | null;
    /**
     * 
     */
    maxPdfSizeBytes: number | null;
    /**
     * 
     */
    maxFileVersionsPerFile: number | null;
    /**
     * 
     */
    maxEmailDomains: number | null;
    /**
     * 
     */
    maxReceivedEmailsPerMonth: number | null;
    /**
     * 
     */
    maxReceivedEmailBytesPerMonth: number | null;
    /**
     * 
     */
    maxReceivedEmailMessageBytes: number | null;
    /**
     * 
     */
    maxEmailAddressRotationsPerMonth: number | null;
    /**
     * 
     */
    maxAccountMembers: number | null;
    /**
     * 
     */
    maxApiKeys: number | null;
    /**
     * 
     */
    maxAgentConnections: number | null;
    /**
     * 
     */
    apiRateLimitRequestsPerMinute: number | null;
    /**
     * 
     */
    auditRetentionDays: number | null;
    /**
     * Active retained email addresses per inbox; Free always has zero.
     */
    maxEmailAliasesPerBucket: number;
}

/**
 * Check if a given object implements the AccountLimits interface.
 */
export function instanceOfAccountLimits(value: object): value is AccountLimits {
    if ((!('maxBuckets' in (value as Record<string, any>)) && !('max_buckets' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxBuckets'] === undefined && (value as Record<string, any>)['max_buckets'] === undefined)) return false;
    if ((!('maxBucketCreationsPerMonth' in (value as Record<string, any>)) && !('max_bucket_creations_per_month' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxBucketCreationsPerMonth'] === undefined && (value as Record<string, any>)['max_bucket_creations_per_month'] === undefined)) return false;
    if ((!('maxFilesPerBucket' in (value as Record<string, any>)) && !('max_files_per_bucket' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxFilesPerBucket'] === undefined && (value as Record<string, any>)['max_files_per_bucket'] === undefined)) return false;
    if ((!('maxCurrentFiles' in (value as Record<string, any>)) && !('max_current_files' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxCurrentFiles'] === undefined && (value as Record<string, any>)['max_current_files'] === undefined)) return false;
    if ((!('maxStorageBytes' in (value as Record<string, any>)) && !('max_storage_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxStorageBytes'] === undefined && (value as Record<string, any>)['max_storage_bytes'] === undefined)) return false;
    if ((!('maxFileSizeBytes' in (value as Record<string, any>)) && !('max_file_size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxFileSizeBytes'] === undefined && (value as Record<string, any>)['max_file_size_bytes'] === undefined)) return false;
    if ((!('maxPdfSizeBytes' in (value as Record<string, any>)) && !('max_pdf_size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxPdfSizeBytes'] === undefined && (value as Record<string, any>)['max_pdf_size_bytes'] === undefined)) return false;
    if ((!('maxFileVersionsPerFile' in (value as Record<string, any>)) && !('max_file_versions_per_file' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxFileVersionsPerFile'] === undefined && (value as Record<string, any>)['max_file_versions_per_file'] === undefined)) return false;
    if ((!('maxEmailDomains' in (value as Record<string, any>)) && !('max_email_domains' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxEmailDomains'] === undefined && (value as Record<string, any>)['max_email_domains'] === undefined)) return false;
    if ((!('maxReceivedEmailsPerMonth' in (value as Record<string, any>)) && !('max_received_emails_per_month' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxReceivedEmailsPerMonth'] === undefined && (value as Record<string, any>)['max_received_emails_per_month'] === undefined)) return false;
    if ((!('maxReceivedEmailBytesPerMonth' in (value as Record<string, any>)) && !('max_received_email_bytes_per_month' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxReceivedEmailBytesPerMonth'] === undefined && (value as Record<string, any>)['max_received_email_bytes_per_month'] === undefined)) return false;
    if ((!('maxReceivedEmailMessageBytes' in (value as Record<string, any>)) && !('max_received_email_message_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxReceivedEmailMessageBytes'] === undefined && (value as Record<string, any>)['max_received_email_message_bytes'] === undefined)) return false;
    if ((!('maxEmailAddressRotationsPerMonth' in (value as Record<string, any>)) && !('max_email_address_rotations_per_month' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxEmailAddressRotationsPerMonth'] === undefined && (value as Record<string, any>)['max_email_address_rotations_per_month'] === undefined)) return false;
    if ((!('maxAccountMembers' in (value as Record<string, any>)) && !('max_account_members' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxAccountMembers'] === undefined && (value as Record<string, any>)['max_account_members'] === undefined)) return false;
    if ((!('maxApiKeys' in (value as Record<string, any>)) && !('max_api_keys' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxApiKeys'] === undefined && (value as Record<string, any>)['max_api_keys'] === undefined)) return false;
    if ((!('maxAgentConnections' in (value as Record<string, any>)) && !('max_agent_connections' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxAgentConnections'] === undefined && (value as Record<string, any>)['max_agent_connections'] === undefined)) return false;
    if ((!('apiRateLimitRequestsPerMinute' in (value as Record<string, any>)) && !('api_rate_limit_requests_per_minute' in (value as Record<string, any>))) || ((value as Record<string, any>)['apiRateLimitRequestsPerMinute'] === undefined && (value as Record<string, any>)['api_rate_limit_requests_per_minute'] === undefined)) return false;
    if ((!('auditRetentionDays' in (value as Record<string, any>)) && !('audit_retention_days' in (value as Record<string, any>))) || ((value as Record<string, any>)['auditRetentionDays'] === undefined && (value as Record<string, any>)['audit_retention_days'] === undefined)) return false;
    if ((!('maxEmailAliasesPerBucket' in (value as Record<string, any>)) && !('max_email_aliases_per_bucket' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxEmailAliasesPerBucket'] === undefined && (value as Record<string, any>)['max_email_aliases_per_bucket'] === undefined)) return false;
    return true;
}

export function AccountLimitsFromJSON(json: any): AccountLimits {
    return AccountLimitsFromJSONTyped(json, false);
}

export function AccountLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'maxBuckets': json['max_buckets'],
        'maxBucketCreationsPerMonth': json['max_bucket_creations_per_month'],
        'maxFilesPerBucket': json['max_files_per_bucket'],
        'maxCurrentFiles': json['max_current_files'],
        'maxStorageBytes': json['max_storage_bytes'],
        'maxFileSizeBytes': json['max_file_size_bytes'],
        'maxPdfSizeBytes': json['max_pdf_size_bytes'],
        'maxFileVersionsPerFile': json['max_file_versions_per_file'],
        'maxEmailDomains': json['max_email_domains'],
        'maxReceivedEmailsPerMonth': json['max_received_emails_per_month'],
        'maxReceivedEmailBytesPerMonth': json['max_received_email_bytes_per_month'],
        'maxReceivedEmailMessageBytes': json['max_received_email_message_bytes'],
        'maxEmailAddressRotationsPerMonth': json['max_email_address_rotations_per_month'],
        'maxAccountMembers': json['max_account_members'],
        'maxApiKeys': json['max_api_keys'],
        'maxAgentConnections': json['max_agent_connections'],
        'apiRateLimitRequestsPerMinute': json['api_rate_limit_requests_per_minute'],
        'auditRetentionDays': json['audit_retention_days'],
        'maxEmailAliasesPerBucket': json['max_email_aliases_per_bucket'],
    };
}

export function AccountLimitsToJSON(json: any): AccountLimits {
    return AccountLimitsToJSONTyped(json, false);
}

export function AccountLimitsToJSONTyped(value?: AccountLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_buckets': value['maxBuckets'],
        'max_bucket_creations_per_month': value['maxBucketCreationsPerMonth'],
        'max_files_per_bucket': value['maxFilesPerBucket'],
        'max_current_files': value['maxCurrentFiles'],
        'max_storage_bytes': value['maxStorageBytes'],
        'max_file_size_bytes': value['maxFileSizeBytes'],
        'max_pdf_size_bytes': value['maxPdfSizeBytes'],
        'max_file_versions_per_file': value['maxFileVersionsPerFile'],
        'max_email_domains': value['maxEmailDomains'],
        'max_received_emails_per_month': value['maxReceivedEmailsPerMonth'],
        'max_received_email_bytes_per_month': value['maxReceivedEmailBytesPerMonth'],
        'max_received_email_message_bytes': value['maxReceivedEmailMessageBytes'],
        'max_email_address_rotations_per_month': value['maxEmailAddressRotationsPerMonth'],
        'max_account_members': value['maxAccountMembers'],
        'max_api_keys': value['maxApiKeys'],
        'max_agent_connections': value['maxAgentConnections'],
        'api_rate_limit_requests_per_minute': value['apiRateLimitRequestsPerMinute'],
        'audit_retention_days': value['auditRetentionDays'],
        'max_email_aliases_per_bucket': value['maxEmailAliasesPerBucket'],
    };
}

