/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountIdentityPermissions } from './AccountIdentityPermissions';
import {
    AccountIdentityPermissionsFromJSON,
    AccountIdentityPermissionsFromJSONTyped,
    AccountIdentityPermissionsToJSON,
    AccountIdentityPermissionsToJSONTyped,
} from './AccountIdentityPermissions';
import type { AccountIdentityAgencyAccount } from './AccountIdentityAgencyAccount';
import {
    AccountIdentityAgencyAccountFromJSON,
    AccountIdentityAgencyAccountFromJSONTyped,
    AccountIdentityAgencyAccountToJSON,
    AccountIdentityAgencyAccountToJSONTyped,
} from './AccountIdentityAgencyAccount';

/**
 * 
 * @export
 * @interface AccountIdentity
 */
export interface AccountIdentity {
    /**
     * 
     */
    id: string;
    /**
     * Account name, separate from the client person or business.
     */
    name: string;
    /**
     * 
     */
    accountKind: AccountIdentityAccountKindEnum;
    /**
     * Client person or business name, or null when unset.
     */
    clientName: string | null;
    /**
     * 
     */
    agencyAccount: AccountIdentityAgencyAccount | null;
    /**
     * 
     */
    region?: string | null;
    /**
     * 
     */
    status?: AccountIdentityStatusEnum;
    /**
     * 
     */
    permissions?: AccountIdentityPermissions;
}


/**
 * @export
 */
export const AccountIdentityAccountKindEnum = {
    Standard: 'standard',
    Agency: 'agency',
    Client: 'client',
} as const;
export type AccountIdentityAccountKindEnum = typeof AccountIdentityAccountKindEnum[keyof typeof AccountIdentityAccountKindEnum];

/**
 * @export
 */
export const AccountIdentityStatusEnum = {
    Active: 'active',
    ReadOnly: 'read_only',
} as const;
export type AccountIdentityStatusEnum = typeof AccountIdentityStatusEnum[keyof typeof AccountIdentityStatusEnum];


/**
 * Check if a given object implements the AccountIdentity interface.
 */
export function instanceOfAccountIdentity(value: object): value is AccountIdentity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('accountKind' in (value as Record<string, any>)) && !('account_kind' in (value as Record<string, any>))) || ((value as Record<string, any>)['accountKind'] === undefined && (value as Record<string, any>)['account_kind'] === undefined)) return false;
    if ((!('clientName' in (value as Record<string, any>)) && !('client_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['clientName'] === undefined && (value as Record<string, any>)['client_name'] === undefined)) return false;
    if ((!('agencyAccount' in (value as Record<string, any>)) && !('agency_account' in (value as Record<string, any>))) || ((value as Record<string, any>)['agencyAccount'] === undefined && (value as Record<string, any>)['agency_account'] === undefined)) return false;
    return true;
}

export function AccountIdentityFromJSON(json: any): AccountIdentity {
    return AccountIdentityFromJSONTyped(json, false);
}

export function AccountIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountIdentity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'accountKind': json['account_kind'],
        'clientName': json['client_name'],
        'agencyAccount': AccountIdentityAgencyAccountFromJSON(json['agency_account']),
        'region': json['region'] === undefined ? undefined : json['region'] === null ? null : json['region'],
        'status': json['status'] == null ? undefined : json['status'],
        'permissions': json['permissions'] == null ? undefined : AccountIdentityPermissionsFromJSON(json['permissions']),
    };
}

export function AccountIdentityToJSON(json: any): AccountIdentity {
    return AccountIdentityToJSONTyped(json, false);
}

export function AccountIdentityToJSONTyped(value?: AccountIdentity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'account_kind': value['accountKind'],
        'client_name': value['clientName'],
        'agency_account': AccountIdentityAgencyAccountToJSON(value['agencyAccount']),
        'region': value['region'],
        'status': value['status'],
        'permissions': AccountIdentityPermissionsToJSON(value['permissions']),
    };
}

