/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountIdentityPermissions
 */
export interface AccountIdentityPermissions {
    /**
     * 
     */
    scope?: string;
    /**
     * 
     */
    bucketAccess?: string;
    /**
     * 
     */
    canCreateBuckets?: boolean;
}

/**
 * Check if a given object implements the AccountIdentityPermissions interface.
 */
export function instanceOfAccountIdentityPermissions(value: object): value is AccountIdentityPermissions {
    return true;
}

export function AccountIdentityPermissionsFromJSON(json: any): AccountIdentityPermissions {
    return AccountIdentityPermissionsFromJSONTyped(json, false);
}

export function AccountIdentityPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountIdentityPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'] == null ? undefined : json['scope'],
        'bucketAccess': json['bucket_access'] == null ? undefined : json['bucket_access'],
        'canCreateBuckets': json['can_create_buckets'] == null ? undefined : json['can_create_buckets'],
    };
}

export function AccountIdentityPermissionsToJSON(json: any): AccountIdentityPermissions {
    return AccountIdentityPermissionsToJSONTyped(json, false);
}

export function AccountIdentityPermissionsToJSONTyped(value?: AccountIdentityPermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'bucket_access': value['bucketAccess'],
        'can_create_buckets': value['canCreateBuckets'],
    };
}

