/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ApiErrorError
 */
export interface ApiErrorError {
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    message: string;
    /**
     * Structured error details: an object or an array of field/message validation errors.
     */
    details?: any | null;
    /**
     * 
     */
    requestId?: string;
    /**
     * 
     */
    docsUrl?: string;
    /**
     * 
     */
    timestamp?: Date;
    /**
     * 
     */
    recoverable?: boolean;
    /**
     * 
     */
    nextAction?: string;
    /**
     * 
     */
    browserUrl?: string;
}

/**
 * Check if a given object implements the ApiErrorError interface.
 */
export function instanceOfApiErrorError(value: object): value is ApiErrorError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApiErrorErrorFromJSON(json: any): ApiErrorError {
    return ApiErrorErrorFromJSONTyped(json, false);
}

export function ApiErrorErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] === undefined ? undefined : json['details'] === null ? null : json['details'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'docsUrl': json['docs_url'] == null ? undefined : json['docs_url'],
        'timestamp': json['timestamp'] == null ? undefined : (parseDateTime(json['timestamp'])),
        'recoverable': json['recoverable'] == null ? undefined : json['recoverable'],
        'nextAction': json['next_action'] == null ? undefined : json['next_action'],
        'browserUrl': json['browser_url'] == null ? undefined : json['browser_url'],
    };
}

export function ApiErrorErrorToJSON(json: any): ApiErrorError {
    return ApiErrorErrorToJSONTyped(json, false);
}

export function ApiErrorErrorToJSONTyped(value?: ApiErrorError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
        'request_id': value['requestId'],
        'docs_url': value['docsUrl'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : serializeDateTime(value['timestamp']),
        'recoverable': value['recoverable'],
        'next_action': value['nextAction'],
        'browser_url': value['browserUrl'],
    };
}

