/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiErrorNot
 */
export interface ApiErrorNot {
}

/**
 * Check if a given object implements the ApiErrorNot interface.
 */
export function instanceOfApiErrorNot(value: object): value is ApiErrorNot {
    return true;
}

export function ApiErrorNotFromJSON(json: any): ApiErrorNot {
    return ApiErrorNotFromJSONTyped(json, false);
}

export function ApiErrorNotFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorNot {
    return json;
}

export function ApiErrorNotToJSON(json: any): ApiErrorNot {
    return ApiErrorNotToJSONTyped(json, false);
}

export function ApiErrorNotToJSONTyped(value?: ApiErrorNot | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

