/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSuccess
 */
export interface ApiSuccess {
    /**
     * 
     */
    success: boolean;
    /**
     * Endpoint-specific result fields. See the endpoint documentation for the domain or authentication-capability fields.
     */
    data: { [key: string]: any; };
}

/**
 * Check if a given object implements the ApiSuccess interface.
 */
export function instanceOfApiSuccess(value: object): value is ApiSuccess {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ApiSuccessFromJSON(json: any): ApiSuccess {
    return ApiSuccessFromJSONTyped(json, false);
}

export function ApiSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSuccess {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'],
    };
}

export function ApiSuccessToJSON(json: any): ApiSuccess {
    return ApiSuccessToJSONTyped(json, false);
}

export function ApiSuccessToJSONTyped(value?: ApiSuccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
    };
}

