/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BucketEmailAssignmentError
 */
export interface BucketEmailAssignmentError {
    /**
     * 
     */
    code?: string;
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    retryable?: boolean;
}

/**
 * Check if a given object implements the BucketEmailAssignmentError interface.
 */
export function instanceOfBucketEmailAssignmentError(value: object): value is BucketEmailAssignmentError {
    return true;
}

export function BucketEmailAssignmentErrorFromJSON(json: any): BucketEmailAssignmentError {
    return BucketEmailAssignmentErrorFromJSONTyped(json, false);
}

export function BucketEmailAssignmentErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketEmailAssignmentError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'retryable': json['retryable'] == null ? undefined : json['retryable'],
    };
}

export function BucketEmailAssignmentErrorToJSON(json: any): BucketEmailAssignmentError {
    return BucketEmailAssignmentErrorToJSONTyped(json, false);
}

export function BucketEmailAssignmentErrorToJSONTyped(value?: BucketEmailAssignmentError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'retryable': value['retryable'],
    };
}

