/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BucketEmailAvailableDomainsInner
 */
export interface BucketEmailAvailableDomainsInner {
    /**
     * 
     */
    hostname?: string;
    /**
     * 
     */
    kind?: BucketEmailAvailableDomainsInnerKindEnum;
}


/**
 * @export
 */
export const BucketEmailAvailableDomainsInnerKindEnum = {
    Platform: 'platform',
    Custom: 'custom',
} as const;
export type BucketEmailAvailableDomainsInnerKindEnum = typeof BucketEmailAvailableDomainsInnerKindEnum[keyof typeof BucketEmailAvailableDomainsInnerKindEnum];


/**
 * Check if a given object implements the BucketEmailAvailableDomainsInner interface.
 */
export function instanceOfBucketEmailAvailableDomainsInner(value: object): value is BucketEmailAvailableDomainsInner {
    return true;
}

export function BucketEmailAvailableDomainsInnerFromJSON(json: any): BucketEmailAvailableDomainsInner {
    return BucketEmailAvailableDomainsInnerFromJSONTyped(json, false);
}

export function BucketEmailAvailableDomainsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketEmailAvailableDomainsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'kind': json['kind'] == null ? undefined : json['kind'],
    };
}

export function BucketEmailAvailableDomainsInnerToJSON(json: any): BucketEmailAvailableDomainsInner {
    return BucketEmailAvailableDomainsInnerToJSONTyped(json, false);
}

export function BucketEmailAvailableDomainsInnerToJSONTyped(value?: BucketEmailAvailableDomainsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'kind': value['kind'],
    };
}

