/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BucketEmailAliasesInner
 */
export interface BucketEmailAliasesInner {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    address: string;
    /**
     * Within the current alias allowance. Inbox receiving holds still apply.
     */
    active: boolean;
}

/**
 * Check if a given object implements the BucketEmailAliasesInner interface.
 */
export function instanceOfBucketEmailAliasesInner(value: object): value is BucketEmailAliasesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function BucketEmailAliasesInnerFromJSON(json: any): BucketEmailAliasesInner {
    return BucketEmailAliasesInnerFromJSONTyped(json, false);
}

export function BucketEmailAliasesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketEmailAliasesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'address': json['address'],
        'active': json['active'],
    };
}

export function BucketEmailAliasesInnerToJSON(json: any): BucketEmailAliasesInner {
    return BucketEmailAliasesInnerToJSONTyped(json, false);
}

export function BucketEmailAliasesInnerToJSONTyped(value?: BucketEmailAliasesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'address': value['address'],
        'active': value['active'],
    };
}

