/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BucketEmailAssignmentError } from './BucketEmailAssignmentError';
import {
    BucketEmailAssignmentErrorFromJSON,
    BucketEmailAssignmentErrorFromJSONTyped,
    BucketEmailAssignmentErrorToJSON,
    BucketEmailAssignmentErrorToJSONTyped,
} from './BucketEmailAssignmentError';

/**
 * No candidate address is disclosed. Keep using address until status is active; on pending poll the email endpoint.
 * @export
 * @interface BucketEmailAssignment
 */
export interface BucketEmailAssignment {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    status?: BucketEmailAssignmentStatusEnum;
    /**
     * 
     */
    hostname?: string;
    /**
     * 
     */
    error?: BucketEmailAssignmentError;
}


/**
 * @export
 */
export const BucketEmailAssignmentStatusEnum = {
    Pending: 'pending',
    Active: 'active',
    Failed: 'failed',
} as const;
export type BucketEmailAssignmentStatusEnum = typeof BucketEmailAssignmentStatusEnum[keyof typeof BucketEmailAssignmentStatusEnum];


/**
 * Check if a given object implements the BucketEmailAssignment interface.
 */
export function instanceOfBucketEmailAssignment(value: object): value is BucketEmailAssignment {
    return true;
}

export function BucketEmailAssignmentFromJSON(json: any): BucketEmailAssignment {
    return BucketEmailAssignmentFromJSONTyped(json, false);
}

export function BucketEmailAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketEmailAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'error': json['error'] == null ? undefined : BucketEmailAssignmentErrorFromJSON(json['error']),
    };
}

export function BucketEmailAssignmentToJSON(json: any): BucketEmailAssignment {
    return BucketEmailAssignmentToJSONTyped(json, false);
}

export function BucketEmailAssignmentToJSONTyped(value?: BucketEmailAssignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'hostname': value['hostname'],
        'error': BucketEmailAssignmentErrorToJSON(value['error']),
    };
}

