/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Caller-specific customization capability on the dedicated email GET/rotate endpoints.
 * @export
 * @interface BucketEmailCustomization
 */
export interface BucketEmailCustomization {
    /**
     * 
     */
    allowed?: boolean;
    /**
     * 
     */
    blockedReason?: string | null;
    /**
     * Account-domain settings link for administrators; null otherwise.
     */
    settingsUrl?: string | null;
}

/**
 * Check if a given object implements the BucketEmailCustomization interface.
 */
export function instanceOfBucketEmailCustomization(value: object): value is BucketEmailCustomization {
    return true;
}

export function BucketEmailCustomizationFromJSON(json: any): BucketEmailCustomization {
    return BucketEmailCustomizationFromJSONTyped(json, false);
}

export function BucketEmailCustomizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketEmailCustomization {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed': json['allowed'] == null ? undefined : json['allowed'],
        'blockedReason': json['blocked_reason'] === undefined ? undefined : json['blocked_reason'] === null ? null : json['blocked_reason'],
        'settingsUrl': json['settings_url'] === undefined ? undefined : json['settings_url'] === null ? null : json['settings_url'],
    };
}

export function BucketEmailCustomizationToJSON(json: any): BucketEmailCustomization {
    return BucketEmailCustomizationToJSONTyped(json, false);
}

export function BucketEmailCustomizationToJSONTyped(value?: BucketEmailCustomization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed': value['allowed'],
        'blocked_reason': value['blockedReason'],
        'settings_url': value['settingsUrl'],
    };
}

