/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { BucketEmailAssignment } from './BucketEmailAssignment';
import {
    BucketEmailAssignmentFromJSON,
    BucketEmailAssignmentFromJSONTyped,
    BucketEmailAssignmentToJSON,
    BucketEmailAssignmentToJSONTyped,
} from './BucketEmailAssignment';
import type { BucketEmailAvailableDomainsInner } from './BucketEmailAvailableDomainsInner';
import {
    BucketEmailAvailableDomainsInnerFromJSON,
    BucketEmailAvailableDomainsInnerFromJSONTyped,
    BucketEmailAvailableDomainsInnerToJSON,
    BucketEmailAvailableDomainsInnerToJSONTyped,
} from './BucketEmailAvailableDomainsInner';
import type { EmailSenderAllowlist } from './EmailSenderAllowlist';
import {
    EmailSenderAllowlistFromJSON,
    EmailSenderAllowlistFromJSONTyped,
    EmailSenderAllowlistToJSON,
    EmailSenderAllowlistToJSONTyped,
} from './EmailSenderAllowlist';
import type { BucketEmailCustomization } from './BucketEmailCustomization';
import {
    BucketEmailCustomizationFromJSON,
    BucketEmailCustomizationFromJSONTyped,
    BucketEmailCustomizationToJSON,
    BucketEmailCustomizationToJSONTyped,
} from './BucketEmailCustomization';
import type { BucketEmailAliasesInner } from './BucketEmailAliasesInner';
import {
    BucketEmailAliasesInnerFromJSON,
    BucketEmailAliasesInnerFromJSONTyped,
    BucketEmailAliasesInnerToJSON,
    BucketEmailAliasesInnerToJSONTyped,
} from './BucketEmailAliasesInner';

/**
 * Receiving address/state on creation and authorized opt-in reads. Ordinary bucket reads expose activity only; use the emails collection for a durable arrival cursor.
 * @export
 * @interface BucketEmail
 */
export interface BucketEmail {
    /**
     * 
     */
    address?: string | null;
    /**
     * 
     */
    receivedCount?: number;
    /**
     * 
     */
    lastReceivedAt?: Date | null;
    /**
     * Latest message folder with trailing slash; null before receipt. May become stale after manual file moves/deletion.
     */
    lastReceivedPath?: string | null;
    /**
     * Why receiving is unavailable; omitted when receiving_enabled is true.
     */
    blockedReason?: string | null;
    /**
     * 
     */
    availableDomains?: Array<BucketEmailAvailableDomainsInner>;
    /**
     * 
     */
    assignment?: BucketEmailAssignment;
    /**
     * 
     */
    customization?: BucketEmailCustomization;
    /**
     * Whether this mailbox can currently receive email. False when configuration, account state, quota or routing prevents receiving.
     */
    receivingEnabled?: boolean;
    /**
     * 
     */
    senderAllowlist?: EmailSenderAllowlist;
    /**
     * 
     */
    username?: string | null;
    /**
     * Always false. Sending is not implemented.
     */
    sendingEnabled?: boolean;
    /**
     * 
     */
    aliases?: Array<BucketEmailAliasesInner>;
}

/**
 * Check if a given object implements the BucketEmail interface.
 */
export function instanceOfBucketEmail(value: object): value is BucketEmail {
    return true;
}

export function BucketEmailFromJSON(json: any): BucketEmail {
    return BucketEmailFromJSONTyped(json, false);
}

export function BucketEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] === undefined ? undefined : json['address'] === null ? null : json['address'],
        'receivedCount': json['received_count'] == null ? undefined : json['received_count'],
        'lastReceivedAt': json['last_received_at'] === undefined ? undefined : json['last_received_at'] === null ? null : (parseDateTime(json['last_received_at'])),
        'lastReceivedPath': json['last_received_path'] === undefined ? undefined : json['last_received_path'] === null ? null : json['last_received_path'],
        'blockedReason': json['blocked_reason'] === undefined ? undefined : json['blocked_reason'] === null ? null : json['blocked_reason'],
        'availableDomains': json['available_domains'] == null ? undefined : ((json['available_domains'] as Array<any>).map(BucketEmailAvailableDomainsInnerFromJSON)),
        'assignment': json['assignment'] == null ? undefined : BucketEmailAssignmentFromJSON(json['assignment']),
        'customization': json['customization'] == null ? undefined : BucketEmailCustomizationFromJSON(json['customization']),
        'receivingEnabled': json['receiving_enabled'] == null ? undefined : json['receiving_enabled'],
        'senderAllowlist': json['sender_allowlist'] == null ? undefined : EmailSenderAllowlistFromJSON(json['sender_allowlist']),
        'username': json['username'] === undefined ? undefined : json['username'] === null ? null : json['username'],
        'sendingEnabled': json['sending_enabled'] == null ? undefined : json['sending_enabled'],
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(BucketEmailAliasesInnerFromJSON)),
    };
}

export function BucketEmailToJSON(json: any): BucketEmail {
    return BucketEmailToJSONTyped(json, false);
}

export function BucketEmailToJSONTyped(value?: BucketEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'received_count': value['receivedCount'],
        'last_received_at': value['lastReceivedAt'] == null ? value['lastReceivedAt'] : serializeDateTime(value['lastReceivedAt']),
        'last_received_path': value['lastReceivedPath'],
        'blocked_reason': value['blockedReason'],
        'available_domains': value['availableDomains'] == null ? undefined : ((value['availableDomains'] as Array<any>).map(BucketEmailAvailableDomainsInnerToJSON)),
        'assignment': BucketEmailAssignmentToJSON(value['assignment']),
        'customization': BucketEmailCustomizationToJSON(value['customization']),
        'receiving_enabled': value['receivingEnabled'],
        'sender_allowlist': EmailSenderAllowlistToJSON(value['senderAllowlist']),
        'username': value['username'],
        'sending_enabled': value['sendingEnabled'],
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(BucketEmailAliasesInnerToJSON)),
    };
}

