/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountEmailDomainRequest
 */
export interface CreateAccountEmailDomainRequest {
    /**
     * Dedicated root or unused subdomain, such as inbox.example.com. Subdomain recommended when root mail already exists.
     */
    hostname: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the CreateAccountEmailDomainRequest interface.
 */
export function instanceOfCreateAccountEmailDomainRequest(value: object): value is CreateAccountEmailDomainRequest {
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    return true;
}

export function CreateAccountEmailDomainRequestFromJSON(json: any): CreateAccountEmailDomainRequest {
    return CreateAccountEmailDomainRequestFromJSONTyped(json, false);
}

export function CreateAccountEmailDomainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountEmailDomainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function CreateAccountEmailDomainRequestToJSON(json: any): CreateAccountEmailDomainRequest {
    return CreateAccountEmailDomainRequestToJSONTyped(json, false);
}

export function CreateAccountEmailDomainRequestToJSONTyped(value?: CreateAccountEmailDomainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'account_id': value['accountId'],
        'reason': value['reason'],
    };
}

