/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BucketEmail } from './BucketEmail';
import {
    BucketEmailFromJSON,
    BucketEmailFromJSONTyped,
    BucketEmailToJSON,
    BucketEmailToJSONTyped,
} from './BucketEmail';

/**
 * 
 * @export
 * @interface CreateBucket201ResponseDataBucket
 */
export interface CreateBucket201ResponseDataBucket {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    email?: BucketEmail;
}

/**
 * Check if a given object implements the CreateBucket201ResponseDataBucket interface.
 */
export function instanceOfCreateBucket201ResponseDataBucket(value: object): value is CreateBucket201ResponseDataBucket {
    return true;
}

export function CreateBucket201ResponseDataBucketFromJSON(json: any): CreateBucket201ResponseDataBucket {
    return CreateBucket201ResponseDataBucketFromJSONTyped(json, false);
}

export function CreateBucket201ResponseDataBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBucket201ResponseDataBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : BucketEmailFromJSON(json['email']),
    };
}

export function CreateBucket201ResponseDataBucketToJSON(json: any): CreateBucket201ResponseDataBucket {
    return CreateBucket201ResponseDataBucketToJSONTyped(json, false);
}

export function CreateBucket201ResponseDataBucketToJSONTyped(value?: CreateBucket201ResponseDataBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': BucketEmailToJSON(value['email']),
    };
}

