/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMailbox201ResponseData } from './CreateMailbox201ResponseData';
import {
    CreateMailbox201ResponseDataFromJSON,
    CreateMailbox201ResponseDataFromJSONTyped,
    CreateMailbox201ResponseDataToJSON,
    CreateMailbox201ResponseDataToJSONTyped,
} from './CreateMailbox201ResponseData';

/**
 * 
 * @export
 * @interface CreateMailbox201Response
 */
export interface CreateMailbox201Response {
    /**
     * 
     */
    data: CreateMailbox201ResponseData;
    /**
     * 
     */
    success: boolean;
}

/**
 * Check if a given object implements the CreateMailbox201Response interface.
 */
export function instanceOfCreateMailbox201Response(value: object): value is CreateMailbox201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function CreateMailbox201ResponseFromJSON(json: any): CreateMailbox201Response {
    return CreateMailbox201ResponseFromJSONTyped(json, false);
}

export function CreateMailbox201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMailbox201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CreateMailbox201ResponseDataFromJSON(json['data']),
        'success': json['success'],
    };
}

export function CreateMailbox201ResponseToJSON(json: any): CreateMailbox201Response {
    return CreateMailbox201ResponseToJSONTyped(json, false);
}

export function CreateMailbox201ResponseToJSONTyped(value?: CreateMailbox201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CreateMailbox201ResponseDataToJSON(value['data']),
        'success': value['success'],
    };
}

