/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBucketEmailAliasRequest
 */
export interface CreateBucketEmailAliasRequest {
    /**
     * Local part of the new address; platform reserved names are unavailable.
     */
    username: string;
    /**
     * Available platform domain or ready account-owned domain; defaults to the platform domain.
     */
    domain?: string;
}

/**
 * Check if a given object implements the CreateBucketEmailAliasRequest interface.
 */
export function instanceOfCreateBucketEmailAliasRequest(value: object): value is CreateBucketEmailAliasRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateBucketEmailAliasRequestFromJSON(json: any): CreateBucketEmailAliasRequest {
    return CreateBucketEmailAliasRequestFromJSONTyped(json, false);
}

export function CreateBucketEmailAliasRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBucketEmailAliasRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function CreateBucketEmailAliasRequestToJSON(json: any): CreateBucketEmailAliasRequest {
    return CreateBucketEmailAliasRequestToJSONTyped(json, false);
}

export function CreateBucketEmailAliasRequestToJSONTyped(value?: CreateBucketEmailAliasRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'domain': value['domain'],
    };
}

