/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMailboxEmailAliasRequest
 */
export interface CreateMailboxEmailAliasRequest {
    /**
     * Local part of the new address; platform reserved names are unavailable.
     */
    username: string;
    /**
     * Available platform domain or ready account-owned domain; defaults to the platform domain.
     */
    domain?: string;
}

/**
 * Check if a given object implements the CreateMailboxEmailAliasRequest interface.
 */
export function instanceOfCreateMailboxEmailAliasRequest(value: object): value is CreateMailboxEmailAliasRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateMailboxEmailAliasRequestFromJSON(json: any): CreateMailboxEmailAliasRequest {
    return CreateMailboxEmailAliasRequestFromJSONTyped(json, false);
}

export function CreateMailboxEmailAliasRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMailboxEmailAliasRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function CreateMailboxEmailAliasRequestToJSON(json: any): CreateMailboxEmailAliasRequest {
    return CreateMailboxEmailAliasRequestToJSONTyped(json, false);
}

export function CreateMailboxEmailAliasRequestToJSONTyped(value?: CreateMailboxEmailAliasRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'domain': value['domain'],
    };
}

