/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountIdentity } from './AccountIdentity';
import {
    AccountIdentityFromJSON,
    AccountIdentityFromJSONTyped,
    AccountIdentityToJSON,
    AccountIdentityToJSONTyped,
} from './AccountIdentity';

/**
 * 
 * @export
 * @interface CreateClientAccount201ResponseData
 */
export interface CreateClientAccount201ResponseData {
    /**
     * 
     */
    account?: AccountIdentity;
}

/**
 * Check if a given object implements the CreateClientAccount201ResponseData interface.
 */
export function instanceOfCreateClientAccount201ResponseData(value: object): value is CreateClientAccount201ResponseData {
    return true;
}

export function CreateClientAccount201ResponseDataFromJSON(json: any): CreateClientAccount201ResponseData {
    return CreateClientAccount201ResponseDataFromJSONTyped(json, false);
}

export function CreateClientAccount201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClientAccount201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : AccountIdentityFromJSON(json['account']),
    };
}

export function CreateClientAccount201ResponseDataToJSON(json: any): CreateClientAccount201ResponseData {
    return CreateClientAccount201ResponseDataToJSONTyped(json, false);
}

export function CreateClientAccount201ResponseDataToJSONTyped(value?: CreateClientAccount201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': AccountIdentityToJSON(value['account']),
    };
}

