/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBucketRequestBucketEmail
 */
export interface CreateBucketRequestBucketEmail {
    /**
     * Name before @. Normalized to lowercase. Omit to generate; blank/null is invalid. Reserved platform names return EMAIL_NAME_RESERVED; occupied or retired names return EMAIL_ALREADY_EXISTS.
     */
    username?: string;
    /**
     * Built-in domain such as revdokumail.com on any plan, or a ready custom email domain owned by the selected account on an eligible plan. Omit for the default platform domain.
     */
    domain?: string;
}

/**
 * Check if a given object implements the CreateBucketRequestBucketEmail interface.
 */
export function instanceOfCreateBucketRequestBucketEmail(value: object): value is CreateBucketRequestBucketEmail {
    return true;
}

export function CreateBucketRequestBucketEmailFromJSON(json: any): CreateBucketRequestBucketEmail {
    return CreateBucketRequestBucketEmailFromJSONTyped(json, false);
}

export function CreateBucketRequestBucketEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBucketRequestBucketEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function CreateBucketRequestBucketEmailToJSON(json: any): CreateBucketRequestBucketEmail {
    return CreateBucketRequestBucketEmailToJSONTyped(json, false);
}

export function CreateBucketRequestBucketEmailToJSONTyped(value?: CreateBucketRequestBucketEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'domain': value['domain'],
    };
}

