/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMailboxRequestMailboxEmail
 */
export interface CreateMailboxRequestMailboxEmail {
    /**
     * Name before @. Normalized to lowercase. Omit to generate; blank/null is invalid. Reserved platform names return EMAIL_NAME_RESERVED; occupied or retired names return EMAIL_ALREADY_EXISTS.
     */
    username?: string;
    /**
     * Built-in domain such as revdokumail.com on any plan, or a ready custom email domain owned by the selected account on an eligible plan. Omit for the default platform domain.
     */
    domain?: string;
}

/**
 * Check if a given object implements the CreateMailboxRequestMailboxEmail interface.
 */
export function instanceOfCreateMailboxRequestMailboxEmail(value: object): value is CreateMailboxRequestMailboxEmail {
    return true;
}

export function CreateMailboxRequestMailboxEmailFromJSON(json: any): CreateMailboxRequestMailboxEmail {
    return CreateMailboxRequestMailboxEmailFromJSONTyped(json, false);
}

export function CreateMailboxRequestMailboxEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMailboxRequestMailboxEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function CreateMailboxRequestMailboxEmailToJSON(json: any): CreateMailboxRequestMailboxEmail {
    return CreateMailboxRequestMailboxEmailToJSONTyped(json, false);
}

export function CreateMailboxRequestMailboxEmailToJSONTyped(value?: CreateMailboxRequestMailboxEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'domain': value['domain'],
    };
}

