/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBucket201ResponseDataBucket } from './CreateBucket201ResponseDataBucket';
import {
    CreateBucket201ResponseDataBucketFromJSON,
    CreateBucket201ResponseDataBucketFromJSONTyped,
    CreateBucket201ResponseDataBucketToJSON,
    CreateBucket201ResponseDataBucketToJSONTyped,
} from './CreateBucket201ResponseDataBucket';

/**
 * 
 * @export
 * @interface CreateBucket201ResponseData
 */
export interface CreateBucket201ResponseData {
    /**
     * 
     */
    bucket?: CreateBucket201ResponseDataBucket;
}

/**
 * Check if a given object implements the CreateBucket201ResponseData interface.
 */
export function instanceOfCreateBucket201ResponseData(value: object): value is CreateBucket201ResponseData {
    return true;
}

export function CreateBucket201ResponseDataFromJSON(json: any): CreateBucket201ResponseData {
    return CreateBucket201ResponseDataFromJSONTyped(json, false);
}

export function CreateBucket201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBucket201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket': json['bucket'] == null ? undefined : CreateBucket201ResponseDataBucketFromJSON(json['bucket']),
    };
}

export function CreateBucket201ResponseDataToJSON(json: any): CreateBucket201ResponseData {
    return CreateBucket201ResponseDataToJSONTyped(json, false);
}

export function CreateBucket201ResponseDataToJSONTyped(value?: CreateBucket201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket': CreateBucket201ResponseDataBucketToJSON(value['bucket']),
    };
}

