/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBucket201ResponseData } from './CreateBucket201ResponseData';
import {
    CreateBucket201ResponseDataFromJSON,
    CreateBucket201ResponseDataFromJSONTyped,
    CreateBucket201ResponseDataToJSON,
    CreateBucket201ResponseDataToJSONTyped,
} from './CreateBucket201ResponseData';

/**
 * 
 * @export
 * @interface CreateBucket201Response
 */
export interface CreateBucket201Response {
    /**
     * 
     */
    data: CreateBucket201ResponseData;
    /**
     * 
     */
    success: boolean;
}

/**
 * Check if a given object implements the CreateBucket201Response interface.
 */
export function instanceOfCreateBucket201Response(value: object): value is CreateBucket201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function CreateBucket201ResponseFromJSON(json: any): CreateBucket201Response {
    return CreateBucket201ResponseFromJSONTyped(json, false);
}

export function CreateBucket201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBucket201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CreateBucket201ResponseDataFromJSON(json['data']),
        'success': json['success'],
    };
}

export function CreateBucket201ResponseToJSON(json: any): CreateBucket201Response {
    return CreateBucket201ResponseToJSONTyped(json, false);
}

export function CreateBucket201ResponseToJSONTyped(value?: CreateBucket201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CreateBucket201ResponseDataToJSON(value['data']),
        'success': value['success'],
    };
}

