/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxCreateOptions } from './MailboxCreateOptions';
import {
    MailboxCreateOptionsFromJSON,
    MailboxCreateOptionsFromJSONTyped,
    MailboxCreateOptionsToJSON,
    MailboxCreateOptionsToJSONTyped,
} from './MailboxCreateOptions';

/**
 * 
 * @export
 * @interface CreateMailboxRequest
 */
export interface CreateMailboxRequest {
    /**
     * 
     */
    accountId?: string;
    /**
     * 
     */
    mailbox: MailboxCreateOptions;
    /**
     * Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the CreateMailboxRequest interface.
 */
export function instanceOfCreateMailboxRequest(value: object): value is CreateMailboxRequest {
    if (!('mailbox' in value) || value['mailbox'] === undefined) return false;
    return true;
}

export function CreateMailboxRequestFromJSON(json: any): CreateMailboxRequest {
    return CreateMailboxRequestFromJSONTyped(json, false);
}

export function CreateMailboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMailboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'mailbox': MailboxCreateOptionsFromJSON(json['mailbox']),
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function CreateMailboxRequestToJSON(json: any): CreateMailboxRequest {
    return CreateMailboxRequestToJSONTyped(json, false);
}

export function CreateMailboxRequestToJSONTyped(value?: CreateMailboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'mailbox': MailboxCreateOptionsToJSON(value['mailbox']),
        'reason': value['reason'],
    };
}

