/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mailbox } from './Mailbox';
import {
    MailboxFromJSON,
    MailboxFromJSONTyped,
    MailboxToJSON,
    MailboxToJSONTyped,
} from './Mailbox';

/**
 * 
 * @export
 * @interface CreateMailbox201ResponseData
 */
export interface CreateMailbox201ResponseData {
    /**
     * 
     */
    mailbox: Mailbox;
}

/**
 * Check if a given object implements the CreateMailbox201ResponseData interface.
 */
export function instanceOfCreateMailbox201ResponseData(value: object): value is CreateMailbox201ResponseData {
    if (!('mailbox' in value) || value['mailbox'] === undefined) return false;
    return true;
}

export function CreateMailbox201ResponseDataFromJSON(json: any): CreateMailbox201ResponseData {
    return CreateMailbox201ResponseDataFromJSONTyped(json, false);
}

export function CreateMailbox201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMailbox201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'mailbox': MailboxFromJSON(json['mailbox']),
    };
}

export function CreateMailbox201ResponseDataToJSON(json: any): CreateMailbox201ResponseData {
    return CreateMailbox201ResponseDataToJSONTyped(json, false);
}

export function CreateMailbox201ResponseDataToJSONTyped(value?: CreateMailbox201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mailbox': MailboxToJSON(value['mailbox']),
    };
}

