/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMailboxRequestMailboxEmail } from './CreateMailboxRequestMailboxEmail';
import {
    CreateMailboxRequestMailboxEmailFromJSON,
    CreateMailboxRequestMailboxEmailFromJSONTyped,
    CreateMailboxRequestMailboxEmailToJSON,
    CreateMailboxRequestMailboxEmailToJSONTyped,
} from './CreateMailboxRequestMailboxEmail';

/**
 * 
 * @export
 * @interface CreateMailboxRequestMailbox
 */
export interface CreateMailboxRequestMailbox {
    /**
     * Optional display title; defaults to the assigned username.
     */
    title?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     */
    tagIds?: Array<string>;
    /**
     * 
     */
    tagPaths?: Array<string>;
    /**
     * 
     */
    email?: CreateMailboxRequestMailboxEmail;
}

/**
 * Check if a given object implements the CreateMailboxRequestMailbox interface.
 */
export function instanceOfCreateMailboxRequestMailbox(value: object): value is CreateMailboxRequestMailbox {
    return true;
}

export function CreateMailboxRequestMailboxFromJSON(json: any): CreateMailboxRequestMailbox {
    return CreateMailboxRequestMailboxFromJSONTyped(json, false);
}

export function CreateMailboxRequestMailboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMailboxRequestMailbox {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'tagIds': json['tag_ids'] == null ? undefined : json['tag_ids'],
        'tagPaths': json['tag_paths'] == null ? undefined : json['tag_paths'],
        'email': json['email'] == null ? undefined : CreateMailboxRequestMailboxEmailFromJSON(json['email']),
    };
}

export function CreateMailboxRequestMailboxToJSON(json: any): CreateMailboxRequestMailbox {
    return CreateMailboxRequestMailboxToJSONTyped(json, false);
}

export function CreateMailboxRequestMailboxToJSONTyped(value?: CreateMailboxRequestMailbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'metadata': value['metadata'],
        'tag_ids': value['tagIds'],
        'tag_paths': value['tagPaths'],
        'email': CreateMailboxRequestMailboxEmailToJSON(value['email']),
    };
}

