/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { EmailForwardingContent } from './EmailForwardingContent';
import {
    EmailForwardingContentFromJSON,
    EmailForwardingContentFromJSONTyped,
    EmailForwardingContentToJSON,
    EmailForwardingContentToJSONTyped,
} from './EmailForwardingContent';
import type { DecodedEmailAddress } from './DecodedEmailAddress';
import {
    DecodedEmailAddressFromJSON,
    DecodedEmailAddressFromJSONTyped,
    DecodedEmailAddressToJSON,
    DecodedEmailAddressToJSONTyped,
} from './DecodedEmailAddress';
import type { DecodedIncomingMessageAttachmentsInner } from './DecodedIncomingMessageAttachmentsInner';
import {
    DecodedIncomingMessageAttachmentsInnerFromJSON,
    DecodedIncomingMessageAttachmentsInnerFromJSONTyped,
    DecodedIncomingMessageAttachmentsInnerToJSON,
    DecodedIncomingMessageAttachmentsInnerToJSONTyped,
} from './DecodedIncomingMessageAttachmentsInner';

/**
 * Stored message.json, not a dedicated endpoint. UTF-8, at most 512 KiB. Header identities, reply relationships and body are untrusted message data. Original message.eml is authoritative. Structured address, delivery and thread fields are additive in schema v1 and may be absent in older files.
 * @export
 * @interface DecodedIncomingMessage
 */
export interface DecodedIncomingMessage {
    /**
     * 
     */
    schemaVersion: DecodedIncomingMessageSchemaVersionEnum;
    /**
     * 
     */
    subject: string | null;
    /**
     * 
     */
    from: string | null;
    /**
     * 
     */
    to: string | null;
    /**
     * Parsed From authors in header order, retaining multiple authors. Empty when absent/unparseable. Display names are not identity keys.
     */
    fromAddresses?: Array<DecodedEmailAddress>;
    /**
     * Parsed To recipients in header order, with named groups flattened. Empty when absent/unparseable; not trusted delivery routing.
     */
    toAddresses?: Array<DecodedEmailAddress>;
    /**
     * Parsed Cc recipients in header order, with named groups flattened. Empty when absent/unparseable.
     */
    ccAddresses?: Array<DecodedEmailAddress>;
    /**
     * Parsed Reply-To addresses in header order. Empty when absent/unparseable. Does not authorize sending a reply.
     */
    replyToAddresses?: Array<DecodedEmailAddress>;
    /**
     * Sender Message-ID without angle brackets, preserving case. Null when absent/unparseable/ambiguous; never the Revdoku delivery ID.
     */
    messageId?: string | null;
    /**
     * Ordered parent Message-IDs without angle brackets, preserving case. Empty when absent/unparseable; multiple parents are retained.
     */
    inReplyTo?: Array<string>;
    /**
     * Ordered References IDs without angle brackets, preserving case. Empty when absent/unparseable.
     */
    references?: Array<string>;
    /**
     * Revdoku delivery identity, matching email_delivery_id metadata and the original folder suffix. Stable on retries, independent of Message-ID. Copies retain the source identity; not a unique file/copy ID.
     */
    deliveryId?: string;
    /**
     * thr_ plus SHA-256 of thread_anchor_message_id. Best-effort header-derived grouping hint, not authoritative conversation membership or an access grant. Missing ancestry or reused IDs can split/merge hints. Scope lookups to accessible mailboxes.
     */
    threadId?: string | null;
    /**
     * 
     */
    threadIdSource?: DecodedIncomingMessageThreadIdSourceEnum | null;
    /**
     * First References ID, otherwise the sole In-Reply-To ID, otherwise this message's ID if no parent is available. Null without an anchor or when multiple parents lack References.
     */
    threadAnchorMessageId?: string | null;
    /**
     * 
     */
    deliveredTo: string;
    /**
     * 
     */
    receivedAt: Date;
    /**
     * 
     */
    bodyText: string | null;
    /**
     * 
     */
    bodyStatus: DecodedIncomingMessageBodyStatusEnum;
    /**
     * 
     */
    omittedAttachmentCount?: number;
    /**
     * 
     */
    attachments: Array<DecodedIncomingMessageAttachmentsInner>;
    /**
     * 
     */
    forwarding?: EmailForwardingContent;
    /**
     * Decoded Cc header; use the corresponding parsed address array for individual addresses.
     */
    cc?: string | null;
    /**
     * Decoded Reply-To header; use the corresponding parsed address array for individual addresses.
     */
    replyTo?: string | null;
}


/**
 * @export
 */
export const DecodedIncomingMessageSchemaVersionEnum = {
    NUMBER_1: 1,
} as const;
export type DecodedIncomingMessageSchemaVersionEnum = typeof DecodedIncomingMessageSchemaVersionEnum[keyof typeof DecodedIncomingMessageSchemaVersionEnum];

/**
 * @export
 */
export const DecodedIncomingMessageThreadIdSourceEnum = {
    References: 'references',
    InReplyTo: 'in_reply_to',
    MessageId: 'message_id',
} as const;
export type DecodedIncomingMessageThreadIdSourceEnum = typeof DecodedIncomingMessageThreadIdSourceEnum[keyof typeof DecodedIncomingMessageThreadIdSourceEnum];

/**
 * @export
 */
export const DecodedIncomingMessageBodyStatusEnum = {
    Complete: 'complete',
    Empty: 'empty',
    Truncated: 'truncated',
    Unavailable: 'unavailable',
} as const;
export type DecodedIncomingMessageBodyStatusEnum = typeof DecodedIncomingMessageBodyStatusEnum[keyof typeof DecodedIncomingMessageBodyStatusEnum];


/**
 * Check if a given object implements the DecodedIncomingMessage interface.
 */
export function instanceOfDecodedIncomingMessage(value: object): value is DecodedIncomingMessage {
    if ((!('schemaVersion' in (value as Record<string, any>)) && !('schema_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['schemaVersion'] === undefined && (value as Record<string, any>)['schema_version'] === undefined)) return false;
    
    if ((value as Record<string, any>)['schemaVersion'] !== 1 && (value as Record<string, any>)['schema_version'] !== 1) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if ((!('deliveredTo' in (value as Record<string, any>)) && !('delivered_to' in (value as Record<string, any>))) || ((value as Record<string, any>)['deliveredTo'] === undefined && (value as Record<string, any>)['delivered_to'] === undefined)) return false;
    if ((!('receivedAt' in (value as Record<string, any>)) && !('received_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['receivedAt'] === undefined && (value as Record<string, any>)['received_at'] === undefined)) return false;
    if ((!('bodyText' in (value as Record<string, any>)) && !('body_text' in (value as Record<string, any>))) || ((value as Record<string, any>)['bodyText'] === undefined && (value as Record<string, any>)['body_text'] === undefined)) return false;
    if ((!('bodyStatus' in (value as Record<string, any>)) && !('body_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['bodyStatus'] === undefined && (value as Record<string, any>)['body_status'] === undefined)) return false;
    if (!('attachments' in value) || value['attachments'] === undefined) return false;
    return true;
}

export function DecodedIncomingMessageFromJSON(json: any): DecodedIncomingMessage {
    return DecodedIncomingMessageFromJSONTyped(json, false);
}

export function DecodedIncomingMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodedIncomingMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'],
        'subject': json['subject'],
        'from': json['from'],
        'to': json['to'],
        'fromAddresses': json['from_addresses'] == null ? undefined : ((json['from_addresses'] as Array<any>).map(DecodedEmailAddressFromJSON)),
        'toAddresses': json['to_addresses'] == null ? undefined : ((json['to_addresses'] as Array<any>).map(DecodedEmailAddressFromJSON)),
        'ccAddresses': json['cc_addresses'] == null ? undefined : ((json['cc_addresses'] as Array<any>).map(DecodedEmailAddressFromJSON)),
        'replyToAddresses': json['reply_to_addresses'] == null ? undefined : ((json['reply_to_addresses'] as Array<any>).map(DecodedEmailAddressFromJSON)),
        'messageId': json['message_id'] === undefined ? undefined : json['message_id'] === null ? null : json['message_id'],
        'inReplyTo': json['in_reply_to'] == null ? undefined : json['in_reply_to'],
        'references': json['references'] == null ? undefined : json['references'],
        'deliveryId': json['delivery_id'] == null ? undefined : json['delivery_id'],
        'threadId': json['thread_id'] === undefined ? undefined : json['thread_id'] === null ? null : json['thread_id'],
        'threadIdSource': json['thread_id_source'] === undefined ? undefined : json['thread_id_source'] === null ? null : json['thread_id_source'],
        'threadAnchorMessageId': json['thread_anchor_message_id'] === undefined ? undefined : json['thread_anchor_message_id'] === null ? null : json['thread_anchor_message_id'],
        'deliveredTo': json['delivered_to'],
        'receivedAt': (json['received_at'] == null ? json['received_at'] : parseDateTime(json['received_at'])),
        'bodyText': json['body_text'],
        'bodyStatus': json['body_status'],
        'omittedAttachmentCount': json['omitted_attachment_count'] == null ? undefined : json['omitted_attachment_count'],
        'attachments': ((json['attachments'] as Array<any>).map(DecodedIncomingMessageAttachmentsInnerFromJSON)),
        'forwarding': json['forwarding'] == null ? undefined : EmailForwardingContentFromJSON(json['forwarding']),
        'cc': json['cc'] === undefined ? undefined : json['cc'] === null ? null : json['cc'],
        'replyTo': json['reply_to'] === undefined ? undefined : json['reply_to'] === null ? null : json['reply_to'],
    };
}

export function DecodedIncomingMessageToJSON(json: any): DecodedIncomingMessage {
    return DecodedIncomingMessageToJSONTyped(json, false);
}

export function DecodedIncomingMessageToJSONTyped(value?: DecodedIncomingMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'subject': value['subject'],
        'from': value['from'],
        'to': value['to'],
        'from_addresses': value['fromAddresses'] == null ? undefined : ((value['fromAddresses'] as Array<any>).map(DecodedEmailAddressToJSON)),
        'to_addresses': value['toAddresses'] == null ? undefined : ((value['toAddresses'] as Array<any>).map(DecodedEmailAddressToJSON)),
        'cc_addresses': value['ccAddresses'] == null ? undefined : ((value['ccAddresses'] as Array<any>).map(DecodedEmailAddressToJSON)),
        'reply_to_addresses': value['replyToAddresses'] == null ? undefined : ((value['replyToAddresses'] as Array<any>).map(DecodedEmailAddressToJSON)),
        'message_id': value['messageId'],
        'in_reply_to': value['inReplyTo'],
        'references': value['references'],
        'delivery_id': value['deliveryId'],
        'thread_id': value['threadId'],
        'thread_id_source': value['threadIdSource'],
        'thread_anchor_message_id': value['threadAnchorMessageId'],
        'delivered_to': value['deliveredTo'],
        'received_at': value['receivedAt'] == null ? value['receivedAt'] : serializeDateTime(value['receivedAt']),
        'body_text': value['bodyText'],
        'body_status': value['bodyStatus'],
        'omitted_attachment_count': value['omittedAttachmentCount'],
        'attachments': ((value['attachments'] as Array<any>).map(DecodedIncomingMessageAttachmentsInnerToJSON)),
        'forwarding': EmailForwardingContentToJSON(value['forwarding']),
        'cc': value['cc'],
        'reply_to': value['replyTo'],
    };
}

