/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecodedEmailAddress
 */
export interface DecodedEmailAddress {
    /**
     * 
     */
    address: string;
    /**
     * 
     */
    name: string | null;
}

/**
 * Check if a given object implements the DecodedEmailAddress interface.
 */
export function instanceOfDecodedEmailAddress(value: object): value is DecodedEmailAddress {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DecodedEmailAddressFromJSON(json: any): DecodedEmailAddress {
    return DecodedEmailAddressFromJSONTyped(json, false);
}

export function DecodedEmailAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodedEmailAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'name': json['name'],
    };
}

export function DecodedEmailAddressToJSON(json: any): DecodedEmailAddress {
    return DecodedEmailAddressToJSONTyped(json, false);
}

export function DecodedEmailAddressToJSONTyped(value?: DecodedEmailAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'name': value['name'],
    };
}

