/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecodedIncomingMessageAttachmentsInner
 */
export interface DecodedIncomingMessageAttachmentsInner {
    /**
     * Relative to message folder.
     */
    path: string;
    /**
     * 
     */
    originalFilename: string;
    /**
     * 
     */
    contentType: string;
    /**
     * 
     */
    sizeBytes: number;
    /**
     * For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
     */
    origin?: DecodedIncomingMessageAttachmentsInnerOriginEnum;
}


/**
 * @export
 */
export const DecodedIncomingMessageAttachmentsInnerOriginEnum = {
    Original: 'original',
    Forwarder: 'forwarder',
    ForwardedMessage: 'forwarded_message',
    Unspecified: 'unspecified',
} as const;
export type DecodedIncomingMessageAttachmentsInnerOriginEnum = typeof DecodedIncomingMessageAttachmentsInnerOriginEnum[keyof typeof DecodedIncomingMessageAttachmentsInnerOriginEnum];


/**
 * Check if a given object implements the DecodedIncomingMessageAttachmentsInner interface.
 */
export function instanceOfDecodedIncomingMessageAttachmentsInner(value: object): value is DecodedIncomingMessageAttachmentsInner {
    if (!('path' in value) || value['path'] === undefined) return false;
    if ((!('originalFilename' in (value as Record<string, any>)) && !('original_filename' in (value as Record<string, any>))) || ((value as Record<string, any>)['originalFilename'] === undefined && (value as Record<string, any>)['original_filename'] === undefined)) return false;
    if ((!('contentType' in (value as Record<string, any>)) && !('content_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentType'] === undefined && (value as Record<string, any>)['content_type'] === undefined)) return false;
    if ((!('sizeBytes' in (value as Record<string, any>)) && !('size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['sizeBytes'] === undefined && (value as Record<string, any>)['size_bytes'] === undefined)) return false;
    return true;
}

export function DecodedIncomingMessageAttachmentsInnerFromJSON(json: any): DecodedIncomingMessageAttachmentsInner {
    return DecodedIncomingMessageAttachmentsInnerFromJSONTyped(json, false);
}

export function DecodedIncomingMessageAttachmentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodedIncomingMessageAttachmentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'originalFilename': json['original_filename'],
        'contentType': json['content_type'],
        'sizeBytes': json['size_bytes'],
        'origin': json['origin'] == null ? undefined : json['origin'],
    };
}

export function DecodedIncomingMessageAttachmentsInnerToJSON(json: any): DecodedIncomingMessageAttachmentsInner {
    return DecodedIncomingMessageAttachmentsInnerToJSONTyped(json, false);
}

export function DecodedIncomingMessageAttachmentsInnerToJSONTyped(value?: DecodedIncomingMessageAttachmentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'original_filename': value['originalFilename'],
        'content_type': value['contentType'],
        'size_bytes': value['sizeBytes'],
        'origin': value['origin'],
    };
}

