/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DnsRecord
 */
export interface DnsRecord {
    /**
     * 
     */
    type: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    value: string;
    /**
     * 
     */
    purpose: string;
    /**
     * 
     */
    zone: string;
    /**
     * 
     */
    relativeName: string;
}

/**
 * Check if a given object implements the DnsRecord interface.
 */
export function instanceOfDnsRecord(value: object): value is DnsRecord {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (!('zone' in value) || value['zone'] === undefined) return false;
    if ((!('relativeName' in (value as Record<string, any>)) && !('relative_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['relativeName'] === undefined && (value as Record<string, any>)['relative_name'] === undefined)) return false;
    return true;
}

export function DnsRecordFromJSON(json: any): DnsRecord {
    return DnsRecordFromJSONTyped(json, false);
}

export function DnsRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): DnsRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'value': json['value'],
        'purpose': json['purpose'],
        'zone': json['zone'],
        'relativeName': json['relative_name'],
    };
}

export function DnsRecordToJSON(json: any): DnsRecord {
    return DnsRecordToJSONTyped(json, false);
}

export function DnsRecordToJSONTyped(value?: DnsRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'value': value['value'],
        'purpose': value['purpose'],
        'zone': value['zone'],
        'relative_name': value['relativeName'],
    };
}

