/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailDownload } from './EmailDownload';
import {
    EmailDownloadFromJSON,
    EmailDownloadFromJSONTyped,
    EmailDownloadToJSON,
    EmailDownloadToJSONTyped,
} from './EmailDownload';

/**
 * 
 * @export
 * @interface DownloadEmailOriginal200ResponseData
 */
export interface DownloadEmailOriginal200ResponseData {
    /**
     * 
     */
    download: EmailDownload;
}

/**
 * Check if a given object implements the DownloadEmailOriginal200ResponseData interface.
 */
export function instanceOfDownloadEmailOriginal200ResponseData(value: object): value is DownloadEmailOriginal200ResponseData {
    if (!('download' in value) || value['download'] === undefined) return false;
    return true;
}

export function DownloadEmailOriginal200ResponseDataFromJSON(json: any): DownloadEmailOriginal200ResponseData {
    return DownloadEmailOriginal200ResponseDataFromJSONTyped(json, false);
}

export function DownloadEmailOriginal200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadEmailOriginal200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'download': EmailDownloadFromJSON(json['download']),
    };
}

export function DownloadEmailOriginal200ResponseDataToJSON(json: any): DownloadEmailOriginal200ResponseData {
    return DownloadEmailOriginal200ResponseDataToJSONTyped(json, false);
}

export function DownloadEmailOriginal200ResponseDataToJSONTyped(value?: DownloadEmailOriginal200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'download': EmailDownloadToJSON(value['download']),
    };
}

