/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxEmail } from './MailboxEmail';
import {
    MailboxEmailFromJSON,
    MailboxEmailFromJSONTyped,
    MailboxEmailToJSON,
    MailboxEmailToJSONTyped,
} from './MailboxEmail';

/**
 * 
 * @export
 * @interface EmailDomainAssignedMailboxesInner
 */
export interface EmailDomainAssignedMailboxesInner {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    email?: MailboxEmail;
}

/**
 * Check if a given object implements the EmailDomainAssignedMailboxesInner interface.
 */
export function instanceOfEmailDomainAssignedMailboxesInner(value: object): value is EmailDomainAssignedMailboxesInner {
    return true;
}

export function EmailDomainAssignedMailboxesInnerFromJSON(json: any): EmailDomainAssignedMailboxesInner {
    return EmailDomainAssignedMailboxesInnerFromJSONTyped(json, false);
}

export function EmailDomainAssignedMailboxesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomainAssignedMailboxesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : MailboxEmailFromJSON(json['email']),
    };
}

export function EmailDomainAssignedMailboxesInnerToJSON(json: any): EmailDomainAssignedMailboxesInner {
    return EmailDomainAssignedMailboxesInnerToJSONTyped(json, false);
}

export function EmailDomainAssignedMailboxesInnerToJSONTyped(value?: EmailDomainAssignedMailboxesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': MailboxEmailToJSON(value['email']),
    };
}

