/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailDownload
 */
export interface EmailDownload {
    /**
     * 
     */
    url: string;
    /**
     * 
     */
    authentication: EmailDownloadAuthenticationEnum;
    /**
     * 
     */
    filename: string;
    /**
     * 
     */
    contentType: string | null;
    /**
     * 
     */
    expiresIn: EmailDownloadExpiresInEnum;
    /**
     * 
     */
    sizeBytes: number;
}


/**
 * @export
 */
export const EmailDownloadAuthenticationEnum = {
    None: 'none',
} as const;
export type EmailDownloadAuthenticationEnum = typeof EmailDownloadAuthenticationEnum[keyof typeof EmailDownloadAuthenticationEnum];

/**
 * @export
 */
export const EmailDownloadExpiresInEnum = {
    NUMBER_900: 900,
} as const;
export type EmailDownloadExpiresInEnum = typeof EmailDownloadExpiresInEnum[keyof typeof EmailDownloadExpiresInEnum];


/**
 * Check if a given object implements the EmailDownload interface.
 */
export function instanceOfEmailDownload(value: object): value is EmailDownload {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('authentication' in value) || value['authentication'] === undefined) return false;
    if (value['authentication'] !== 'none') return false;
    
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if ((!('contentType' in (value as Record<string, any>)) && !('content_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentType'] === undefined && (value as Record<string, any>)['content_type'] === undefined)) return false;
    if ((!('expiresIn' in (value as Record<string, any>)) && !('expires_in' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresIn'] === undefined && (value as Record<string, any>)['expires_in'] === undefined)) return false;
    
    if ((value as Record<string, any>)['expiresIn'] !== 900 && (value as Record<string, any>)['expires_in'] !== 900) return false;
    if ((!('sizeBytes' in (value as Record<string, any>)) && !('size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['sizeBytes'] === undefined && (value as Record<string, any>)['size_bytes'] === undefined)) return false;
    return true;
}

export function EmailDownloadFromJSON(json: any): EmailDownload {
    return EmailDownloadFromJSONTyped(json, false);
}

export function EmailDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDownload {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'authentication': json['authentication'],
        'filename': json['filename'],
        'contentType': json['content_type'],
        'expiresIn': json['expires_in'],
        'sizeBytes': json['size_bytes'],
    };
}

export function EmailDownloadToJSON(json: any): EmailDownload {
    return EmailDownloadToJSONTyped(json, false);
}

export function EmailDownloadToJSONTyped(value?: EmailDownload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'authentication': value['authentication'],
        'filename': value['filename'],
        'content_type': value['contentType'],
        'expires_in': value['expiresIn'],
        'size_bytes': value['sizeBytes'],
    };
}

