/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { EmailDomainAssignedMailboxesInner } from './EmailDomainAssignedMailboxesInner';
import {
    EmailDomainAssignedMailboxesInnerFromJSON,
    EmailDomainAssignedMailboxesInnerFromJSONTyped,
    EmailDomainAssignedMailboxesInnerToJSON,
    EmailDomainAssignedMailboxesInnerToJSONTyped,
} from './EmailDomainAssignedMailboxesInner';
import type { DnsRecord } from './DnsRecord';
import {
    DnsRecordFromJSON,
    DnsRecordFromJSONTyped,
    DnsRecordToJSON,
    DnsRecordToJSONTyped,
} from './DnsRecord';
import type { EmailDomainError } from './EmailDomainError';
import {
    EmailDomainErrorFromJSON,
    EmailDomainErrorFromJSONTyped,
    EmailDomainErrorToJSON,
    EmailDomainErrorToJSONTyped,
} from './EmailDomainError';

/**
 * 
 * @export
 * @interface EmailDomain
 */
export interface EmailDomain {
    /**
     * 
     */
    suggestedSubdomain?: string | null;
    /**
     * 
     */
    rootGuidance?: string | null;
    /**
     * 
     */
    pauseReason?: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    hostname: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    guidance?: string;
    /**
     * 
     */
    receiving?: boolean;
    /**
     * 
     */
    rootDomain?: boolean;
    /**
     * 
     */
    pausedAt?: Date | null;
    /**
     * 
     */
    lastCheckedAt?: Date | null;
    /**
     * 
     */
    ownershipVerifiedAt?: Date | null;
    /**
     * 
     */
    setupExpiresAt?: Date | null;
    /**
     * 
     */
    readyAt?: Date | null;
    /**
     * 
     */
    requiredDnsRecords?: Array<DnsRecord>;
    /**
     * 
     */
    error?: EmailDomainError | null;
    /**
     * 
     */
    assignedMailboxes?: Array<EmailDomainAssignedMailboxesInner>;
}

/**
 * Check if a given object implements the EmailDomain interface.
 */
export function instanceOfEmailDomain(value: object): value is EmailDomain {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EmailDomainFromJSON(json: any): EmailDomain {
    return EmailDomainFromJSONTyped(json, false);
}

export function EmailDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestedSubdomain': json['suggested_subdomain'] === undefined ? undefined : json['suggested_subdomain'] === null ? null : json['suggested_subdomain'],
        'rootGuidance': json['root_guidance'] === undefined ? undefined : json['root_guidance'] === null ? null : json['root_guidance'],
        'pauseReason': json['pause_reason'] === undefined ? undefined : json['pause_reason'] === null ? null : json['pause_reason'],
        'id': json['id'],
        'hostname': json['hostname'],
        'status': json['status'],
        'guidance': json['guidance'] == null ? undefined : json['guidance'],
        'receiving': json['receiving'] == null ? undefined : json['receiving'],
        'rootDomain': json['root_domain'] == null ? undefined : json['root_domain'],
        'pausedAt': json['paused_at'] === undefined ? undefined : json['paused_at'] === null ? null : (parseDateTime(json['paused_at'])),
        'lastCheckedAt': json['last_checked_at'] === undefined ? undefined : json['last_checked_at'] === null ? null : (parseDateTime(json['last_checked_at'])),
        'ownershipVerifiedAt': json['ownership_verified_at'] === undefined ? undefined : json['ownership_verified_at'] === null ? null : (parseDateTime(json['ownership_verified_at'])),
        'setupExpiresAt': json['setup_expires_at'] === undefined ? undefined : json['setup_expires_at'] === null ? null : (parseDateTime(json['setup_expires_at'])),
        'readyAt': json['ready_at'] === undefined ? undefined : json['ready_at'] === null ? null : (parseDateTime(json['ready_at'])),
        'requiredDnsRecords': json['required_dns_records'] == null ? undefined : ((json['required_dns_records'] as Array<any>).map(DnsRecordFromJSON)),
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : EmailDomainErrorFromJSON(json['error']),
        'assignedMailboxes': json['assigned_mailboxes'] == null ? undefined : ((json['assigned_mailboxes'] as Array<any>).map(EmailDomainAssignedMailboxesInnerFromJSON)),
    };
}

export function EmailDomainToJSON(json: any): EmailDomain {
    return EmailDomainToJSONTyped(json, false);
}

export function EmailDomainToJSONTyped(value?: EmailDomain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggested_subdomain': value['suggestedSubdomain'],
        'root_guidance': value['rootGuidance'],
        'pause_reason': value['pauseReason'],
        'id': value['id'],
        'hostname': value['hostname'],
        'status': value['status'],
        'guidance': value['guidance'],
        'receiving': value['receiving'],
        'root_domain': value['rootDomain'],
        'paused_at': value['pausedAt'] == null ? value['pausedAt'] : serializeDateTime(value['pausedAt']),
        'last_checked_at': value['lastCheckedAt'] == null ? value['lastCheckedAt'] : serializeDateTime(value['lastCheckedAt']),
        'ownership_verified_at': value['ownershipVerifiedAt'] == null ? value['ownershipVerifiedAt'] : serializeDateTime(value['ownershipVerifiedAt']),
        'setup_expires_at': value['setupExpiresAt'] == null ? value['setupExpiresAt'] : serializeDateTime(value['setupExpiresAt']),
        'ready_at': value['readyAt'] == null ? value['readyAt'] : serializeDateTime(value['readyAt']),
        'required_dns_records': value['requiredDnsRecords'] == null ? undefined : ((value['requiredDnsRecords'] as Array<any>).map(DnsRecordToJSON)),
        'error': EmailDomainErrorToJSON(value['error']),
        'assigned_mailboxes': value['assignedMailboxes'] == null ? undefined : ((value['assignedMailboxes'] as Array<any>).map(EmailDomainAssignedMailboxesInnerToJSON)),
    };
}

