/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface EmailUsage
 */
export interface EmailUsage {
    /**
     * 
     */
    used?: number;
    /**
     * 
     */
    monthlyLimit?: number;
    /**
     * 
     */
    remaining?: number;
    /**
     * 
     */
    bytesUsed?: number;
    /**
     * 
     */
    monthlyBytesLimit?: number;
    /**
     * 
     */
    bytesRemaining?: number;
    /**
     * 
     */
    maxMessageBytes?: number;
    /**
     * 
     */
    resetsAt?: Date;
    /**
     * 
     */
    paused?: boolean;
    /**
     * 
     */
    pauseReason?: string | null;
}

/**
 * Check if a given object implements the EmailUsage interface.
 */
export function instanceOfEmailUsage(value: object): value is EmailUsage {
    return true;
}

export function EmailUsageFromJSON(json: any): EmailUsage {
    return EmailUsageFromJSONTyped(json, false);
}

export function EmailUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'] == null ? undefined : json['used'],
        'monthlyLimit': json['monthly_limit'] == null ? undefined : json['monthly_limit'],
        'remaining': json['remaining'] == null ? undefined : json['remaining'],
        'bytesUsed': json['bytes_used'] == null ? undefined : json['bytes_used'],
        'monthlyBytesLimit': json['monthly_bytes_limit'] == null ? undefined : json['monthly_bytes_limit'],
        'bytesRemaining': json['bytes_remaining'] == null ? undefined : json['bytes_remaining'],
        'maxMessageBytes': json['max_message_bytes'] == null ? undefined : json['max_message_bytes'],
        'resetsAt': json['resets_at'] == null ? undefined : (parseDateTime(json['resets_at'])),
        'paused': json['paused'] == null ? undefined : json['paused'],
        'pauseReason': json['pause_reason'] === undefined ? undefined : json['pause_reason'] === null ? null : json['pause_reason'],
    };
}

export function EmailUsageToJSON(json: any): EmailUsage {
    return EmailUsageToJSONTyped(json, false);
}

export function EmailUsageToJSONTyped(value?: EmailUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'monthly_limit': value['monthlyLimit'],
        'remaining': value['remaining'],
        'bytes_used': value['bytesUsed'],
        'monthly_bytes_limit': value['monthlyBytesLimit'],
        'bytes_remaining': value['bytesRemaining'],
        'max_message_bytes': value['maxMessageBytes'],
        'resets_at': value['resetsAt'] == null ? value['resetsAt'] : serializeDateTime(value['resetsAt']),
        'paused': value['paused'],
        'pause_reason': value['pauseReason'],
    };
}

