/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { EmailReceivedEventData } from './EmailReceivedEventData';
import {
    EmailReceivedEventDataFromJSON,
    EmailReceivedEventDataFromJSONTyped,
    EmailReceivedEventDataToJSON,
    EmailReceivedEventDataToJSONTyped,
} from './EmailReceivedEventData';

/**
 * 
 * @export
 * @interface EmailReceivedEvent
 */
export interface EmailReceivedEvent {
    /**
     * Stable event ID; deduplicate across retries.
     */
    id: string;
    /**
     * 
     */
    type: EmailReceivedEventTypeEnum;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    data: EmailReceivedEventData;
}


/**
 * @export
 */
export const EmailReceivedEventTypeEnum = {
    EmailReceived: 'email.received',
} as const;
export type EmailReceivedEventTypeEnum = typeof EmailReceivedEventTypeEnum[keyof typeof EmailReceivedEventTypeEnum];


/**
 * Check if a given object implements the EmailReceivedEvent interface.
 */
export function instanceOfEmailReceivedEvent(value: object): value is EmailReceivedEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'email.received') return false;
    
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EmailReceivedEventFromJSON(json: any): EmailReceivedEvent {
    return EmailReceivedEventFromJSONTyped(json, false);
}

export function EmailReceivedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailReceivedEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'data': EmailReceivedEventDataFromJSON(json['data']),
    };
}

export function EmailReceivedEventToJSON(json: any): EmailReceivedEvent {
    return EmailReceivedEventToJSONTyped(json, false);
}

export function EmailReceivedEventToJSONTyped(value?: EmailReceivedEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'data': EmailReceivedEventDataToJSON(value['data']),
    };
}

