/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailDomainList } from './EmailDomainList';
import {
    EmailDomainListFromJSON,
    EmailDomainListFromJSONTyped,
    EmailDomainListToJSON,
    EmailDomainListToJSONTyped,
} from './EmailDomainList';

/**
 * 
 * @export
 * @interface EmailDomainListResponse
 */
export interface EmailDomainListResponse {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: EmailDomainList;
}

/**
 * Check if a given object implements the EmailDomainListResponse interface.
 */
export function instanceOfEmailDomainListResponse(value: object): value is EmailDomainListResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EmailDomainListResponseFromJSON(json: any): EmailDomainListResponse {
    return EmailDomainListResponseFromJSONTyped(json, false);
}

export function EmailDomainListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomainListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': EmailDomainListFromJSON(json['data']),
    };
}

export function EmailDomainListResponseToJSON(json: any): EmailDomainListResponse {
    return EmailDomainListResponseToJSONTyped(json, false);
}

export function EmailDomainListResponseToJSONTyped(value?: EmailDomainListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EmailDomainListToJSON(value['data']),
    };
}

