/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailDomainCheck
 */
export interface EmailDomainCheck {
    /**
     * 
     */
    hostname: string;
    /**
     * 
     */
    rootDomain: boolean;
    /**
     * 
     */
    suggestedSubdomain?: string | null;
    /**
     * 
     */
    rootGuidance?: string;
}

/**
 * Check if a given object implements the EmailDomainCheck interface.
 */
export function instanceOfEmailDomainCheck(value: object): value is EmailDomainCheck {
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if ((!('rootDomain' in (value as Record<string, any>)) && !('root_domain' in (value as Record<string, any>))) || ((value as Record<string, any>)['rootDomain'] === undefined && (value as Record<string, any>)['root_domain'] === undefined)) return false;
    return true;
}

export function EmailDomainCheckFromJSON(json: any): EmailDomainCheck {
    return EmailDomainCheckFromJSONTyped(json, false);
}

export function EmailDomainCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomainCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'],
        'rootDomain': json['root_domain'],
        'suggestedSubdomain': json['suggested_subdomain'] === undefined ? undefined : json['suggested_subdomain'] === null ? null : json['suggested_subdomain'],
        'rootGuidance': json['root_guidance'] == null ? undefined : json['root_guidance'],
    };
}

export function EmailDomainCheckToJSON(json: any): EmailDomainCheck {
    return EmailDomainCheckToJSONTyped(json, false);
}

export function EmailDomainCheckToJSONTyped(value?: EmailDomainCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'root_domain': value['rootDomain'],
        'suggested_subdomain': value['suggestedSubdomain'],
        'root_guidance': value['rootGuidance'],
    };
}

