/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailUsage } from './EmailUsage';
import {
    EmailUsageFromJSON,
    EmailUsageFromJSONTyped,
    EmailUsageToJSON,
    EmailUsageToJSONTyped,
} from './EmailUsage';
import type { EmailDomain } from './EmailDomain';
import {
    EmailDomainFromJSON,
    EmailDomainFromJSONTyped,
    EmailDomainToJSON,
    EmailDomainToJSONTyped,
} from './EmailDomain';

/**
 * 
 * @export
 * @interface EmailDomainList
 */
export interface EmailDomainList {
    /**
     * 
     */
    domains: Array<EmailDomain>;
    /**
     * 
     */
    enabled?: boolean;
    /**
     * 
     */
    configured?: boolean;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    usage?: EmailUsage;
    /**
     * 
     */
    guidance?: string;
}

/**
 * Check if a given object implements the EmailDomainList interface.
 */
export function instanceOfEmailDomainList(value: object): value is EmailDomainList {
    if (!('domains' in value) || value['domains'] === undefined) return false;
    return true;
}

export function EmailDomainListFromJSON(json: any): EmailDomainList {
    return EmailDomainListFromJSONTyped(json, false);
}

export function EmailDomainListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomainList {
    if (json == null) {
        return json;
    }
    return {
        
        'domains': ((json['domains'] as Array<any>).map(EmailDomainFromJSON)),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'configured': json['configured'] == null ? undefined : json['configured'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'usage': json['usage'] == null ? undefined : EmailUsageFromJSON(json['usage']),
        'guidance': json['guidance'] == null ? undefined : json['guidance'],
    };
}

export function EmailDomainListToJSON(json: any): EmailDomainList {
    return EmailDomainListToJSONTyped(json, false);
}

export function EmailDomainListToJSONTyped(value?: EmailDomainList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domains': ((value['domains'] as Array<any>).map(EmailDomainToJSON)),
        'enabled': value['enabled'],
        'configured': value['configured'],
        'limit': value['limit'],
        'usage': EmailUsageToJSON(value['usage']),
        'guidance': value['guidance'],
    };
}

