/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSenderAllowlist
 */
export interface EmailSenderAllowlist {
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    entries: Array<string>;
    /**
     * 
     */
    version: string;
    /**
     * 
     */
    maxEntries: number;
    /**
     * 
     */
    editable: boolean;
}

/**
 * Check if a given object implements the EmailSenderAllowlist interface.
 */
export function instanceOfEmailSenderAllowlist(value: object): value is EmailSenderAllowlist {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if ((!('maxEntries' in (value as Record<string, any>)) && !('max_entries' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxEntries'] === undefined && (value as Record<string, any>)['max_entries'] === undefined)) return false;
    if (!('editable' in value) || value['editable'] === undefined) return false;
    return true;
}

export function EmailSenderAllowlistFromJSON(json: any): EmailSenderAllowlist {
    return EmailSenderAllowlistFromJSONTyped(json, false);
}

export function EmailSenderAllowlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSenderAllowlist {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'entries': json['entries'],
        'version': json['version'],
        'maxEntries': json['max_entries'],
        'editable': json['editable'],
    };
}

export function EmailSenderAllowlistToJSON(json: any): EmailSenderAllowlist {
    return EmailSenderAllowlistToJSONTyped(json, false);
}

export function EmailSenderAllowlistToJSONTyped(value?: EmailSenderAllowlist | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'entries': value['entries'],
        'version': value['version'],
        'max_entries': value['maxEntries'],
        'editable': value['editable'],
    };
}

