/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailDomain } from './EmailDomain';
import {
    EmailDomainFromJSON,
    EmailDomainFromJSONTyped,
    EmailDomainToJSON,
    EmailDomainToJSONTyped,
} from './EmailDomain';

/**
 * 
 * @export
 * @interface EmailDomainResponse
 */
export interface EmailDomainResponse {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: EmailDomain;
}

/**
 * Check if a given object implements the EmailDomainResponse interface.
 */
export function instanceOfEmailDomainResponse(value: object): value is EmailDomainResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EmailDomainResponseFromJSON(json: any): EmailDomainResponse {
    return EmailDomainResponseFromJSONTyped(json, false);
}

export function EmailDomainResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomainResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': EmailDomainFromJSON(json['data']),
    };
}

export function EmailDomainResponseToJSON(json: any): EmailDomainResponse {
    return EmailDomainResponseToJSONTyped(json, false);
}

export function EmailDomainResponseToJSONTyped(value?: EmailDomainResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EmailDomainToJSON(value['data']),
    };
}

