/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailDomainError
 */
export interface EmailDomainError {
    /**
     * 
     */
    code?: string;
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    retryable?: boolean;
}

/**
 * Check if a given object implements the EmailDomainError interface.
 */
export function instanceOfEmailDomainError(value: object): value is EmailDomainError {
    return true;
}

export function EmailDomainErrorFromJSON(json: any): EmailDomainError {
    return EmailDomainErrorFromJSONTyped(json, false);
}

export function EmailDomainErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomainError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'retryable': json['retryable'] == null ? undefined : json['retryable'],
    };
}

export function EmailDomainErrorToJSON(json: any): EmailDomainError {
    return EmailDomainErrorToJSONTyped(json, false);
}

export function EmailDomainErrorToJSONTyped(value?: EmailDomainError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'retryable': value['retryable'],
    };
}

