/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Included only with include_storage=true for file-browser integration.
 * @export
 * @interface EmailSummaryFiles
 */
export interface EmailSummaryFiles {
    /**
     * 
     */
    bodyId: string | null;
    /**
     * 
     */
    originalId: string | null;
    /**
     * 
     */
    attachmentIds: Array<string>;
}

/**
 * Check if a given object implements the EmailSummaryFiles interface.
 */
export function instanceOfEmailSummaryFiles(value: object): value is EmailSummaryFiles {
    if ((!('bodyId' in (value as Record<string, any>)) && !('body_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['bodyId'] === undefined && (value as Record<string, any>)['body_id'] === undefined)) return false;
    if ((!('originalId' in (value as Record<string, any>)) && !('original_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['originalId'] === undefined && (value as Record<string, any>)['original_id'] === undefined)) return false;
    if ((!('attachmentIds' in (value as Record<string, any>)) && !('attachment_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['attachmentIds'] === undefined && (value as Record<string, any>)['attachment_ids'] === undefined)) return false;
    return true;
}

export function EmailSummaryFilesFromJSON(json: any): EmailSummaryFiles {
    return EmailSummaryFilesFromJSONTyped(json, false);
}

export function EmailSummaryFilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSummaryFiles {
    if (json == null) {
        return json;
    }
    return {
        
        'bodyId': json['body_id'],
        'originalId': json['original_id'],
        'attachmentIds': json['attachment_ids'],
    };
}

export function EmailSummaryFilesToJSON(json: any): EmailSummaryFiles {
    return EmailSummaryFilesToJSONTyped(json, false);
}

export function EmailSummaryFilesToJSONTyped(value?: EmailSummaryFiles | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body_id': value['bodyId'],
        'original_id': value['originalId'],
        'attachment_ids': value['attachmentIds'],
    };
}

