/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface EmailReceivedEventData
 */
export interface EmailReceivedEventData {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    mailboxId: string;
    /**
     * 
     */
    emailId: string;
    /**
     * 
     */
    receivedAt: Date;
    /**
     * 
     */
    attachmentCount: number;
}

/**
 * Check if a given object implements the EmailReceivedEventData interface.
 */
export function instanceOfEmailReceivedEventData(value: object): value is EmailReceivedEventData {
    if ((!('accountId' in (value as Record<string, any>)) && !('account_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['accountId'] === undefined && (value as Record<string, any>)['account_id'] === undefined)) return false;
    if ((!('mailboxId' in (value as Record<string, any>)) && !('mailbox_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['mailboxId'] === undefined && (value as Record<string, any>)['mailbox_id'] === undefined)) return false;
    if ((!('emailId' in (value as Record<string, any>)) && !('email_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['emailId'] === undefined && (value as Record<string, any>)['email_id'] === undefined)) return false;
    if ((!('receivedAt' in (value as Record<string, any>)) && !('received_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['receivedAt'] === undefined && (value as Record<string, any>)['received_at'] === undefined)) return false;
    if ((!('attachmentCount' in (value as Record<string, any>)) && !('attachment_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['attachmentCount'] === undefined && (value as Record<string, any>)['attachment_count'] === undefined)) return false;
    return true;
}

export function EmailReceivedEventDataFromJSON(json: any): EmailReceivedEventData {
    return EmailReceivedEventDataFromJSONTyped(json, false);
}

export function EmailReceivedEventDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailReceivedEventData {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'mailboxId': json['mailbox_id'],
        'emailId': json['email_id'],
        'receivedAt': (json['received_at'] == null ? json['received_at'] : parseDateTime(json['received_at'])),
        'attachmentCount': json['attachment_count'],
    };
}

export function EmailReceivedEventDataToJSON(json: any): EmailReceivedEventData {
    return EmailReceivedEventDataToJSONTyped(json, false);
}

export function EmailReceivedEventDataToJSONTyped(value?: EmailReceivedEventData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'mailbox_id': value['mailboxId'],
        'email_id': value['emailId'],
        'received_at': value['receivedAt'] == null ? value['receivedAt'] : serializeDateTime(value['receivedAt']),
        'attachment_count': value['attachmentCount'],
    };
}

