/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailPagination
 */
export interface EmailPagination {
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    hasMore: boolean;
    /**
     * 
     */
    nextCursor: string;
}

/**
 * Check if a given object implements the EmailPagination interface.
 */
export function instanceOfEmailPagination(value: object): value is EmailPagination {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function EmailPaginationFromJSON(json: any): EmailPagination {
    return EmailPaginationFromJSONTyped(json, false);
}

export function EmailPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'hasMore': json['has_more'],
        'nextCursor': json['next_cursor'],
    };
}

export function EmailPaginationToJSON(json: any): EmailPagination {
    return EmailPaginationToJSONTyped(json, false);
}

export function EmailPaginationToJSONTyped(value?: EmailPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'has_more': value['hasMore'],
        'next_cursor': value['nextCursor'],
    };
}

