/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { FileKey } from './FileKey';
import {
    FileKeyFromJSON,
    FileKeyFromJSONTyped,
    FileKeyToJSON,
    FileKeyToJSONTyped,
} from './FileKey';
import type { FileActor } from './FileActor';
import {
    FileActorFromJSON,
    FileActorFromJSONTyped,
    FileActorToJSON,
    FileActorToJSONTyped,
} from './FileActor';

/**
 * 
 * @export
 * @interface FileVersion
 */
export interface FileVersion {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    fileId?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    mimeType?: string;
    /**
     * 
     */
    sha256?: string;
    /**
     * 
     */
    reason?: string | null;
    /**
     * 
     */
    metaKey?: string;
    /**
     * 
     */
    createdBySystem?: string;
    /**
     * 
     */
    deleted?: boolean;
    /**
     * 
     */
    ready?: boolean;
    /**
     * 
     */
    hasText?: boolean;
    /**
     * 
     */
    normalizationRequired?: boolean;
    /**
     * 
     */
    metaReady?: boolean;
    /**
     * 
     */
    versionNumber?: number;
    /**
     * 
     */
    byteSize?: number;
    /**
     * 
     */
    createdAt?: Date;
    /**
     * 
     */
    metaCreatedAt?: Date;
    /**
     * 
     */
    createdBy?: FileActor;
    /**
     * 
     */
    updatedBy?: FileActor;
    /**
     * 
     */
    createdByAgent?: { [key: string]: any; };
    /**
     * 
     */
    updatedByAgent?: { [key: string]: any; };
    /**
     * 
     */
    createdByApiKey?: { [key: string]: any; };
    /**
     * 
     */
    updatedByApiKey?: { [key: string]: any; };
    /**
     * 
     */
    read?: boolean;
    /**
     * 
     */
    readAt?: Date | null;
    /**
     * 
     */
    readBy?: FileActor | null;
    /**
     * 
     */
    readByApiKey?: FileKey | null;
}

/**
 * Check if a given object implements the FileVersion interface.
 */
export function instanceOfFileVersion(value: object): value is FileVersion {
    return true;
}

export function FileVersionFromJSON(json: any): FileVersion {
    return FileVersionFromJSONTyped(json, false);
}

export function FileVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'sha256': json['sha256'] == null ? undefined : json['sha256'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
        'metaKey': json['meta_key'] == null ? undefined : json['meta_key'],
        'createdBySystem': json['created_by_system'] == null ? undefined : json['created_by_system'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'ready': json['ready'] == null ? undefined : json['ready'],
        'hasText': json['has_text'] == null ? undefined : json['has_text'],
        'normalizationRequired': json['normalization_required'] == null ? undefined : json['normalization_required'],
        'metaReady': json['meta_ready'] == null ? undefined : json['meta_ready'],
        'versionNumber': json['version_number'] == null ? undefined : json['version_number'],
        'byteSize': json['byte_size'] == null ? undefined : json['byte_size'],
        'createdAt': json['created_at'] == null ? undefined : (parseDateTime(json['created_at'])),
        'metaCreatedAt': json['meta_created_at'] == null ? undefined : (parseDateTime(json['meta_created_at'])),
        'createdBy': json['created_by'] == null ? undefined : FileActorFromJSON(json['created_by']),
        'updatedBy': json['updated_by'] == null ? undefined : FileActorFromJSON(json['updated_by']),
        'createdByAgent': json['created_by_agent'] == null ? undefined : json['created_by_agent'],
        'updatedByAgent': json['updated_by_agent'] == null ? undefined : json['updated_by_agent'],
        'createdByApiKey': json['created_by_api_key'] == null ? undefined : json['created_by_api_key'],
        'updatedByApiKey': json['updated_by_api_key'] == null ? undefined : json['updated_by_api_key'],
        'read': json['read'] == null ? undefined : json['read'],
        'readAt': json['read_at'] === undefined ? undefined : json['read_at'] === null ? null : (parseDateTime(json['read_at'])),
        'readBy': json['read_by'] === undefined ? undefined : json['read_by'] === null ? null : FileActorFromJSON(json['read_by']),
        'readByApiKey': json['read_by_api_key'] === undefined ? undefined : json['read_by_api_key'] === null ? null : FileKeyFromJSON(json['read_by_api_key']),
    };
}

export function FileVersionToJSON(json: any): FileVersion {
    return FileVersionToJSONTyped(json, false);
}

export function FileVersionToJSONTyped(value?: FileVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'file_id': value['fileId'],
        'name': value['name'],
        'mime_type': value['mimeType'],
        'sha256': value['sha256'],
        'reason': value['reason'],
        'meta_key': value['metaKey'],
        'created_by_system': value['createdBySystem'],
        'deleted': value['deleted'],
        'ready': value['ready'],
        'has_text': value['hasText'],
        'normalization_required': value['normalizationRequired'],
        'meta_ready': value['metaReady'],
        'version_number': value['versionNumber'],
        'byte_size': value['byteSize'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'meta_created_at': value['metaCreatedAt'] == null ? value['metaCreatedAt'] : serializeDateTime(value['metaCreatedAt']),
        'created_by': FileActorToJSON(value['createdBy']),
        'updated_by': FileActorToJSON(value['updatedBy']),
        'created_by_agent': value['createdByAgent'],
        'updated_by_agent': value['updatedByAgent'],
        'created_by_api_key': value['createdByApiKey'],
        'updated_by_api_key': value['updatedByApiKey'],
        'read': value['read'],
        'read_at': value['readAt'] == null ? value['readAt'] : serializeDateTime(value['readAt']),
        'read_by': FileActorToJSON(value['readBy']),
        'read_by_api_key': FileKeyToJSON(value['readByApiKey']),
    };
}

