/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface FileVersionReason
 */
export interface FileVersionReason {
    /**
     * 
     */
    versionId?: string;
    /**
     * 
     */
    reason?: string;
    /**
     * 
     */
    createdById?: string;
    /**
     * 
     */
    versionNumber?: number;
    /**
     * 
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the FileVersionReason interface.
 */
export function instanceOfFileVersionReason(value: object): value is FileVersionReason {
    return true;
}

export function FileVersionReasonFromJSON(json: any): FileVersionReason {
    return FileVersionReasonFromJSONTyped(json, false);
}

export function FileVersionReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileVersionReason {
    if (json == null) {
        return json;
    }
    return {
        
        'versionId': json['version_id'] == null ? undefined : json['version_id'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'createdById': json['created_by_id'] == null ? undefined : json['created_by_id'],
        'versionNumber': json['version_number'] == null ? undefined : json['version_number'],
        'createdAt': json['created_at'] == null ? undefined : (parseDateTime(json['created_at'])),
    };
}

export function FileVersionReasonToJSON(json: any): FileVersionReason {
    return FileVersionReasonToJSONTyped(json, false);
}

export function FileVersionReasonToJSONTyped(value?: FileVersionReason | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version_id': value['versionId'],
        'reason': value['reason'],
        'created_by_id': value['createdById'],
        'version_number': value['versionNumber'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

