/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileKey
 */
export interface FileKey {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    label?: string;
    /**
     * 
     */
    tokenType?: string;
}

/**
 * Check if a given object implements the FileKey interface.
 */
export function instanceOfFileKey(value: object): value is FileKey {
    return true;
}

export function FileKeyFromJSON(json: any): FileKey {
    return FileKeyFromJSONTyped(json, false);
}

export function FileKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileKey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
    };
}

export function FileKeyToJSON(json: any): FileKey {
    return FileKeyToJSONTyped(json, false);
}

export function FileKeyToJSONTyped(value?: FileKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'token_type': value['tokenType'],
    };
}

