/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileActor
 */
export interface FileActor {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    email?: string;
}

/**
 * Check if a given object implements the FileActor interface.
 */
export function instanceOfFileActor(value: object): value is FileActor {
    return true;
}

export function FileActorFromJSON(json: any): FileActor {
    return FileActorFromJSONTyped(json, false);
}

export function FileActorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileActor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function FileActorToJSON(json: any): FileActor {
    return FileActorToJSONTyped(json, false);
}

export function FileActorToJSONTyped(value?: FileActor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
    };
}

