/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilePagination
 */
export interface FilePagination {
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    count: number;
    /**
     * 
     */
    total: number;
    /**
     * 
     */
    hasMore: boolean;
    /**
     * 
     */
    nextOffset: number | null;
}

/**
 * Check if a given object implements the FilePagination interface.
 */
export function instanceOfFilePagination(value: object): value is FilePagination {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    if ((!('nextOffset' in (value as Record<string, any>)) && !('next_offset' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextOffset'] === undefined && (value as Record<string, any>)['next_offset'] === undefined)) return false;
    return true;
}

export function FilePaginationFromJSON(json: any): FilePagination {
    return FilePaginationFromJSONTyped(json, false);
}

export function FilePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'offset': json['offset'],
        'count': json['count'],
        'total': json['total'],
        'hasMore': json['has_more'],
        'nextOffset': json['next_offset'],
    };
}

export function FilePaginationToJSON(json: any): FilePagination {
    return FilePaginationToJSONTyped(json, false);
}

export function FilePaginationToJSONTyped(value?: FilePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'count': value['count'],
        'total': value['total'],
        'has_more': value['hasMore'],
        'next_offset': value['nextOffset'],
    };
}

