/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountLimits200ResponseDataUsageMailboxCreations
 */
export interface GetAccountLimits200ResponseDataUsageMailboxCreations {
    /**
     * 
     */
    used: number;
    /**
     * 
     */
    remaining: number;
    /**
     * 
     */
    monthlyLimit: number;
    /**
     * 
     */
    resetsAt: Date;
}

/**
 * Check if a given object implements the GetAccountLimits200ResponseDataUsageMailboxCreations interface.
 */
export function instanceOfGetAccountLimits200ResponseDataUsageMailboxCreations(value: object): value is GetAccountLimits200ResponseDataUsageMailboxCreations {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    if ((!('monthlyLimit' in (value as Record<string, any>)) && !('monthly_limit' in (value as Record<string, any>))) || ((value as Record<string, any>)['monthlyLimit'] === undefined && (value as Record<string, any>)['monthly_limit'] === undefined)) return false;
    if ((!('resetsAt' in (value as Record<string, any>)) && !('resets_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['resetsAt'] === undefined && (value as Record<string, any>)['resets_at'] === undefined)) return false;
    return true;
}

export function GetAccountLimits200ResponseDataUsageMailboxCreationsFromJSON(json: any): GetAccountLimits200ResponseDataUsageMailboxCreations {
    return GetAccountLimits200ResponseDataUsageMailboxCreationsFromJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataUsageMailboxCreationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountLimits200ResponseDataUsageMailboxCreations {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'remaining': json['remaining'],
        'monthlyLimit': json['monthly_limit'],
        'resetsAt': (json['resets_at'] == null ? json['resets_at'] : parseDateTime(json['resets_at'])),
    };
}

export function GetAccountLimits200ResponseDataUsageMailboxCreationsToJSON(json: any): GetAccountLimits200ResponseDataUsageMailboxCreations {
    return GetAccountLimits200ResponseDataUsageMailboxCreationsToJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataUsageMailboxCreationsToJSONTyped(value?: GetAccountLimits200ResponseDataUsageMailboxCreations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'remaining': value['remaining'],
        'monthly_limit': value['monthlyLimit'],
        'resets_at': value['resetsAt'] == null ? value['resetsAt'] : serializeDateTime(value['resetsAt']),
    };
}

