/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountLimits } from './AccountLimits';
import {
    AccountLimitsFromJSON,
    AccountLimitsFromJSONTyped,
    AccountLimitsToJSON,
    AccountLimitsToJSONTyped,
} from './AccountLimits';
import type { GetAccountLimits200ResponseDataUsage } from './GetAccountLimits200ResponseDataUsage';
import {
    GetAccountLimits200ResponseDataUsageFromJSON,
    GetAccountLimits200ResponseDataUsageFromJSONTyped,
    GetAccountLimits200ResponseDataUsageToJSON,
    GetAccountLimits200ResponseDataUsageToJSONTyped,
} from './GetAccountLimits200ResponseDataUsage';

/**
 * 
 * @export
 * @interface GetAccountLimits200ResponseData
 */
export interface GetAccountLimits200ResponseData {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    limits: AccountLimits;
    /**
     * 
     */
    usage?: GetAccountLimits200ResponseDataUsage;
}

/**
 * Check if a given object implements the GetAccountLimits200ResponseData interface.
 */
export function instanceOfGetAccountLimits200ResponseData(value: object): value is GetAccountLimits200ResponseData {
    if ((!('accountId' in (value as Record<string, any>)) && !('account_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['accountId'] === undefined && (value as Record<string, any>)['account_id'] === undefined)) return false;
    if (!('limits' in value) || value['limits'] === undefined) return false;
    return true;
}

export function GetAccountLimits200ResponseDataFromJSON(json: any): GetAccountLimits200ResponseData {
    return GetAccountLimits200ResponseDataFromJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountLimits200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'limits': AccountLimitsFromJSON(json['limits']),
        'usage': json['usage'] == null ? undefined : GetAccountLimits200ResponseDataUsageFromJSON(json['usage']),
    };
}

export function GetAccountLimits200ResponseDataToJSON(json: any): GetAccountLimits200ResponseData {
    return GetAccountLimits200ResponseDataToJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataToJSONTyped(value?: GetAccountLimits200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'limits': AccountLimitsToJSON(value['limits']),
        'usage': GetAccountLimits200ResponseDataUsageToJSON(value['usage']),
    };
}

