/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountLimits200ResponseDataUsageBucketCreations
 */
export interface GetAccountLimits200ResponseDataUsageBucketCreations {
    /**
     * 
     */
    used: number;
    /**
     * 
     */
    remaining: number;
    /**
     * 
     */
    monthlyLimit: number;
    /**
     * 
     */
    resetsAt: Date;
}

/**
 * Check if a given object implements the GetAccountLimits200ResponseDataUsageBucketCreations interface.
 */
export function instanceOfGetAccountLimits200ResponseDataUsageBucketCreations(value: object): value is GetAccountLimits200ResponseDataUsageBucketCreations {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    if ((!('monthlyLimit' in (value as Record<string, any>)) && !('monthly_limit' in (value as Record<string, any>))) || ((value as Record<string, any>)['monthlyLimit'] === undefined && (value as Record<string, any>)['monthly_limit'] === undefined)) return false;
    if ((!('resetsAt' in (value as Record<string, any>)) && !('resets_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['resetsAt'] === undefined && (value as Record<string, any>)['resets_at'] === undefined)) return false;
    return true;
}

export function GetAccountLimits200ResponseDataUsageBucketCreationsFromJSON(json: any): GetAccountLimits200ResponseDataUsageBucketCreations {
    return GetAccountLimits200ResponseDataUsageBucketCreationsFromJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataUsageBucketCreationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountLimits200ResponseDataUsageBucketCreations {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'remaining': json['remaining'],
        'monthlyLimit': json['monthly_limit'],
        'resetsAt': (json['resets_at'] == null ? json['resets_at'] : parseDateTime(json['resets_at'])),
    };
}

export function GetAccountLimits200ResponseDataUsageBucketCreationsToJSON(json: any): GetAccountLimits200ResponseDataUsageBucketCreations {
    return GetAccountLimits200ResponseDataUsageBucketCreationsToJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataUsageBucketCreationsToJSONTyped(value?: GetAccountLimits200ResponseDataUsageBucketCreations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'remaining': value['remaining'],
        'monthly_limit': value['monthlyLimit'],
        'resets_at': value['resetsAt'] == null ? value['resetsAt'] : serializeDateTime(value['resetsAt']),
    };
}

