/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAccountLimits200ResponseDataUsageBucketCreations } from './GetAccountLimits200ResponseDataUsageBucketCreations';
import {
    GetAccountLimits200ResponseDataUsageBucketCreationsFromJSON,
    GetAccountLimits200ResponseDataUsageBucketCreationsFromJSONTyped,
    GetAccountLimits200ResponseDataUsageBucketCreationsToJSON,
    GetAccountLimits200ResponseDataUsageBucketCreationsToJSONTyped,
} from './GetAccountLimits200ResponseDataUsageBucketCreations';

/**
 * Present only for full-account administrator credentials and full-account browser sessions.
 * @export
 * @interface GetAccountLimits200ResponseDataUsage
 */
export interface GetAccountLimits200ResponseDataUsage {
    /**
     * 
     */
    bucketCreations?: GetAccountLimits200ResponseDataUsageBucketCreations;
}

/**
 * Check if a given object implements the GetAccountLimits200ResponseDataUsage interface.
 */
export function instanceOfGetAccountLimits200ResponseDataUsage(value: object): value is GetAccountLimits200ResponseDataUsage {
    return true;
}

export function GetAccountLimits200ResponseDataUsageFromJSON(json: any): GetAccountLimits200ResponseDataUsage {
    return GetAccountLimits200ResponseDataUsageFromJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountLimits200ResponseDataUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'bucketCreations': json['bucket_creations'] == null ? undefined : GetAccountLimits200ResponseDataUsageBucketCreationsFromJSON(json['bucket_creations']),
    };
}

export function GetAccountLimits200ResponseDataUsageToJSON(json: any): GetAccountLimits200ResponseDataUsage {
    return GetAccountLimits200ResponseDataUsageToJSONTyped(json, false);
}

export function GetAccountLimits200ResponseDataUsageToJSONTyped(value?: GetAccountLimits200ResponseDataUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket_creations': GetAccountLimits200ResponseDataUsageBucketCreationsToJSON(value['bucketCreations']),
    };
}

