/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAccountLimits200ResponseData } from './GetAccountLimits200ResponseData';
import {
    GetAccountLimits200ResponseDataFromJSON,
    GetAccountLimits200ResponseDataFromJSONTyped,
    GetAccountLimits200ResponseDataToJSON,
    GetAccountLimits200ResponseDataToJSONTyped,
} from './GetAccountLimits200ResponseData';

/**
 * 
 * @export
 * @interface GetAccountLimits200Response
 */
export interface GetAccountLimits200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: GetAccountLimits200ResponseData;
}

/**
 * Check if a given object implements the GetAccountLimits200Response interface.
 */
export function instanceOfGetAccountLimits200Response(value: object): value is GetAccountLimits200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetAccountLimits200ResponseFromJSON(json: any): GetAccountLimits200Response {
    return GetAccountLimits200ResponseFromJSONTyped(json, false);
}

export function GetAccountLimits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountLimits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': GetAccountLimits200ResponseDataFromJSON(json['data']),
    };
}

export function GetAccountLimits200ResponseToJSON(json: any): GetAccountLimits200Response {
    return GetAccountLimits200ResponseToJSONTyped(json, false);
}

export function GetAccountLimits200ResponseToJSONTyped(value?: GetAccountLimits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetAccountLimits200ResponseDataToJSON(value['data']),
    };
}

