/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BucketEmail } from './BucketEmail';
import {
    BucketEmailFromJSON,
    BucketEmailFromJSONTyped,
    BucketEmailToJSON,
    BucketEmailToJSONTyped,
} from './BucketEmail';

/**
 * 
 * @export
 * @interface GetBucketEmailSettings200Response
 */
export interface GetBucketEmailSettings200Response {
    /**
     * 
     */
    data: BucketEmail;
    /**
     * 
     */
    success: boolean;
}

/**
 * Check if a given object implements the GetBucketEmailSettings200Response interface.
 */
export function instanceOfGetBucketEmailSettings200Response(value: object): value is GetBucketEmailSettings200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetBucketEmailSettings200ResponseFromJSON(json: any): GetBucketEmailSettings200Response {
    return GetBucketEmailSettings200ResponseFromJSONTyped(json, false);
}

export function GetBucketEmailSettings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBucketEmailSettings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BucketEmailFromJSON(json['data']),
        'success': json['success'],
    };
}

export function GetBucketEmailSettings200ResponseToJSON(json: any): GetBucketEmailSettings200Response {
    return GetBucketEmailSettings200ResponseToJSONTyped(json, false);
}

export function GetBucketEmailSettings200ResponseToJSONTyped(value?: GetBucketEmailSettings200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BucketEmailToJSON(value['data']),
        'success': value['success'],
    };
}

