/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailWebhook200ResponseDataWebhook } from './GetEmailWebhook200ResponseDataWebhook';
import {
    GetEmailWebhook200ResponseDataWebhookFromJSON,
    GetEmailWebhook200ResponseDataWebhookFromJSONTyped,
    GetEmailWebhook200ResponseDataWebhookToJSON,
    GetEmailWebhook200ResponseDataWebhookToJSONTyped,
} from './GetEmailWebhook200ResponseDataWebhook';

/**
 * 
 * @export
 * @interface GetEmailWebhook200ResponseData
 */
export interface GetEmailWebhook200ResponseData {
    /**
     * 
     */
    webhook: GetEmailWebhook200ResponseDataWebhook | null;
}

/**
 * Check if a given object implements the GetEmailWebhook200ResponseData interface.
 */
export function instanceOfGetEmailWebhook200ResponseData(value: object): value is GetEmailWebhook200ResponseData {
    if (!('webhook' in value) || value['webhook'] === undefined) return false;
    return true;
}

export function GetEmailWebhook200ResponseDataFromJSON(json: any): GetEmailWebhook200ResponseData {
    return GetEmailWebhook200ResponseDataFromJSONTyped(json, false);
}

export function GetEmailWebhook200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailWebhook200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'webhook': GetEmailWebhook200ResponseDataWebhookFromJSON(json['webhook']),
    };
}

export function GetEmailWebhook200ResponseDataToJSON(json: any): GetEmailWebhook200ResponseData {
    return GetEmailWebhook200ResponseDataToJSONTyped(json, false);
}

export function GetEmailWebhook200ResponseDataToJSONTyped(value?: GetEmailWebhook200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhook': GetEmailWebhook200ResponseDataWebhookToJSON(value['webhook']),
    };
}

