/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEmailWebhook200ResponseDataWebhook
 */
export interface GetEmailWebhook200ResponseDataWebhook {
    /**
     * 
     */
    url: string;
    /**
     * 
     */
    event: GetEmailWebhook200ResponseDataWebhookEventEnum;
}


/**
 * @export
 */
export const GetEmailWebhook200ResponseDataWebhookEventEnum = {
    EmailReceived: 'email.received',
} as const;
export type GetEmailWebhook200ResponseDataWebhookEventEnum = typeof GetEmailWebhook200ResponseDataWebhookEventEnum[keyof typeof GetEmailWebhook200ResponseDataWebhookEventEnum];


/**
 * Check if a given object implements the GetEmailWebhook200ResponseDataWebhook interface.
 */
export function instanceOfGetEmailWebhook200ResponseDataWebhook(value: object): value is GetEmailWebhook200ResponseDataWebhook {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (value['event'] !== 'email.received') return false;
    
    return true;
}

export function GetEmailWebhook200ResponseDataWebhookFromJSON(json: any): GetEmailWebhook200ResponseDataWebhook {
    return GetEmailWebhook200ResponseDataWebhookFromJSONTyped(json, false);
}

export function GetEmailWebhook200ResponseDataWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailWebhook200ResponseDataWebhook {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'event': json['event'],
    };
}

export function GetEmailWebhook200ResponseDataWebhookToJSON(json: any): GetEmailWebhook200ResponseDataWebhook {
    return GetEmailWebhook200ResponseDataWebhookToJSONTyped(json, false);
}

export function GetEmailWebhook200ResponseDataWebhookToJSONTyped(value?: GetEmailWebhook200ResponseDataWebhook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'event': value['event'],
    };
}

