/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailWebhook200ResponseData } from './GetEmailWebhook200ResponseData';
import {
    GetEmailWebhook200ResponseDataFromJSON,
    GetEmailWebhook200ResponseDataFromJSONTyped,
    GetEmailWebhook200ResponseDataToJSON,
    GetEmailWebhook200ResponseDataToJSONTyped,
} from './GetEmailWebhook200ResponseData';

/**
 * 
 * @export
 * @interface GetEmailWebhook200Response
 */
export interface GetEmailWebhook200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: GetEmailWebhook200ResponseData;
}

/**
 * Check if a given object implements the GetEmailWebhook200Response interface.
 */
export function instanceOfGetEmailWebhook200Response(value: object): value is GetEmailWebhook200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmailWebhook200ResponseFromJSON(json: any): GetEmailWebhook200Response {
    return GetEmailWebhook200ResponseFromJSONTyped(json, false);
}

export function GetEmailWebhook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailWebhook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': GetEmailWebhook200ResponseDataFromJSON(json['data']),
    };
}

export function GetEmailWebhook200ResponseToJSON(json: any): GetEmailWebhook200Response {
    return GetEmailWebhook200ResponseToJSONTyped(json, false);
}

export function GetEmailWebhook200ResponseToJSONTyped(value?: GetEmailWebhook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetEmailWebhook200ResponseDataToJSON(value['data']),
    };
}

