/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailDetail } from './EmailDetail';
import {
    EmailDetailFromJSON,
    EmailDetailFromJSONTyped,
    EmailDetailToJSON,
    EmailDetailToJSONTyped,
} from './EmailDetail';

/**
 * 
 * @export
 * @interface GetEmail200ResponseData
 */
export interface GetEmail200ResponseData {
    /**
     * 
     */
    email: EmailDetail;
}

/**
 * Check if a given object implements the GetEmail200ResponseData interface.
 */
export function instanceOfGetEmail200ResponseData(value: object): value is GetEmail200ResponseData {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function GetEmail200ResponseDataFromJSON(json: any): GetEmail200ResponseData {
    return GetEmail200ResponseDataFromJSONTyped(json, false);
}

export function GetEmail200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmail200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'email': EmailDetailFromJSON(json['email']),
    };
}

export function GetEmail200ResponseDataToJSON(json: any): GetEmail200ResponseData {
    return GetEmail200ResponseDataToJSONTyped(json, false);
}

export function GetEmail200ResponseDataToJSONTyped(value?: GetEmail200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': EmailDetailToJSON(value['email']),
    };
}

