/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailSubscription200ResponseData } from './GetEmailSubscription200ResponseData';
import {
    GetEmailSubscription200ResponseDataFromJSON,
    GetEmailSubscription200ResponseDataFromJSONTyped,
    GetEmailSubscription200ResponseDataToJSON,
    GetEmailSubscription200ResponseDataToJSONTyped,
} from './GetEmailSubscription200ResponseData';

/**
 * 
 * @export
 * @interface GetEmailSubscription200Response
 */
export interface GetEmailSubscription200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: GetEmailSubscription200ResponseData;
}

/**
 * Check if a given object implements the GetEmailSubscription200Response interface.
 */
export function instanceOfGetEmailSubscription200Response(value: object): value is GetEmailSubscription200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmailSubscription200ResponseFromJSON(json: any): GetEmailSubscription200Response {
    return GetEmailSubscription200ResponseFromJSONTyped(json, false);
}

export function GetEmailSubscription200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailSubscription200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': GetEmailSubscription200ResponseDataFromJSON(json['data']),
    };
}

export function GetEmailSubscription200ResponseToJSON(json: any): GetEmailSubscription200Response {
    return GetEmailSubscription200ResponseToJSONTyped(json, false);
}

export function GetEmailSubscription200ResponseToJSONTyped(value?: GetEmailSubscription200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetEmailSubscription200ResponseDataToJSON(value['data']),
    };
}

