/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmail200ResponseData } from './GetEmail200ResponseData';
import {
    GetEmail200ResponseDataFromJSON,
    GetEmail200ResponseDataFromJSONTyped,
    GetEmail200ResponseDataToJSON,
    GetEmail200ResponseDataToJSONTyped,
} from './GetEmail200ResponseData';

/**
 * 
 * @export
 * @interface GetEmail200Response
 */
export interface GetEmail200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: GetEmail200ResponseData;
}

/**
 * Check if a given object implements the GetEmail200Response interface.
 */
export function instanceOfGetEmail200Response(value: object): value is GetEmail200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmail200ResponseFromJSON(json: any): GetEmail200Response {
    return GetEmail200ResponseFromJSONTyped(json, false);
}

export function GetEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmail200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': GetEmail200ResponseDataFromJSON(json['data']),
    };
}

export function GetEmail200ResponseToJSON(json: any): GetEmail200Response {
    return GetEmail200ResponseToJSONTyped(json, false);
}

export function GetEmail200ResponseToJSONTyped(value?: GetEmail200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetEmail200ResponseDataToJSON(value['data']),
    };
}

