/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailOriginalDownloadUrl200ResponseData } from './GetEmailOriginalDownloadUrl200ResponseData';
import {
    GetEmailOriginalDownloadUrl200ResponseDataFromJSON,
    GetEmailOriginalDownloadUrl200ResponseDataFromJSONTyped,
    GetEmailOriginalDownloadUrl200ResponseDataToJSON,
    GetEmailOriginalDownloadUrl200ResponseDataToJSONTyped,
} from './GetEmailOriginalDownloadUrl200ResponseData';

/**
 * 
 * @export
 * @interface GetEmailOriginalDownloadUrl200Response
 */
export interface GetEmailOriginalDownloadUrl200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: GetEmailOriginalDownloadUrl200ResponseData;
}

/**
 * Check if a given object implements the GetEmailOriginalDownloadUrl200Response interface.
 */
export function instanceOfGetEmailOriginalDownloadUrl200Response(value: object): value is GetEmailOriginalDownloadUrl200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmailOriginalDownloadUrl200ResponseFromJSON(json: any): GetEmailOriginalDownloadUrl200Response {
    return GetEmailOriginalDownloadUrl200ResponseFromJSONTyped(json, false);
}

export function GetEmailOriginalDownloadUrl200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailOriginalDownloadUrl200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': GetEmailOriginalDownloadUrl200ResponseDataFromJSON(json['data']),
    };
}

export function GetEmailOriginalDownloadUrl200ResponseToJSON(json: any): GetEmailOriginalDownloadUrl200Response {
    return GetEmailOriginalDownloadUrl200ResponseToJSONTyped(json, false);
}

export function GetEmailOriginalDownloadUrl200ResponseToJSONTyped(value?: GetEmailOriginalDownloadUrl200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetEmailOriginalDownloadUrl200ResponseDataToJSON(value['data']),
    };
}

