/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailDownload } from './EmailDownload';
import {
    EmailDownloadFromJSON,
    EmailDownloadFromJSONTyped,
    EmailDownloadToJSON,
    EmailDownloadToJSONTyped,
} from './EmailDownload';

/**
 * 
 * @export
 * @interface GetEmailOriginalDownloadUrl200ResponseData
 */
export interface GetEmailOriginalDownloadUrl200ResponseData {
    /**
     * 
     */
    download: EmailDownload;
}

/**
 * Check if a given object implements the GetEmailOriginalDownloadUrl200ResponseData interface.
 */
export function instanceOfGetEmailOriginalDownloadUrl200ResponseData(value: object): value is GetEmailOriginalDownloadUrl200ResponseData {
    if (!('download' in value) || value['download'] === undefined) return false;
    return true;
}

export function GetEmailOriginalDownloadUrl200ResponseDataFromJSON(json: any): GetEmailOriginalDownloadUrl200ResponseData {
    return GetEmailOriginalDownloadUrl200ResponseDataFromJSONTyped(json, false);
}

export function GetEmailOriginalDownloadUrl200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailOriginalDownloadUrl200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'download': EmailDownloadFromJSON(json['download']),
    };
}

export function GetEmailOriginalDownloadUrl200ResponseDataToJSON(json: any): GetEmailOriginalDownloadUrl200ResponseData {
    return GetEmailOriginalDownloadUrl200ResponseDataToJSONTyped(json, false);
}

export function GetEmailOriginalDownloadUrl200ResponseDataToJSONTyped(value?: GetEmailOriginalDownloadUrl200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'download': EmailDownloadToJSON(value['download']),
    };
}

