/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetRevdokuStatus200ResponseData } from './GetRevdokuStatus200ResponseData';
import {
    GetRevdokuStatus200ResponseDataFromJSON,
    GetRevdokuStatus200ResponseDataFromJSONTyped,
    GetRevdokuStatus200ResponseDataToJSON,
    GetRevdokuStatus200ResponseDataToJSONTyped,
} from './GetRevdokuStatus200ResponseData';

/**
 * 
 * @export
 * @interface GetRevdokuStatus200Response
 */
export interface GetRevdokuStatus200Response {
    /**
     * 
     */
    data: GetRevdokuStatus200ResponseData;
    /**
     * 
     */
    success: boolean;
}

/**
 * Check if a given object implements the GetRevdokuStatus200Response interface.
 */
export function instanceOfGetRevdokuStatus200Response(value: object): value is GetRevdokuStatus200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetRevdokuStatus200ResponseFromJSON(json: any): GetRevdokuStatus200Response {
    return GetRevdokuStatus200ResponseFromJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRevdokuStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetRevdokuStatus200ResponseDataFromJSON(json['data']),
        'success': json['success'],
    };
}

export function GetRevdokuStatus200ResponseToJSON(json: any): GetRevdokuStatus200Response {
    return GetRevdokuStatus200ResponseToJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseToJSONTyped(value?: GetRevdokuStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetRevdokuStatus200ResponseDataToJSON(value['data']),
        'success': value['success'],
    };
}

