/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRevdokuStatus200ResponseDataConnectionRenewal
 */
export interface GetRevdokuStatus200ResponseDataConnectionRenewal {
    /**
     * 
     */
    recommended?: boolean;
    /**
     * 
     */
    nextAction?: string;
    /**
     * 
     */
    browserUrl?: string;
}

/**
 * Check if a given object implements the GetRevdokuStatus200ResponseDataConnectionRenewal interface.
 */
export function instanceOfGetRevdokuStatus200ResponseDataConnectionRenewal(value: object): value is GetRevdokuStatus200ResponseDataConnectionRenewal {
    return true;
}

export function GetRevdokuStatus200ResponseDataConnectionRenewalFromJSON(json: any): GetRevdokuStatus200ResponseDataConnectionRenewal {
    return GetRevdokuStatus200ResponseDataConnectionRenewalFromJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseDataConnectionRenewalFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRevdokuStatus200ResponseDataConnectionRenewal {
    if (json == null) {
        return json;
    }
    return {
        
        'recommended': json['recommended'] == null ? undefined : json['recommended'],
        'nextAction': json['next_action'] == null ? undefined : json['next_action'],
        'browserUrl': json['browser_url'] == null ? undefined : json['browser_url'],
    };
}

export function GetRevdokuStatus200ResponseDataConnectionRenewalToJSON(json: any): GetRevdokuStatus200ResponseDataConnectionRenewal {
    return GetRevdokuStatus200ResponseDataConnectionRenewalToJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseDataConnectionRenewalToJSONTyped(value?: GetRevdokuStatus200ResponseDataConnectionRenewal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recommended': value['recommended'],
        'next_action': value['nextAction'],
        'browser_url': value['browserUrl'],
    };
}

