/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRevdokuStatus200ResponseNot
 */
export interface GetRevdokuStatus200ResponseNot {
}

/**
 * Check if a given object implements the GetRevdokuStatus200ResponseNot interface.
 */
export function instanceOfGetRevdokuStatus200ResponseNot(value: object): value is GetRevdokuStatus200ResponseNot {
    return true;
}

export function GetRevdokuStatus200ResponseNotFromJSON(json: any): GetRevdokuStatus200ResponseNot {
    return GetRevdokuStatus200ResponseNotFromJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseNotFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRevdokuStatus200ResponseNot {
    return json;
}

export function GetRevdokuStatus200ResponseNotToJSON(json: any): GetRevdokuStatus200ResponseNot {
    return GetRevdokuStatus200ResponseNotToJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseNotToJSONTyped(value?: GetRevdokuStatus200ResponseNot | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

