/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRevdokuStatus200ResponseDataFeatures
 */
export interface GetRevdokuStatus200ResponseDataFeatures {
    [key: string]: any | any;
    /**
     * 
     */
    emailDomains?: boolean;
}

/**
 * Check if a given object implements the GetRevdokuStatus200ResponseDataFeatures interface.
 */
export function instanceOfGetRevdokuStatus200ResponseDataFeatures(value: object): value is GetRevdokuStatus200ResponseDataFeatures {
    return true;
}

export function GetRevdokuStatus200ResponseDataFeaturesFromJSON(json: any): GetRevdokuStatus200ResponseDataFeatures {
    return GetRevdokuStatus200ResponseDataFeaturesFromJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseDataFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRevdokuStatus200ResponseDataFeatures {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'emailDomains': json['email_domains'] == null ? undefined : json['email_domains'],
    };
}

export function GetRevdokuStatus200ResponseDataFeaturesToJSON(json: any): GetRevdokuStatus200ResponseDataFeatures {
    return GetRevdokuStatus200ResponseDataFeaturesToJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseDataFeaturesToJSONTyped(value?: GetRevdokuStatus200ResponseDataFeatures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'email_domains': value['emailDomains'],
    };
}

