/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetRevdokuStatus200ResponseDataFeatures } from './GetRevdokuStatus200ResponseDataFeatures';
import {
    GetRevdokuStatus200ResponseDataFeaturesFromJSON,
    GetRevdokuStatus200ResponseDataFeaturesFromJSONTyped,
    GetRevdokuStatus200ResponseDataFeaturesToJSON,
    GetRevdokuStatus200ResponseDataFeaturesToJSONTyped,
} from './GetRevdokuStatus200ResponseDataFeatures';
import type { GetRevdokuStatus200ResponseDataConnection } from './GetRevdokuStatus200ResponseDataConnection';
import {
    GetRevdokuStatus200ResponseDataConnectionFromJSON,
    GetRevdokuStatus200ResponseDataConnectionFromJSONTyped,
    GetRevdokuStatus200ResponseDataConnectionToJSON,
    GetRevdokuStatus200ResponseDataConnectionToJSONTyped,
} from './GetRevdokuStatus200ResponseDataConnection';
import type { AccountIdentity } from './AccountIdentity';
import {
    AccountIdentityFromJSON,
    AccountIdentityFromJSONTyped,
    AccountIdentityToJSON,
    AccountIdentityToJSONTyped,
} from './AccountIdentity';

/**
 * 
 * @export
 * @interface GetRevdokuStatus200ResponseData
 */
export interface GetRevdokuStatus200ResponseData {
    /**
     * 
     */
    account?: AccountIdentity;
    /**
     * 
     */
    defaultAccountId?: string | null;
    /**
     * 
     */
    accounts?: Array<AccountIdentity>;
    /**
     * 
     */
    features?: GetRevdokuStatus200ResponseDataFeatures;
    /**
     * 
     */
    connected?: boolean;
    /**
     * 
     */
    serverVersion?: string;
    /**
     * 
     */
    clientVersion?: string;
    /**
     * 
     */
    connection?: GetRevdokuStatus200ResponseDataConnection;
    /**
     * 
     */
    limits?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the GetRevdokuStatus200ResponseData interface.
 */
export function instanceOfGetRevdokuStatus200ResponseData(value: object): value is GetRevdokuStatus200ResponseData {
    return true;
}

export function GetRevdokuStatus200ResponseDataFromJSON(json: any): GetRevdokuStatus200ResponseData {
    return GetRevdokuStatus200ResponseDataFromJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRevdokuStatus200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : AccountIdentityFromJSON(json['account']),
        'defaultAccountId': json['default_account_id'] === undefined ? undefined : json['default_account_id'] === null ? null : json['default_account_id'],
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(AccountIdentityFromJSON)),
        'features': json['features'] == null ? undefined : GetRevdokuStatus200ResponseDataFeaturesFromJSON(json['features']),
        'connected': json['connected'] == null ? undefined : json['connected'],
        'serverVersion': json['server_version'] == null ? undefined : json['server_version'],
        'clientVersion': json['client_version'] == null ? undefined : json['client_version'],
        'connection': json['connection'] == null ? undefined : GetRevdokuStatus200ResponseDataConnectionFromJSON(json['connection']),
        'limits': json['limits'] === undefined ? undefined : json['limits'] === null ? null : json['limits'],
    };
}

export function GetRevdokuStatus200ResponseDataToJSON(json: any): GetRevdokuStatus200ResponseData {
    return GetRevdokuStatus200ResponseDataToJSONTyped(json, false);
}

export function GetRevdokuStatus200ResponseDataToJSONTyped(value?: GetRevdokuStatus200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': AccountIdentityToJSON(value['account']),
        'default_account_id': value['defaultAccountId'],
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(AccountIdentityToJSON)),
        'features': GetRevdokuStatus200ResponseDataFeaturesToJSON(value['features']),
        'connected': value['connected'],
        'server_version': value['serverVersion'],
        'client_version': value['clientVersion'],
        'connection': GetRevdokuStatus200ResponseDataConnectionToJSON(value['connection']),
        'limits': value['limits'],
    };
}

