/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListBucketFiles200ResponseData } from './ListBucketFiles200ResponseData';
import {
    ListBucketFiles200ResponseDataFromJSON,
    ListBucketFiles200ResponseDataFromJSONTyped,
    ListBucketFiles200ResponseDataToJSON,
    ListBucketFiles200ResponseDataToJSONTyped,
} from './ListBucketFiles200ResponseData';

/**
 * 
 * @export
 * @interface ListBucketFiles200Response
 */
export interface ListBucketFiles200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: ListBucketFiles200ResponseData;
}

/**
 * Check if a given object implements the ListBucketFiles200Response interface.
 */
export function instanceOfListBucketFiles200Response(value: object): value is ListBucketFiles200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListBucketFiles200ResponseFromJSON(json: any): ListBucketFiles200Response {
    return ListBucketFiles200ResponseFromJSONTyped(json, false);
}

export function ListBucketFiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBucketFiles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ListBucketFiles200ResponseDataFromJSON(json['data']),
    };
}

export function ListBucketFiles200ResponseToJSON(json: any): ListBucketFiles200Response {
    return ListBucketFiles200ResponseToJSONTyped(json, false);
}

export function ListBucketFiles200ResponseToJSONTyped(value?: ListBucketFiles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListBucketFiles200ResponseDataToJSON(value['data']),
    };
}

