/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListMailboxFiles200ResponseData } from './ListMailboxFiles200ResponseData';
import {
    ListMailboxFiles200ResponseDataFromJSON,
    ListMailboxFiles200ResponseDataFromJSONTyped,
    ListMailboxFiles200ResponseDataToJSON,
    ListMailboxFiles200ResponseDataToJSONTyped,
} from './ListMailboxFiles200ResponseData';

/**
 * 
 * @export
 * @interface ListMailboxFiles200Response
 */
export interface ListMailboxFiles200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: ListMailboxFiles200ResponseData;
}

/**
 * Check if a given object implements the ListMailboxFiles200Response interface.
 */
export function instanceOfListMailboxFiles200Response(value: object): value is ListMailboxFiles200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListMailboxFiles200ResponseFromJSON(json: any): ListMailboxFiles200Response {
    return ListMailboxFiles200ResponseFromJSONTyped(json, false);
}

export function ListMailboxFiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMailboxFiles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ListMailboxFiles200ResponseDataFromJSON(json['data']),
    };
}

export function ListMailboxFiles200ResponseToJSON(json: any): ListMailboxFiles200Response {
    return ListMailboxFiles200ResponseToJSONTyped(json, false);
}

export function ListMailboxFiles200ResponseToJSONTyped(value?: ListMailboxFiles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListMailboxFiles200ResponseDataToJSON(value['data']),
    };
}

