/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilePagination } from './FilePagination';
import {
    FilePaginationFromJSON,
    FilePaginationFromJSONTyped,
    FilePaginationToJSON,
    FilePaginationToJSONTyped,
} from './FilePagination';

/**
 * 
 * @export
 * @interface ListMailboxFiles200ResponseData
 */
export interface ListMailboxFiles200ResponseData {
    /**
     * 
     */
    files: Array<object>;
    /**
     * 
     */
    pagination: FilePagination;
}

/**
 * Check if a given object implements the ListMailboxFiles200ResponseData interface.
 */
export function instanceOfListMailboxFiles200ResponseData(value: object): value is ListMailboxFiles200ResponseData {
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListMailboxFiles200ResponseDataFromJSON(json: any): ListMailboxFiles200ResponseData {
    return ListMailboxFiles200ResponseDataFromJSONTyped(json, false);
}

export function ListMailboxFiles200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMailboxFiles200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'files': json['files'],
        'pagination': FilePaginationFromJSON(json['pagination']),
    };
}

export function ListMailboxFiles200ResponseDataToJSON(json: any): ListMailboxFiles200ResponseData {
    return ListMailboxFiles200ResponseDataToJSONTyped(json, false);
}

export function ListMailboxFiles200ResponseDataToJSONTyped(value?: ListMailboxFiles200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'files': value['files'],
        'pagination': FilePaginationToJSON(value['pagination']),
    };
}

