/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailPagination } from './EmailPagination';
import {
    EmailPaginationFromJSON,
    EmailPaginationFromJSONTyped,
    EmailPaginationToJSON,
    EmailPaginationToJSONTyped,
} from './EmailPagination';
import type { EmailSummary } from './EmailSummary';
import {
    EmailSummaryFromJSON,
    EmailSummaryFromJSONTyped,
    EmailSummaryToJSON,
    EmailSummaryToJSONTyped,
} from './EmailSummary';

/**
 * 
 * @export
 * @interface ListEmails200ResponseData
 */
export interface ListEmails200ResponseData {
    /**
     * 
     */
    emails: Array<EmailSummary>;
    /**
     * 
     */
    pagination: EmailPagination;
}

/**
 * Check if a given object implements the ListEmails200ResponseData interface.
 */
export function instanceOfListEmails200ResponseData(value: object): value is ListEmails200ResponseData {
    if (!('emails' in value) || value['emails'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListEmails200ResponseDataFromJSON(json: any): ListEmails200ResponseData {
    return ListEmails200ResponseDataFromJSONTyped(json, false);
}

export function ListEmails200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEmails200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'emails': ((json['emails'] as Array<any>).map(EmailSummaryFromJSON)),
        'pagination': EmailPaginationFromJSON(json['pagination']),
    };
}

export function ListEmails200ResponseDataToJSON(json: any): ListEmails200ResponseData {
    return ListEmails200ResponseDataToJSONTyped(json, false);
}

export function ListEmails200ResponseDataToJSONTyped(value?: ListEmails200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emails': ((value['emails'] as Array<any>).map(EmailSummaryToJSON)),
        'pagination': EmailPaginationToJSON(value['pagination']),
    };
}

