/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBuckets200ResponseDataBucketsInner
 */
export interface ListBuckets200ResponseDataBucketsInner {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    title: string;
}

/**
 * Check if a given object implements the ListBuckets200ResponseDataBucketsInner interface.
 */
export function instanceOfListBuckets200ResponseDataBucketsInner(value: object): value is ListBuckets200ResponseDataBucketsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ListBuckets200ResponseDataBucketsInnerFromJSON(json: any): ListBuckets200ResponseDataBucketsInner {
    return ListBuckets200ResponseDataBucketsInnerFromJSONTyped(json, false);
}

export function ListBuckets200ResponseDataBucketsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBuckets200ResponseDataBucketsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
    };
}

export function ListBuckets200ResponseDataBucketsInnerToJSON(json: any): ListBuckets200ResponseDataBucketsInner {
    return ListBuckets200ResponseDataBucketsInnerToJSONTyped(json, false);
}

export function ListBuckets200ResponseDataBucketsInnerToJSONTyped(value?: ListBuckets200ResponseDataBucketsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

