/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEmails200ResponseData } from './ListEmails200ResponseData';
import {
    ListEmails200ResponseDataFromJSON,
    ListEmails200ResponseDataFromJSONTyped,
    ListEmails200ResponseDataToJSON,
    ListEmails200ResponseDataToJSONTyped,
} from './ListEmails200ResponseData';

/**
 * 
 * @export
 * @interface ListEmails200Response
 */
export interface ListEmails200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: ListEmails200ResponseData;
}

/**
 * Check if a given object implements the ListEmails200Response interface.
 */
export function instanceOfListEmails200Response(value: object): value is ListEmails200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListEmails200ResponseFromJSON(json: any): ListEmails200Response {
    return ListEmails200ResponseFromJSONTyped(json, false);
}

export function ListEmails200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEmails200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ListEmails200ResponseDataFromJSON(json['data']),
    };
}

export function ListEmails200ResponseToJSON(json: any): ListEmails200Response {
    return ListEmails200ResponseToJSONTyped(json, false);
}

export function ListEmails200ResponseToJSONTyped(value?: ListEmails200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListEmails200ResponseDataToJSON(value['data']),
    };
}

