/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilePagination } from './FilePagination';
import {
    FilePaginationFromJSON,
    FilePaginationFromJSONTyped,
    FilePaginationToJSON,
    FilePaginationToJSONTyped,
} from './FilePagination';

/**
 * 
 * @export
 * @interface ListBucketFiles200ResponseData
 */
export interface ListBucketFiles200ResponseData {
    /**
     * 
     */
    files: Array<object>;
    /**
     * 
     */
    pagination: FilePagination;
}

/**
 * Check if a given object implements the ListBucketFiles200ResponseData interface.
 */
export function instanceOfListBucketFiles200ResponseData(value: object): value is ListBucketFiles200ResponseData {
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListBucketFiles200ResponseDataFromJSON(json: any): ListBucketFiles200ResponseData {
    return ListBucketFiles200ResponseDataFromJSONTyped(json, false);
}

export function ListBucketFiles200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBucketFiles200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'files': json['files'],
        'pagination': FilePaginationFromJSON(json['pagination']),
    };
}

export function ListBucketFiles200ResponseDataToJSON(json: any): ListBucketFiles200ResponseData {
    return ListBucketFiles200ResponseDataToJSONTyped(json, false);
}

export function ListBucketFiles200ResponseDataToJSONTyped(value?: ListBucketFiles200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'files': value['files'],
        'pagination': FilePaginationToJSON(value['pagination']),
    };
}

