/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountPagination } from './AccountPagination';
import {
    AccountPaginationFromJSON,
    AccountPaginationFromJSONTyped,
    AccountPaginationToJSON,
    AccountPaginationToJSONTyped,
} from './AccountPagination';
import type { AccountIdentity } from './AccountIdentity';
import {
    AccountIdentityFromJSON,
    AccountIdentityFromJSONTyped,
    AccountIdentityToJSON,
    AccountIdentityToJSONTyped,
} from './AccountIdentity';

/**
 * 
 * @export
 * @interface ListAccounts200ResponseData
 */
export interface ListAccounts200ResponseData {
    /**
     * 
     */
    accounts: Array<AccountIdentity>;
    /**
     * 
     */
    defaultAccountId: string | null;
    /**
     * 
     */
    pagination: AccountPagination;
}

/**
 * Check if a given object implements the ListAccounts200ResponseData interface.
 */
export function instanceOfListAccounts200ResponseData(value: object): value is ListAccounts200ResponseData {
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    if ((!('defaultAccountId' in (value as Record<string, any>)) && !('default_account_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['defaultAccountId'] === undefined && (value as Record<string, any>)['default_account_id'] === undefined)) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListAccounts200ResponseDataFromJSON(json: any): ListAccounts200ResponseData {
    return ListAccounts200ResponseDataFromJSONTyped(json, false);
}

export function ListAccounts200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAccounts200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': ((json['accounts'] as Array<any>).map(AccountIdentityFromJSON)),
        'defaultAccountId': json['default_account_id'],
        'pagination': AccountPaginationFromJSON(json['pagination']),
    };
}

export function ListAccounts200ResponseDataToJSON(json: any): ListAccounts200ResponseData {
    return ListAccounts200ResponseDataToJSONTyped(json, false);
}

export function ListAccounts200ResponseDataToJSONTyped(value?: ListAccounts200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': ((value['accounts'] as Array<any>).map(AccountIdentityToJSON)),
        'default_account_id': value['defaultAccountId'],
        'pagination': AccountPaginationToJSON(value['pagination']),
    };
}

