/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountIdentity } from './AccountIdentity';
import {
    AccountIdentityFromJSON,
    AccountIdentityFromJSONTyped,
    AccountIdentityToJSON,
    AccountIdentityToJSONTyped,
} from './AccountIdentity';

/**
 * 
 * @export
 * @interface ListAccounts200ResponseData
 */
export interface ListAccounts200ResponseData {
    /**
     * 
     */
    accounts?: Array<AccountIdentity>;
    /**
     * 
     */
    defaultAccountId?: string | null;
    /**
     * 
     */
    pagination?: object;
}

/**
 * Check if a given object implements the ListAccounts200ResponseData interface.
 */
export function instanceOfListAccounts200ResponseData(value: object): value is ListAccounts200ResponseData {
    return true;
}

export function ListAccounts200ResponseDataFromJSON(json: any): ListAccounts200ResponseData {
    return ListAccounts200ResponseDataFromJSONTyped(json, false);
}

export function ListAccounts200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAccounts200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(AccountIdentityFromJSON)),
        'defaultAccountId': json['default_account_id'] === undefined ? undefined : json['default_account_id'] === null ? null : json['default_account_id'],
        'pagination': json['pagination'] == null ? undefined : json['pagination'],
    };
}

export function ListAccounts200ResponseDataToJSON(json: any): ListAccounts200ResponseData {
    return ListAccounts200ResponseDataToJSONTyped(json, false);
}

export function ListAccounts200ResponseDataToJSONTyped(value?: ListAccounts200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(AccountIdentityToJSON)),
        'default_account_id': value['defaultAccountId'],
        'pagination': value['pagination'],
    };
}

