/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mailbox } from './Mailbox';
import {
    MailboxFromJSON,
    MailboxFromJSONTyped,
    MailboxToJSON,
    MailboxToJSONTyped,
} from './Mailbox';

/**
 * 
 * @export
 * @interface ListMailboxes200ResponseData
 */
export interface ListMailboxes200ResponseData {
    /**
     * 
     */
    mailboxes: Array<Mailbox>;
}

/**
 * Check if a given object implements the ListMailboxes200ResponseData interface.
 */
export function instanceOfListMailboxes200ResponseData(value: object): value is ListMailboxes200ResponseData {
    if (!('mailboxes' in value) || value['mailboxes'] === undefined) return false;
    return true;
}

export function ListMailboxes200ResponseDataFromJSON(json: any): ListMailboxes200ResponseData {
    return ListMailboxes200ResponseDataFromJSONTyped(json, false);
}

export function ListMailboxes200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMailboxes200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'mailboxes': ((json['mailboxes'] as Array<any>).map(MailboxFromJSON)),
    };
}

export function ListMailboxes200ResponseDataToJSON(json: any): ListMailboxes200ResponseData {
    return ListMailboxes200ResponseDataToJSONTyped(json, false);
}

export function ListMailboxes200ResponseDataToJSONTyped(value?: ListMailboxes200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mailboxes': ((value['mailboxes'] as Array<any>).map(MailboxToJSON)),
    };
}

