/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListAccounts200ResponseData } from './ListAccounts200ResponseData';
import {
    ListAccounts200ResponseDataFromJSON,
    ListAccounts200ResponseDataFromJSONTyped,
    ListAccounts200ResponseDataToJSON,
    ListAccounts200ResponseDataToJSONTyped,
} from './ListAccounts200ResponseData';

/**
 * 
 * @export
 * @interface ListAccounts200Response
 */
export interface ListAccounts200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: ListAccounts200ResponseData;
}

/**
 * Check if a given object implements the ListAccounts200Response interface.
 */
export function instanceOfListAccounts200Response(value: object): value is ListAccounts200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListAccounts200ResponseFromJSON(json: any): ListAccounts200Response {
    return ListAccounts200ResponseFromJSONTyped(json, false);
}

export function ListAccounts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAccounts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ListAccounts200ResponseDataFromJSON(json['data']),
    };
}

export function ListAccounts200ResponseToJSON(json: any): ListAccounts200Response {
    return ListAccounts200ResponseToJSONTyped(json, false);
}

export function ListAccounts200ResponseToJSONTyped(value?: ListAccounts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListAccounts200ResponseDataToJSON(value['data']),
    };
}

