/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListBuckets200ResponseDataBucketsInner } from './ListBuckets200ResponseDataBucketsInner';
import {
    ListBuckets200ResponseDataBucketsInnerFromJSON,
    ListBuckets200ResponseDataBucketsInnerFromJSONTyped,
    ListBuckets200ResponseDataBucketsInnerToJSON,
    ListBuckets200ResponseDataBucketsInnerToJSONTyped,
} from './ListBuckets200ResponseDataBucketsInner';

/**
 * 
 * @export
 * @interface ListBuckets200ResponseData
 */
export interface ListBuckets200ResponseData {
    /**
     * 
     */
    buckets: Array<ListBuckets200ResponseDataBucketsInner>;
}

/**
 * Check if a given object implements the ListBuckets200ResponseData interface.
 */
export function instanceOfListBuckets200ResponseData(value: object): value is ListBuckets200ResponseData {
    if (!('buckets' in value) || value['buckets'] === undefined) return false;
    return true;
}

export function ListBuckets200ResponseDataFromJSON(json: any): ListBuckets200ResponseData {
    return ListBuckets200ResponseDataFromJSONTyped(json, false);
}

export function ListBuckets200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBuckets200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'buckets': ((json['buckets'] as Array<any>).map(ListBuckets200ResponseDataBucketsInnerFromJSON)),
    };
}

export function ListBuckets200ResponseDataToJSON(json: any): ListBuckets200ResponseData {
    return ListBuckets200ResponseDataToJSONTyped(json, false);
}

export function ListBuckets200ResponseDataToJSONTyped(value?: ListBuckets200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buckets': ((value['buckets'] as Array<any>).map(ListBuckets200ResponseDataBucketsInnerToJSON)),
    };
}

