/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListBuckets200ResponseData } from './ListBuckets200ResponseData';
import {
    ListBuckets200ResponseDataFromJSON,
    ListBuckets200ResponseDataFromJSONTyped,
    ListBuckets200ResponseDataToJSON,
    ListBuckets200ResponseDataToJSONTyped,
} from './ListBuckets200ResponseData';

/**
 * 
 * @export
 * @interface ListBuckets200Response
 */
export interface ListBuckets200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: ListBuckets200ResponseData;
}

/**
 * Check if a given object implements the ListBuckets200Response interface.
 */
export function instanceOfListBuckets200Response(value: object): value is ListBuckets200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListBuckets200ResponseFromJSON(json: any): ListBuckets200Response {
    return ListBuckets200ResponseFromJSONTyped(json, false);
}

export function ListBuckets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBuckets200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ListBuckets200ResponseDataFromJSON(json['data']),
    };
}

export function ListBuckets200ResponseToJSON(json: any): ListBuckets200Response {
    return ListBuckets200ResponseToJSONTyped(json, false);
}

export function ListBuckets200ResponseToJSONTyped(value?: ListBuckets200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListBuckets200ResponseDataToJSON(value['data']),
    };
}

