/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListMailboxes200ResponseData } from './ListMailboxes200ResponseData';
import {
    ListMailboxes200ResponseDataFromJSON,
    ListMailboxes200ResponseDataFromJSONTyped,
    ListMailboxes200ResponseDataToJSON,
    ListMailboxes200ResponseDataToJSONTyped,
} from './ListMailboxes200ResponseData';

/**
 * 
 * @export
 * @interface ListMailboxes200Response
 */
export interface ListMailboxes200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: ListMailboxes200ResponseData;
}

/**
 * Check if a given object implements the ListMailboxes200Response interface.
 */
export function instanceOfListMailboxes200Response(value: object): value is ListMailboxes200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListMailboxes200ResponseFromJSON(json: any): ListMailboxes200Response {
    return ListMailboxes200ResponseFromJSONTyped(json, false);
}

export function ListMailboxes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMailboxes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ListMailboxes200ResponseDataFromJSON(json['data']),
    };
}

export function ListMailboxes200ResponseToJSON(json: any): ListMailboxes200Response {
    return ListMailboxes200ResponseToJSONTyped(json, false);
}

export function ListMailboxes200ResponseToJSONTyped(value?: ListMailboxes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListMailboxes200ResponseDataToJSON(value['data']),
    };
}

