/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxEmailAssignmentError } from './MailboxEmailAssignmentError';
import {
    MailboxEmailAssignmentErrorFromJSON,
    MailboxEmailAssignmentErrorFromJSONTyped,
    MailboxEmailAssignmentErrorToJSON,
    MailboxEmailAssignmentErrorToJSONTyped,
} from './MailboxEmailAssignmentError';

/**
 * No candidate address is disclosed. Keep using address until status is active; on pending poll the email endpoint.
 * @export
 * @interface MailboxEmailAssignment
 */
export interface MailboxEmailAssignment {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    status?: MailboxEmailAssignmentStatusEnum;
    /**
     * 
     */
    hostname?: string;
    /**
     * 
     */
    error?: MailboxEmailAssignmentError;
}


/**
 * @export
 */
export const MailboxEmailAssignmentStatusEnum = {
    Pending: 'pending',
    Active: 'active',
    Failed: 'failed',
} as const;
export type MailboxEmailAssignmentStatusEnum = typeof MailboxEmailAssignmentStatusEnum[keyof typeof MailboxEmailAssignmentStatusEnum];


/**
 * Check if a given object implements the MailboxEmailAssignment interface.
 */
export function instanceOfMailboxEmailAssignment(value: object): value is MailboxEmailAssignment {
    return true;
}

export function MailboxEmailAssignmentFromJSON(json: any): MailboxEmailAssignment {
    return MailboxEmailAssignmentFromJSONTyped(json, false);
}

export function MailboxEmailAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxEmailAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'error': json['error'] == null ? undefined : MailboxEmailAssignmentErrorFromJSON(json['error']),
    };
}

export function MailboxEmailAssignmentToJSON(json: any): MailboxEmailAssignment {
    return MailboxEmailAssignmentToJSONTyped(json, false);
}

export function MailboxEmailAssignmentToJSONTyped(value?: MailboxEmailAssignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'hostname': value['hostname'],
        'error': MailboxEmailAssignmentErrorToJSON(value['error']),
    };
}

