/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxEmailAvailableDomainsInner
 */
export interface MailboxEmailAvailableDomainsInner {
    /**
     * 
     */
    hostname?: string;
    /**
     * 
     */
    kind?: MailboxEmailAvailableDomainsInnerKindEnum;
}


/**
 * @export
 */
export const MailboxEmailAvailableDomainsInnerKindEnum = {
    Platform: 'platform',
    Custom: 'custom',
} as const;
export type MailboxEmailAvailableDomainsInnerKindEnum = typeof MailboxEmailAvailableDomainsInnerKindEnum[keyof typeof MailboxEmailAvailableDomainsInnerKindEnum];


/**
 * Check if a given object implements the MailboxEmailAvailableDomainsInner interface.
 */
export function instanceOfMailboxEmailAvailableDomainsInner(value: object): value is MailboxEmailAvailableDomainsInner {
    return true;
}

export function MailboxEmailAvailableDomainsInnerFromJSON(json: any): MailboxEmailAvailableDomainsInner {
    return MailboxEmailAvailableDomainsInnerFromJSONTyped(json, false);
}

export function MailboxEmailAvailableDomainsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxEmailAvailableDomainsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'kind': json['kind'] == null ? undefined : json['kind'],
    };
}

export function MailboxEmailAvailableDomainsInnerToJSON(json: any): MailboxEmailAvailableDomainsInner {
    return MailboxEmailAvailableDomainsInnerToJSONTyped(json, false);
}

export function MailboxEmailAvailableDomainsInnerToJSONTyped(value?: MailboxEmailAvailableDomainsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'kind': value['kind'],
    };
}

