/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxFileResponseData } from './MailboxFileResponseData';
import {
    MailboxFileResponseDataFromJSON,
    MailboxFileResponseDataFromJSONTyped,
    MailboxFileResponseDataToJSON,
    MailboxFileResponseDataToJSONTyped,
} from './MailboxFileResponseData';

/**
 * 
 * @export
 * @interface MailboxFileResponse
 */
export interface MailboxFileResponse {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: MailboxFileResponseData;
}

/**
 * Check if a given object implements the MailboxFileResponse interface.
 */
export function instanceOfMailboxFileResponse(value: object): value is MailboxFileResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MailboxFileResponseFromJSON(json: any): MailboxFileResponse {
    return MailboxFileResponseFromJSONTyped(json, false);
}

export function MailboxFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': MailboxFileResponseDataFromJSON(json['data']),
    };
}

export function MailboxFileResponseToJSON(json: any): MailboxFileResponse {
    return MailboxFileResponseToJSONTyped(json, false);
}

export function MailboxFileResponseToJSONTyped(value?: MailboxFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': MailboxFileResponseDataToJSON(value['data']),
    };
}

