/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { MailboxLockLockedBy } from './MailboxLockLockedBy';
import {
    MailboxLockLockedByFromJSON,
    MailboxLockLockedByFromJSONTyped,
    MailboxLockLockedByToJSON,
    MailboxLockLockedByToJSONTyped,
} from './MailboxLockLockedBy';
import type { MailboxLockLockedByApiKey } from './MailboxLockLockedByApiKey';
import {
    MailboxLockLockedByApiKeyFromJSON,
    MailboxLockLockedByApiKeyFromJSONTyped,
    MailboxLockLockedByApiKeyToJSON,
    MailboxLockLockedByApiKeyToJSONTyped,
} from './MailboxLockLockedByApiKey';

/**
 * 
 * @export
 * @interface MailboxLock
 */
export interface MailboxLock {
    [key: string]: any | any;
    /**
     * 
     */
    locked: boolean;
    /**
     * 
     */
    lockedUntil?: Date;
    /**
     * 
     */
    kind?: string;
    /**
     * 
     */
    mailboxUploadSessionId?: string;
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    progress?: { [key: string]: any; };
    /**
     * 
     */
    lockedBy?: MailboxLockLockedBy;
    /**
     * 
     */
    lockedByApiKey?: MailboxLockLockedByApiKey;
}

/**
 * Check if a given object implements the MailboxLock interface.
 */
export function instanceOfMailboxLock(value: object): value is MailboxLock {
    if (!('locked' in value) || value['locked'] === undefined) return false;
    return true;
}

export function MailboxLockFromJSON(json: any): MailboxLock {
    return MailboxLockFromJSONTyped(json, false);
}

export function MailboxLockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxLock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'locked': json['locked'],
        'lockedUntil': json['locked_until'] == null ? undefined : (parseDateTime(json['locked_until'])),
        'kind': json['kind'] == null ? undefined : json['kind'],
        'mailboxUploadSessionId': json['mailbox_upload_session_id'] == null ? undefined : json['mailbox_upload_session_id'],
        'message': json['message'] == null ? undefined : json['message'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'lockedBy': json['locked_by'] == null ? undefined : MailboxLockLockedByFromJSON(json['locked_by']),
        'lockedByApiKey': json['locked_by_api_key'] == null ? undefined : MailboxLockLockedByApiKeyFromJSON(json['locked_by_api_key']),
    };
}

export function MailboxLockToJSON(json: any): MailboxLock {
    return MailboxLockToJSONTyped(json, false);
}

export function MailboxLockToJSONTyped(value?: MailboxLock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'locked': value['locked'],
        'locked_until': value['lockedUntil'] == null ? value['lockedUntil'] : serializeDateTime(value['lockedUntil']),
        'kind': value['kind'],
        'mailbox_upload_session_id': value['mailboxUploadSessionId'],
        'message': value['message'],
        'progress': value['progress'],
        'locked_by': MailboxLockLockedByToJSON(value['lockedBy']),
        'locked_by_api_key': MailboxLockLockedByApiKeyToJSON(value['lockedByApiKey']),
    };
}

