/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxEmailActivity
 */
export interface MailboxEmailActivity {
    /**
     * 
     */
    receivedCount?: number;
    /**
     * 
     */
    lastReceivedAt?: Date | null;
    /**
     * Latest message folder with trailing slash; null before receipt. May become stale after manual file moves/deletion.
     */
    lastReceivedPath?: string | null;
}

/**
 * Check if a given object implements the MailboxEmailActivity interface.
 */
export function instanceOfMailboxEmailActivity(value: object): value is MailboxEmailActivity {
    return true;
}

export function MailboxEmailActivityFromJSON(json: any): MailboxEmailActivity {
    return MailboxEmailActivityFromJSONTyped(json, false);
}

export function MailboxEmailActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxEmailActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'receivedCount': json['received_count'] == null ? undefined : json['received_count'],
        'lastReceivedAt': json['last_received_at'] === undefined ? undefined : json['last_received_at'] === null ? null : (parseDateTime(json['last_received_at'])),
        'lastReceivedPath': json['last_received_path'] === undefined ? undefined : json['last_received_path'] === null ? null : json['last_received_path'],
    };
}

export function MailboxEmailActivityToJSON(json: any): MailboxEmailActivity {
    return MailboxEmailActivityToJSONTyped(json, false);
}

export function MailboxEmailActivityToJSONTyped(value?: MailboxEmailActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'received_count': value['receivedCount'],
        'last_received_at': value['lastReceivedAt'] == null ? value['lastReceivedAt'] : serializeDateTime(value['lastReceivedAt']),
        'last_received_path': value['lastReceivedPath'],
    };
}

