/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxAction
 */
export interface MailboxAction {
    /**
     * 
     */
    allowed: boolean;
    /**
     * 
     */
    blockedReason?: string;
    /**
     * 
     */
    requiredAction?: string;
    /**
     * 
     */
    confirmation?: string;
}

/**
 * Check if a given object implements the MailboxAction interface.
 */
export function instanceOfMailboxAction(value: object): value is MailboxAction {
    if (!('allowed' in value) || value['allowed'] === undefined) return false;
    return true;
}

export function MailboxActionFromJSON(json: any): MailboxAction {
    return MailboxActionFromJSONTyped(json, false);
}

export function MailboxActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxAction {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed': json['allowed'],
        'blockedReason': json['blocked_reason'] == null ? undefined : json['blocked_reason'],
        'requiredAction': json['required_action'] == null ? undefined : json['required_action'],
        'confirmation': json['confirmation'] == null ? undefined : json['confirmation'],
    };
}

export function MailboxActionToJSON(json: any): MailboxAction {
    return MailboxActionToJSONTyped(json, false);
}

export function MailboxActionToJSONTyped(value?: MailboxAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed': value['allowed'],
        'blocked_reason': value['blockedReason'],
        'required_action': value['requiredAction'],
        'confirmation': value['confirmation'],
    };
}

