/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { EmailSenderAllowlist } from './EmailSenderAllowlist';
import {
    EmailSenderAllowlistFromJSON,
    EmailSenderAllowlistFromJSONTyped,
    EmailSenderAllowlistToJSON,
    EmailSenderAllowlistToJSONTyped,
} from './EmailSenderAllowlist';
import type { MailboxEmailCustomization } from './MailboxEmailCustomization';
import {
    MailboxEmailCustomizationFromJSON,
    MailboxEmailCustomizationFromJSONTyped,
    MailboxEmailCustomizationToJSON,
    MailboxEmailCustomizationToJSONTyped,
} from './MailboxEmailCustomization';
import type { MailboxEmailAliasesInner } from './MailboxEmailAliasesInner';
import {
    MailboxEmailAliasesInnerFromJSON,
    MailboxEmailAliasesInnerFromJSONTyped,
    MailboxEmailAliasesInnerToJSON,
    MailboxEmailAliasesInnerToJSONTyped,
} from './MailboxEmailAliasesInner';
import type { MailboxEmailAssignment } from './MailboxEmailAssignment';
import {
    MailboxEmailAssignmentFromJSON,
    MailboxEmailAssignmentFromJSONTyped,
    MailboxEmailAssignmentToJSON,
    MailboxEmailAssignmentToJSONTyped,
} from './MailboxEmailAssignment';
import type { MailboxEmailAvailableDomainsInner } from './MailboxEmailAvailableDomainsInner';
import {
    MailboxEmailAvailableDomainsInnerFromJSON,
    MailboxEmailAvailableDomainsInnerFromJSONTyped,
    MailboxEmailAvailableDomainsInnerToJSON,
    MailboxEmailAvailableDomainsInnerToJSONTyped,
} from './MailboxEmailAvailableDomainsInner';

/**
 * Authorized mailbox reads include the email address. Creation and opt-in reads also include receiving settings; use the emails collection for a durable arrival cursor.
 * @export
 * @interface MailboxEmail
 */
export interface MailboxEmail {
    /**
     * 
     */
    address?: string | null;
    /**
     * 
     */
    receivedCount?: number;
    /**
     * 
     */
    lastReceivedAt?: Date | null;
    /**
     * Latest message folder with trailing slash; null before receipt. May become stale after manual file moves/deletion.
     */
    lastReceivedPath?: string | null;
    /**
     * Why receiving is unavailable; omitted when receiving_enabled is true.
     */
    blockedReason?: string | null;
    /**
     * 
     */
    availableDomains?: Array<MailboxEmailAvailableDomainsInner>;
    /**
     * 
     */
    assignment?: MailboxEmailAssignment;
    /**
     * 
     */
    customization?: MailboxEmailCustomization;
    /**
     * Whether this mailbox can currently receive email. False when configuration, account state, quota or routing prevents receiving.
     */
    receivingEnabled?: boolean;
    /**
     * 
     */
    senderAllowlist?: EmailSenderAllowlist;
    /**
     * 
     */
    username?: string | null;
    /**
     * Always false. Sending is not implemented.
     */
    sendingEnabled?: boolean;
    /**
     * 
     */
    aliases?: Array<MailboxEmailAliasesInner>;
}

/**
 * Check if a given object implements the MailboxEmail interface.
 */
export function instanceOfMailboxEmail(value: object): value is MailboxEmail {
    return true;
}

export function MailboxEmailFromJSON(json: any): MailboxEmail {
    return MailboxEmailFromJSONTyped(json, false);
}

export function MailboxEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] === undefined ? undefined : json['address'] === null ? null : json['address'],
        'receivedCount': json['received_count'] == null ? undefined : json['received_count'],
        'lastReceivedAt': json['last_received_at'] === undefined ? undefined : json['last_received_at'] === null ? null : (parseDateTime(json['last_received_at'])),
        'lastReceivedPath': json['last_received_path'] === undefined ? undefined : json['last_received_path'] === null ? null : json['last_received_path'],
        'blockedReason': json['blocked_reason'] === undefined ? undefined : json['blocked_reason'] === null ? null : json['blocked_reason'],
        'availableDomains': json['available_domains'] == null ? undefined : ((json['available_domains'] as Array<any>).map(MailboxEmailAvailableDomainsInnerFromJSON)),
        'assignment': json['assignment'] == null ? undefined : MailboxEmailAssignmentFromJSON(json['assignment']),
        'customization': json['customization'] == null ? undefined : MailboxEmailCustomizationFromJSON(json['customization']),
        'receivingEnabled': json['receiving_enabled'] == null ? undefined : json['receiving_enabled'],
        'senderAllowlist': json['sender_allowlist'] == null ? undefined : EmailSenderAllowlistFromJSON(json['sender_allowlist']),
        'username': json['username'] === undefined ? undefined : json['username'] === null ? null : json['username'],
        'sendingEnabled': json['sending_enabled'] == null ? undefined : json['sending_enabled'],
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(MailboxEmailAliasesInnerFromJSON)),
    };
}

export function MailboxEmailToJSON(json: any): MailboxEmail {
    return MailboxEmailToJSONTyped(json, false);
}

export function MailboxEmailToJSONTyped(value?: MailboxEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'received_count': value['receivedCount'],
        'last_received_at': value['lastReceivedAt'] == null ? value['lastReceivedAt'] : serializeDateTime(value['lastReceivedAt']),
        'last_received_path': value['lastReceivedPath'],
        'blocked_reason': value['blockedReason'],
        'available_domains': value['availableDomains'] == null ? undefined : ((value['availableDomains'] as Array<any>).map(MailboxEmailAvailableDomainsInnerToJSON)),
        'assignment': MailboxEmailAssignmentToJSON(value['assignment']),
        'customization': MailboxEmailCustomizationToJSON(value['customization']),
        'receiving_enabled': value['receivingEnabled'],
        'sender_allowlist': EmailSenderAllowlistToJSON(value['senderAllowlist']),
        'username': value['username'],
        'sending_enabled': value['sendingEnabled'],
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(MailboxEmailAliasesInnerToJSON)),
    };
}

