/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxLockLockedBy
 */
export interface MailboxLockLockedBy {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    email?: string;
    /**
     * 
     */
    name?: string;
}

/**
 * Check if a given object implements the MailboxLockLockedBy interface.
 */
export function instanceOfMailboxLockLockedBy(value: object): value is MailboxLockLockedBy {
    return true;
}

export function MailboxLockLockedByFromJSON(json: any): MailboxLockLockedBy {
    return MailboxLockLockedByFromJSONTyped(json, false);
}

export function MailboxLockLockedByFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxLockLockedBy {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MailboxLockLockedByToJSON(json: any): MailboxLockLockedBy {
    return MailboxLockLockedByToJSONTyped(json, false);
}

export function MailboxLockLockedByToJSONTyped(value?: MailboxLockLockedBy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
    };
}

