/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxFile } from './MailboxFile';
import {
    MailboxFileFromJSON,
    MailboxFileFromJSONTyped,
    MailboxFileToJSON,
    MailboxFileToJSONTyped,
} from './MailboxFile';

/**
 * 
 * @export
 * @interface MailboxFileResponseData
 */
export interface MailboxFileResponseData {
    /**
     * 
     */
    file: MailboxFile;
}

/**
 * Check if a given object implements the MailboxFileResponseData interface.
 */
export function instanceOfMailboxFileResponseData(value: object): value is MailboxFileResponseData {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function MailboxFileResponseDataFromJSON(json: any): MailboxFileResponseData {
    return MailboxFileResponseDataFromJSONTyped(json, false);
}

export function MailboxFileResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxFileResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'file': MailboxFileFromJSON(json['file']),
    };
}

export function MailboxFileResponseDataToJSON(json: any): MailboxFileResponseData {
    return MailboxFileResponseDataToJSONTyped(json, false);
}

export function MailboxFileResponseDataToJSONTyped(value?: MailboxFileResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': MailboxFileToJSON(value['file']),
    };
}

