/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxEmailAssignmentError
 */
export interface MailboxEmailAssignmentError {
    /**
     * 
     */
    code?: string;
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    retryable?: boolean;
}

/**
 * Check if a given object implements the MailboxEmailAssignmentError interface.
 */
export function instanceOfMailboxEmailAssignmentError(value: object): value is MailboxEmailAssignmentError {
    return true;
}

export function MailboxEmailAssignmentErrorFromJSON(json: any): MailboxEmailAssignmentError {
    return MailboxEmailAssignmentErrorFromJSONTyped(json, false);
}

export function MailboxEmailAssignmentErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxEmailAssignmentError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'retryable': json['retryable'] == null ? undefined : json['retryable'],
    };
}

export function MailboxEmailAssignmentErrorToJSON(json: any): MailboxEmailAssignmentError {
    return MailboxEmailAssignmentErrorToJSONTyped(json, false);
}

export function MailboxEmailAssignmentErrorToJSONTyped(value?: MailboxEmailAssignmentError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'retryable': value['retryable'],
    };
}

