/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxEmailOptions } from './MailboxEmailOptions';
import {
    MailboxEmailOptionsFromJSON,
    MailboxEmailOptionsFromJSONTyped,
    MailboxEmailOptionsToJSON,
    MailboxEmailOptionsToJSONTyped,
} from './MailboxEmailOptions';

/**
 * 
 * @export
 * @interface MailboxCreateOptions
 */
export interface MailboxCreateOptions {
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     */
    tagIds?: Array<string>;
    /**
     * 
     */
    tagPaths?: Array<string>;
    /**
     * 
     */
    email?: MailboxEmailOptions;
}

/**
 * Check if a given object implements the MailboxCreateOptions interface.
 */
export function instanceOfMailboxCreateOptions(value: object): value is MailboxCreateOptions {
    return true;
}

export function MailboxCreateOptionsFromJSON(json: any): MailboxCreateOptions {
    return MailboxCreateOptionsFromJSONTyped(json, false);
}

export function MailboxCreateOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxCreateOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'tagIds': json['tag_ids'] == null ? undefined : json['tag_ids'],
        'tagPaths': json['tag_paths'] == null ? undefined : json['tag_paths'],
        'email': json['email'] == null ? undefined : MailboxEmailOptionsFromJSON(json['email']),
    };
}

export function MailboxCreateOptionsToJSON(json: any): MailboxCreateOptions {
    return MailboxCreateOptionsToJSONTyped(json, false);
}

export function MailboxCreateOptionsToJSONTyped(value?: MailboxCreateOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'metadata': value['metadata'],
        'tag_ids': value['tagIds'],
        'tag_paths': value['tagPaths'],
        'email': MailboxEmailOptionsToJSON(value['email']),
    };
}

