/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { FileKey } from './FileKey';
import {
    FileKeyFromJSON,
    FileKeyFromJSONTyped,
    FileKeyToJSON,
    FileKeyToJSONTyped,
} from './FileKey';
import type { FileVersionReason } from './FileVersionReason';
import {
    FileVersionReasonFromJSON,
    FileVersionReasonFromJSONTyped,
    FileVersionReasonToJSON,
    FileVersionReasonToJSONTyped,
} from './FileVersionReason';
import type { FileActor } from './FileActor';
import {
    FileActorFromJSON,
    FileActorFromJSONTyped,
    FileActorToJSON,
    FileActorToJSONTyped,
} from './FileActor';
import type { FileVersion } from './FileVersion';
import {
    FileVersionFromJSON,
    FileVersionFromJSONTyped,
    FileVersionToJSON,
    FileVersionToJSONTyped,
} from './FileVersion';

/**
 * 
 * @export
 * @interface MailboxFile
 */
export interface MailboxFile {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    mailboxId?: string;
    /**
     * 
     */
    basename?: string;
    /**
     * 
     */
    path: string;
    /**
     * 
     */
    role?: string;
    /**
     * 
     */
    createdBySystem?: string;
    /**
     * 
     */
    deleted?: boolean;
    /**
     * 
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     */
    versionReasons?: Array<FileVersionReason>;
    /**
     * 
     */
    lock?: { [key: string]: any; };
    /**
     * 
     */
    currentFileVersion?: FileVersion | null;
    /**
     * 
     */
    createdBy?: FileActor;
    /**
     * 
     */
    createdAt?: Date;
    /**
     * 
     */
    updatedAt?: Date;
    /**
     * 
     */
    deletedAt?: Date;
    /**
     * 
     */
    createdByAgent?: { [key: string]: any; };
    /**
     * 
     */
    updatedByAgent?: { [key: string]: any; };
    /**
     * 
     */
    createdByApiKey?: { [key: string]: any; };
    /**
     * 
     */
    updatedByApiKey?: { [key: string]: any; };
    /**
     * 
     */
    read?: boolean;
    /**
     * 
     */
    readAt?: Date | null;
    /**
     * 
     */
    readBy?: FileActor | null;
    /**
     * 
     */
    readByApiKey?: FileKey | null;
}

/**
 * Check if a given object implements the MailboxFile interface.
 */
export function instanceOfMailboxFile(value: object): value is MailboxFile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function MailboxFileFromJSON(json: any): MailboxFile {
    return MailboxFileFromJSONTyped(json, false);
}

export function MailboxFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxFile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mailboxId': json['mailbox_id'] == null ? undefined : json['mailbox_id'],
        'basename': json['basename'] == null ? undefined : json['basename'],
        'path': json['path'],
        'role': json['role'] == null ? undefined : json['role'],
        'createdBySystem': json['created_by_system'] == null ? undefined : json['created_by_system'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'versionReasons': json['version_reasons'] == null ? undefined : ((json['version_reasons'] as Array<any>).map(FileVersionReasonFromJSON)),
        'lock': json['lock'] == null ? undefined : json['lock'],
        'currentFileVersion': json['current_file_version'] === undefined ? undefined : json['current_file_version'] === null ? null : FileVersionFromJSON(json['current_file_version']),
        'createdBy': json['created_by'] == null ? undefined : FileActorFromJSON(json['created_by']),
        'createdAt': json['created_at'] == null ? undefined : (parseDateTime(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (parseDateTime(json['updated_at'])),
        'deletedAt': json['deleted_at'] == null ? undefined : (parseDateTime(json['deleted_at'])),
        'createdByAgent': json['created_by_agent'] == null ? undefined : json['created_by_agent'],
        'updatedByAgent': json['updated_by_agent'] == null ? undefined : json['updated_by_agent'],
        'createdByApiKey': json['created_by_api_key'] == null ? undefined : json['created_by_api_key'],
        'updatedByApiKey': json['updated_by_api_key'] == null ? undefined : json['updated_by_api_key'],
        'read': json['read'] == null ? undefined : json['read'],
        'readAt': json['read_at'] === undefined ? undefined : json['read_at'] === null ? null : (parseDateTime(json['read_at'])),
        'readBy': json['read_by'] === undefined ? undefined : json['read_by'] === null ? null : FileActorFromJSON(json['read_by']),
        'readByApiKey': json['read_by_api_key'] === undefined ? undefined : json['read_by_api_key'] === null ? null : FileKeyFromJSON(json['read_by_api_key']),
    };
}

export function MailboxFileToJSON(json: any): MailboxFile {
    return MailboxFileToJSONTyped(json, false);
}

export function MailboxFileToJSONTyped(value?: MailboxFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'mailbox_id': value['mailboxId'],
        'basename': value['basename'],
        'path': value['path'],
        'role': value['role'],
        'created_by_system': value['createdBySystem'],
        'deleted': value['deleted'],
        'metadata': value['metadata'],
        'version_reasons': value['versionReasons'] == null ? undefined : ((value['versionReasons'] as Array<any>).map(FileVersionReasonToJSON)),
        'lock': value['lock'],
        'current_file_version': FileVersionToJSON(value['currentFileVersion']),
        'created_by': FileActorToJSON(value['createdBy']),
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'deleted_at': value['deletedAt'] == null ? value['deletedAt'] : serializeDateTime(value['deletedAt']),
        'created_by_agent': value['createdByAgent'],
        'updated_by_agent': value['updatedByAgent'],
        'created_by_api_key': value['createdByApiKey'],
        'updated_by_api_key': value['updatedByApiKey'],
        'read': value['read'],
        'read_at': value['readAt'] == null ? value['readAt'] : serializeDateTime(value['readAt']),
        'read_by': FileActorToJSON(value['readBy']),
        'read_by_api_key': FileKeyToJSON(value['readByApiKey']),
    };
}

