/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { MailboxLock } from './MailboxLock';
import {
    MailboxLockFromJSON,
    MailboxLockFromJSONTyped,
    MailboxLockToJSON,
    MailboxLockToJSONTyped,
} from './MailboxLock';
import type { MailboxEmail } from './MailboxEmail';
import {
    MailboxEmailFromJSON,
    MailboxEmailFromJSONTyped,
    MailboxEmailToJSON,
    MailboxEmailToJSONTyped,
} from './MailboxEmail';
import type { MailboxAction } from './MailboxAction';
import {
    MailboxActionFromJSON,
    MailboxActionFromJSONTyped,
    MailboxActionToJSON,
    MailboxActionToJSONTyped,
} from './MailboxAction';

/**
 * Public mailbox details. Write-authorized reads include email.address. Creation and authorized include_email reads also include receiving settings.
 * @export
 * @interface Mailbox
 */
export interface Mailbox {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    description?: string | null;
    /**
     * 
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     */
    metadataVersion?: string;
    /**
     * 
     */
    email: MailboxEmail;
    /**
     * 
     */
    archived?: boolean;
    /**
     * 
     */
    archivedAt?: Date | null;
    /**
     * 
     */
    lock?: MailboxLock;
    /**
     * 
     */
    storageBytes?: number;
    /**
     * 
     */
    filesCount?: number;
    /**
     * 
     */
    createdAt?: Date | null;
    /**
     * 
     */
    updatedAt?: Date | null;
    /**
     * 
     */
    dashboardUrl?: string;
    /**
     * 
     */
    currentMailboxRevisionId?: string | null;
    /**
     * 
     */
    currentMailboxRevisionNumber?: number;
    /**
     * 
     */
    archive?: MailboxAction;
    /**
     * 
     */
    unarchive?: MailboxAction;
    /**
     * 
     */
    _delete?: MailboxAction;
}

/**
 * Check if a given object implements the Mailbox interface.
 */
export function instanceOfMailbox(value: object): value is Mailbox {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('accountId' in (value as Record<string, any>)) && !('account_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['accountId'] === undefined && (value as Record<string, any>)['account_id'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function MailboxFromJSON(json: any): Mailbox {
    return MailboxFromJSONTyped(json, false);
}

export function MailboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mailbox {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'accountId': json['account_id'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'metadataVersion': json['metadata_version'] == null ? undefined : json['metadata_version'],
        'email': MailboxEmailFromJSON(json['email']),
        'archived': json['archived'] == null ? undefined : json['archived'],
        'archivedAt': json['archived_at'] === undefined ? undefined : json['archived_at'] === null ? null : (parseDateTime(json['archived_at'])),
        'lock': json['lock'] == null ? undefined : MailboxLockFromJSON(json['lock']),
        'storageBytes': json['storage_bytes'] == null ? undefined : json['storage_bytes'],
        'filesCount': json['files_count'] == null ? undefined : json['files_count'],
        'createdAt': json['created_at'] === undefined ? undefined : json['created_at'] === null ? null : (parseDateTime(json['created_at'])),
        'updatedAt': json['updated_at'] === undefined ? undefined : json['updated_at'] === null ? null : (parseDateTime(json['updated_at'])),
        'dashboardUrl': json['dashboard_url'] == null ? undefined : json['dashboard_url'],
        'currentMailboxRevisionId': json['current_mailbox_revision_id'] === undefined ? undefined : json['current_mailbox_revision_id'] === null ? null : json['current_mailbox_revision_id'],
        'currentMailboxRevisionNumber': json['current_mailbox_revision_number'] == null ? undefined : json['current_mailbox_revision_number'],
        'archive': json['archive'] == null ? undefined : MailboxActionFromJSON(json['archive']),
        'unarchive': json['unarchive'] == null ? undefined : MailboxActionFromJSON(json['unarchive']),
        '_delete': json['delete'] == null ? undefined : MailboxActionFromJSON(json['delete']),
    };
}

export function MailboxToJSON(json: any): Mailbox {
    return MailboxToJSONTyped(json, false);
}

export function MailboxToJSONTyped(value?: Mailbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'account_id': value['accountId'],
        'description': value['description'],
        'metadata': value['metadata'],
        'metadata_version': value['metadataVersion'],
        'email': MailboxEmailToJSON(value['email']),
        'archived': value['archived'],
        'archived_at': value['archivedAt'] == null ? value['archivedAt'] : serializeDateTime(value['archivedAt']),
        'lock': MailboxLockToJSON(value['lock']),
        'storage_bytes': value['storageBytes'],
        'files_count': value['filesCount'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'dashboard_url': value['dashboardUrl'],
        'current_mailbox_revision_id': value['currentMailboxRevisionId'],
        'current_mailbox_revision_number': value['currentMailboxRevisionNumber'],
        'archive': MailboxActionToJSON(value['archive']),
        'unarchive': MailboxActionToJSON(value['unarchive']),
        'delete': MailboxActionToJSON(value['_delete']),
    };
}

