/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxEmailOptions
 */
export interface MailboxEmailOptions {
    /**
     * Free: a prefix normalized to dots, shortened to 51 characters, with a permanent 12-character random lowercase letter/digit suffix added. Paid: the exact name before @, normalized to lowercase. Omit to generate; blank/null is invalid. Reserved shared-domain words return EMAIL_NAME_RESERVED with the reserved word and custom-domain guidance; occupied or retired exact names return EMAIL_ALREADY_EXISTS.
     */
    username?: string;
    /**
     * Built-in domain such as revdokumail.com on any plan, or a ready custom email domain owned by the selected account on an eligible plan. Omit for the default platform domain.
     */
    domain?: string;
}

/**
 * Check if a given object implements the MailboxEmailOptions interface.
 */
export function instanceOfMailboxEmailOptions(value: object): value is MailboxEmailOptions {
    return true;
}

export function MailboxEmailOptionsFromJSON(json: any): MailboxEmailOptions {
    return MailboxEmailOptionsFromJSONTyped(json, false);
}

export function MailboxEmailOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxEmailOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function MailboxEmailOptionsToJSON(json: any): MailboxEmailOptions {
    return MailboxEmailOptionsToJSONTyped(json, false);
}

export function MailboxEmailOptionsToJSONTyped(value?: MailboxEmailOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'domain': value['domain'],
    };
}

