/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadBlob } from './UploadBlob';
import {
    UploadBlobFromJSON,
    UploadBlobFromJSONTyped,
    UploadBlobToJSON,
    UploadBlobToJSONTyped,
} from './UploadBlob';

/**
 * 
 * @export
 * @interface PrepareFileUploadRequest
 */
export interface PrepareFileUploadRequest {
    /**
     * 
     */
    mailboxId: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * 
     */
    path: string;
    /**
     * 
     */
    blob: UploadBlob;
}

/**
 * Check if a given object implements the PrepareFileUploadRequest interface.
 */
export function instanceOfPrepareFileUploadRequest(value: object): value is PrepareFileUploadRequest {
    if ((!('mailboxId' in (value as Record<string, any>)) && !('mailbox_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['mailboxId'] === undefined && (value as Record<string, any>)['mailbox_id'] === undefined)) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('blob' in value) || value['blob'] === undefined) return false;
    return true;
}

export function PrepareFileUploadRequestFromJSON(json: any): PrepareFileUploadRequest {
    return PrepareFileUploadRequestFromJSONTyped(json, false);
}

export function PrepareFileUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareFileUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mailboxId': json['mailbox_id'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'path': json['path'],
        'blob': UploadBlobFromJSON(json['blob']),
    };
}

export function PrepareFileUploadRequestToJSON(json: any): PrepareFileUploadRequest {
    return PrepareFileUploadRequestToJSONTyped(json, false);
}

export function PrepareFileUploadRequestToJSONTyped(value?: PrepareFileUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mailbox_id': value['mailboxId'],
        'account_id': value['accountId'],
        'path': value['path'],
        'blob': UploadBlobToJSON(value['blob']),
    };
}

