/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PreparedFileUpload } from './PreparedFileUpload';
import {
    PreparedFileUploadFromJSON,
    PreparedFileUploadFromJSONTyped,
    PreparedFileUploadToJSON,
    PreparedFileUploadToJSONTyped,
} from './PreparedFileUpload';

/**
 * 
 * @export
 * @interface PreparedFileUploadResponse
 */
export interface PreparedFileUploadResponse {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: PreparedFileUpload;
}

/**
 * Check if a given object implements the PreparedFileUploadResponse interface.
 */
export function instanceOfPreparedFileUploadResponse(value: object): value is PreparedFileUploadResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PreparedFileUploadResponseFromJSON(json: any): PreparedFileUploadResponse {
    return PreparedFileUploadResponseFromJSONTyped(json, false);
}

export function PreparedFileUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreparedFileUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PreparedFileUploadFromJSON(json['data']),
    };
}

export function PreparedFileUploadResponseToJSON(json: any): PreparedFileUploadResponse {
    return PreparedFileUploadResponseToJSONTyped(json, false);
}

export function PreparedFileUploadResponseToJSONTyped(value?: PreparedFileUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PreparedFileUploadToJSON(value['data']),
    };
}

