/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StorageUpload } from './StorageUpload';
import {
    StorageUploadFromJSON,
    StorageUploadFromJSONTyped,
    StorageUploadToJSON,
    StorageUploadToJSONTyped,
} from './StorageUpload';
import type { FileVersion } from './FileVersion';
import {
    FileVersionFromJSON,
    FileVersionFromJSONTyped,
    FileVersionToJSON,
    FileVersionToJSONTyped,
} from './FileVersion';
import type { MailboxFile } from './MailboxFile';
import {
    MailboxFileFromJSON,
    MailboxFileFromJSONTyped,
    MailboxFileToJSON,
    MailboxFileToJSONTyped,
} from './MailboxFile';

/**
 * A new upload returns signed_id and direct_upload. Identical content returns skipped=true, duplicate=true, file and version without a storage upload.
 * @export
 * @interface PreparedFileUpload
 */
export interface PreparedFileUpload {
    /**
     * 
     */
    signedId?: string;
    /**
     * 
     */
    filename?: string;
    /**
     * 
     */
    byteSize?: number;
    /**
     * 
     */
    checksum?: string;
    /**
     * 
     */
    contentType?: string;
    /**
     * 
     */
    serviceName?: string;
    /**
     * 
     */
    directUpload?: StorageUpload;
    /**
     * 
     */
    file?: MailboxFile;
    /**
     * 
     */
    version?: FileVersion;
    /**
     * 
     */
    skipped?: boolean;
    /**
     * 
     */
    duplicate?: boolean;
    /**
     * 
     */
    reason?: string;
    /**
     * 
     */
    details?: { [key: string]: any; };
}

/**
 * Check if a given object implements the PreparedFileUpload interface.
 */
export function instanceOfPreparedFileUpload(value: object): value is PreparedFileUpload {
    return true;
}

export function PreparedFileUploadFromJSON(json: any): PreparedFileUpload {
    return PreparedFileUploadFromJSONTyped(json, false);
}

export function PreparedFileUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreparedFileUpload {
    if (json == null) {
        return json;
    }
    return {
        
        'signedId': json['signed_id'] == null ? undefined : json['signed_id'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'byteSize': json['byte_size'] == null ? undefined : json['byte_size'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'serviceName': json['service_name'] == null ? undefined : json['service_name'],
        'directUpload': json['direct_upload'] == null ? undefined : StorageUploadFromJSON(json['direct_upload']),
        'file': json['file'] == null ? undefined : MailboxFileFromJSON(json['file']),
        'version': json['version'] == null ? undefined : FileVersionFromJSON(json['version']),
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
        'duplicate': json['duplicate'] == null ? undefined : json['duplicate'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function PreparedFileUploadToJSON(json: any): PreparedFileUpload {
    return PreparedFileUploadToJSONTyped(json, false);
}

export function PreparedFileUploadToJSONTyped(value?: PreparedFileUpload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signed_id': value['signedId'],
        'filename': value['filename'],
        'byte_size': value['byteSize'],
        'checksum': value['checksum'],
        'content_type': value['contentType'],
        'service_name': value['serviceName'],
        'direct_upload': StorageUploadToJSON(value['directUpload']),
        'file': MailboxFileToJSON(value['file']),
        'version': FileVersionToJSON(value['version']),
        'skipped': value['skipped'],
        'duplicate': value['duplicate'],
        'reason': value['reason'],
        'details': value['details'],
    };
}

