/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveAccountEmailDomainRequest
 */
export interface RemoveAccountEmailDomainRequest {
    /**
     * 
     */
    hostname: string;
    /**
     * 
     */
    confirm: boolean;
    /**
     * Explicit granted account for this call.
     */
    accountId?: string;
    /**
     * Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the RemoveAccountEmailDomainRequest interface.
 */
export function instanceOfRemoveAccountEmailDomainRequest(value: object): value is RemoveAccountEmailDomainRequest {
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('confirm' in value) || value['confirm'] === undefined) return false;
    return true;
}

export function RemoveAccountEmailDomainRequestFromJSON(json: any): RemoveAccountEmailDomainRequest {
    return RemoveAccountEmailDomainRequestFromJSONTyped(json, false);
}

export function RemoveAccountEmailDomainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveAccountEmailDomainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'],
        'confirm': json['confirm'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function RemoveAccountEmailDomainRequestToJSON(json: any): RemoveAccountEmailDomainRequest {
    return RemoveAccountEmailDomainRequestToJSONTyped(json, false);
}

export function RemoveAccountEmailDomainRequestToJSONTyped(value?: RemoveAccountEmailDomainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'confirm': value['confirm'],
        'account_id': value['accountId'],
        'reason': value['reason'],
    };
}

