/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendAgentSignupCodeRequest
 */
export interface ResendAgentSignupCodeRequest {
    /**
     * Private signup token returned by the first request. Send only in the JSON body; never log it or show it in chat.
     */
    signupToken: string;
}

/**
 * Check if a given object implements the ResendAgentSignupCodeRequest interface.
 */
export function instanceOfResendAgentSignupCodeRequest(value: object): value is ResendAgentSignupCodeRequest {
    if ((!('signupToken' in (value as Record<string, any>)) && !('signup_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['signupToken'] === undefined && (value as Record<string, any>)['signup_token'] === undefined)) return false;
    return true;
}

export function ResendAgentSignupCodeRequestFromJSON(json: any): ResendAgentSignupCodeRequest {
    return ResendAgentSignupCodeRequestFromJSONTyped(json, false);
}

export function ResendAgentSignupCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendAgentSignupCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'signupToken': json['signup_token'],
    };
}

export function ResendAgentSignupCodeRequestToJSON(json: any): ResendAgentSignupCodeRequest {
    return ResendAgentSignupCodeRequestToJSONTyped(json, false);
}

export function ResendAgentSignupCodeRequestToJSONTyped(value?: ResendAgentSignupCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signup_token': value['signupToken'],
    };
}

