/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RotateBucketEmailAddressRequest
 */
export interface RotateBucketEmailAddressRequest {
    /**
     * 
     */
    confirm: boolean;
    /**
     * 
     */
    currentAddress: string;
    /**
     * Explicitly granted account; omission uses credential default
     */
    accountId?: string;
    /**
     * Exact ready domain of this account, or platform for the deployment default.
     */
    domain?: string;
    /**
     * Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
     */
    reason?: string | null;
    /**
     * Administrator-selected name on an available platform or ready owned custom domain. Normalized to lowercase; ASCII letters/digits/dots/hyphens/underscores, alphanumeric endpoints, no consecutive dots. Complete address at most 254 characters. Omit for random rotation; blank/null is invalid.
     */
    username?: string;
    /**
     * Keep the old primary as an alias for this inbox after activation. Requires full-account administrator access and an available alias slot.
     */
    keepOldAsAlias?: boolean;
}

/**
 * Check if a given object implements the RotateBucketEmailAddressRequest interface.
 */
export function instanceOfRotateBucketEmailAddressRequest(value: object): value is RotateBucketEmailAddressRequest {
    if (!('confirm' in value) || value['confirm'] === undefined) return false;
    if ((!('currentAddress' in (value as Record<string, any>)) && !('current_address' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentAddress'] === undefined && (value as Record<string, any>)['current_address'] === undefined)) return false;
    return true;
}

export function RotateBucketEmailAddressRequestFromJSON(json: any): RotateBucketEmailAddressRequest {
    return RotateBucketEmailAddressRequestFromJSONTyped(json, false);
}

export function RotateBucketEmailAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateBucketEmailAddressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'confirm': json['confirm'],
        'currentAddress': json['current_address'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
        'username': json['username'] == null ? undefined : json['username'],
        'keepOldAsAlias': json['keep_old_as_alias'] == null ? undefined : json['keep_old_as_alias'],
    };
}

export function RotateBucketEmailAddressRequestToJSON(json: any): RotateBucketEmailAddressRequest {
    return RotateBucketEmailAddressRequestToJSONTyped(json, false);
}

export function RotateBucketEmailAddressRequestToJSONTyped(value?: RotateBucketEmailAddressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confirm': value['confirm'],
        'current_address': value['currentAddress'],
        'account_id': value['accountId'],
        'domain': value['domain'],
        'reason': value['reason'],
        'username': value['username'],
        'keep_old_as_alias': value['keepOldAsAlias'],
    };
}

