/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SavedFile } from './SavedFile';
import {
    SavedFileFromJSON,
    SavedFileFromJSONTyped,
    SavedFileToJSON,
    SavedFileToJSONTyped,
} from './SavedFile';

/**
 * 
 * @export
 * @interface SavedFileResponse
 */
export interface SavedFileResponse {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: SavedFile;
}

/**
 * Check if a given object implements the SavedFileResponse interface.
 */
export function instanceOfSavedFileResponse(value: object): value is SavedFileResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SavedFileResponseFromJSON(json: any): SavedFileResponse {
    return SavedFileResponseFromJSONTyped(json, false);
}

export function SavedFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavedFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SavedFileFromJSON(json['data']),
    };
}

export function SavedFileResponseToJSON(json: any): SavedFileResponse {
    return SavedFileResponseToJSONTyped(json, false);
}

export function SavedFileResponseToJSONTyped(value?: SavedFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SavedFileToJSON(value['data']),
    };
}

