/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveUploadedFileRequest
 */
export interface SaveUploadedFileRequest {
    /**
     * 
     */
    path: string;
    /**
     * 
     */
    signedBlobId: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * 
     */
    expectedMailboxRevisionId?: string;
    /**
     * Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the SaveUploadedFileRequest interface.
 */
export function instanceOfSaveUploadedFileRequest(value: object): value is SaveUploadedFileRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    if ((!('signedBlobId' in (value as Record<string, any>)) && !('signed_blob_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['signedBlobId'] === undefined && (value as Record<string, any>)['signed_blob_id'] === undefined)) return false;
    return true;
}

export function SaveUploadedFileRequestFromJSON(json: any): SaveUploadedFileRequest {
    return SaveUploadedFileRequestFromJSONTyped(json, false);
}

export function SaveUploadedFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveUploadedFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'signedBlobId': json['signed_blob_id'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'expectedMailboxRevisionId': json['expected_mailbox_revision_id'] == null ? undefined : json['expected_mailbox_revision_id'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function SaveUploadedFileRequestToJSON(json: any): SaveUploadedFileRequest {
    return SaveUploadedFileRequestToJSONTyped(json, false);
}

export function SaveUploadedFileRequestToJSONTyped(value?: SaveUploadedFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'signed_blob_id': value['signedBlobId'],
        'account_id': value['accountId'],
        'expected_mailbox_revision_id': value['expectedMailboxRevisionId'],
        'reason': value['reason'],
    };
}

