/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetEmailWebhook200ResponseData } from './SetEmailWebhook200ResponseData';
import {
    SetEmailWebhook200ResponseDataFromJSON,
    SetEmailWebhook200ResponseDataFromJSONTyped,
    SetEmailWebhook200ResponseDataToJSON,
    SetEmailWebhook200ResponseDataToJSONTyped,
} from './SetEmailWebhook200ResponseData';

/**
 * 
 * @export
 * @interface SetEmailWebhook200Response
 */
export interface SetEmailWebhook200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: SetEmailWebhook200ResponseData;
}

/**
 * Check if a given object implements the SetEmailWebhook200Response interface.
 */
export function instanceOfSetEmailWebhook200Response(value: object): value is SetEmailWebhook200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SetEmailWebhook200ResponseFromJSON(json: any): SetEmailWebhook200Response {
    return SetEmailWebhook200ResponseFromJSONTyped(json, false);
}

export function SetEmailWebhook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetEmailWebhook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SetEmailWebhook200ResponseDataFromJSON(json['data']),
    };
}

export function SetEmailWebhook200ResponseToJSON(json: any): SetEmailWebhook200Response {
    return SetEmailWebhook200ResponseToJSONTyped(json, false);
}

export function SetEmailWebhook200ResponseToJSONTyped(value?: SetEmailWebhook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SetEmailWebhook200ResponseDataToJSON(value['data']),
    };
}

