/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetEmailWebhookRequest
 */
export interface SetEmailWebhookRequest {
    /**
     * 
     */
    webhookUrl: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * Rotate the secret for the same endpoint and cancel pending deliveries.
     */
    rotateSecret?: boolean;
}

/**
 * Check if a given object implements the SetEmailWebhookRequest interface.
 */
export function instanceOfSetEmailWebhookRequest(value: object): value is SetEmailWebhookRequest {
    if ((!('webhookUrl' in (value as Record<string, any>)) && !('webhook_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['webhookUrl'] === undefined && (value as Record<string, any>)['webhook_url'] === undefined)) return false;
    return true;
}

export function SetEmailWebhookRequestFromJSON(json: any): SetEmailWebhookRequest {
    return SetEmailWebhookRequestFromJSONTyped(json, false);
}

export function SetEmailWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetEmailWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'webhookUrl': json['webhook_url'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'rotateSecret': json['rotate_secret'] == null ? undefined : json['rotate_secret'],
    };
}

export function SetEmailWebhookRequestToJSON(json: any): SetEmailWebhookRequest {
    return SetEmailWebhookRequestToJSONTyped(json, false);
}

export function SetEmailWebhookRequestToJSONTyped(value?: SetEmailWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhook_url': value['webhookUrl'],
        'account_id': value['accountId'],
        'rotate_secret': value['rotateSecret'],
    };
}

