/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetEmailWebhook200ResponseDataWebhook
 */
export interface SetEmailWebhook200ResponseDataWebhook {
    /**
     * 
     */
    url: string;
    /**
     * 
     */
    event: SetEmailWebhook200ResponseDataWebhookEventEnum;
    /**
     * 
     */
    signingSecret: string;
}


/**
 * @export
 */
export const SetEmailWebhook200ResponseDataWebhookEventEnum = {
    EmailReceived: 'email.received',
} as const;
export type SetEmailWebhook200ResponseDataWebhookEventEnum = typeof SetEmailWebhook200ResponseDataWebhookEventEnum[keyof typeof SetEmailWebhook200ResponseDataWebhookEventEnum];


/**
 * Check if a given object implements the SetEmailWebhook200ResponseDataWebhook interface.
 */
export function instanceOfSetEmailWebhook200ResponseDataWebhook(value: object): value is SetEmailWebhook200ResponseDataWebhook {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (value['event'] !== 'email.received') return false;
    
    if ((!('signingSecret' in (value as Record<string, any>)) && !('signing_secret' in (value as Record<string, any>))) || ((value as Record<string, any>)['signingSecret'] === undefined && (value as Record<string, any>)['signing_secret'] === undefined)) return false;
    return true;
}

export function SetEmailWebhook200ResponseDataWebhookFromJSON(json: any): SetEmailWebhook200ResponseDataWebhook {
    return SetEmailWebhook200ResponseDataWebhookFromJSONTyped(json, false);
}

export function SetEmailWebhook200ResponseDataWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetEmailWebhook200ResponseDataWebhook {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'event': json['event'],
        'signingSecret': json['signing_secret'],
    };
}

export function SetEmailWebhook200ResponseDataWebhookToJSON(json: any): SetEmailWebhook200ResponseDataWebhook {
    return SetEmailWebhook200ResponseDataWebhookToJSONTyped(json, false);
}

export function SetEmailWebhook200ResponseDataWebhookToJSONTyped(value?: SetEmailWebhook200ResponseDataWebhook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'event': value['event'],
        'signing_secret': value['signingSecret'],
    };
}

