/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetEmailWebhook200ResponseDataWebhook } from './SetEmailWebhook200ResponseDataWebhook';
import {
    SetEmailWebhook200ResponseDataWebhookFromJSON,
    SetEmailWebhook200ResponseDataWebhookFromJSONTyped,
    SetEmailWebhook200ResponseDataWebhookToJSON,
    SetEmailWebhook200ResponseDataWebhookToJSONTyped,
} from './SetEmailWebhook200ResponseDataWebhook';

/**
 * 
 * @export
 * @interface SetEmailWebhook200ResponseData
 */
export interface SetEmailWebhook200ResponseData {
    /**
     * 
     */
    webhook: SetEmailWebhook200ResponseDataWebhook;
}

/**
 * Check if a given object implements the SetEmailWebhook200ResponseData interface.
 */
export function instanceOfSetEmailWebhook200ResponseData(value: object): value is SetEmailWebhook200ResponseData {
    if (!('webhook' in value) || value['webhook'] === undefined) return false;
    return true;
}

export function SetEmailWebhook200ResponseDataFromJSON(json: any): SetEmailWebhook200ResponseData {
    return SetEmailWebhook200ResponseDataFromJSONTyped(json, false);
}

export function SetEmailWebhook200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetEmailWebhook200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'webhook': SetEmailWebhook200ResponseDataWebhookFromJSON(json['webhook']),
    };
}

export function SetEmailWebhook200ResponseDataToJSON(json: any): SetEmailWebhook200ResponseData {
    return SetEmailWebhook200ResponseDataToJSONTyped(json, false);
}

export function SetEmailWebhook200ResponseDataToJSONTyped(value?: SetEmailWebhook200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhook': SetEmailWebhook200ResponseDataWebhookToJSON(value['webhook']),
    };
}

