/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupAccount
 */
export interface SignupAccount {
    /**
     * 
     */
    id: string;
}

/**
 * Check if a given object implements the SignupAccount interface.
 */
export function instanceOfSignupAccount(value: object): value is SignupAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SignupAccountFromJSON(json: any): SignupAccount {
    return SignupAccountFromJSONTyped(json, false);
}

export function SignupAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SignupAccountToJSON(json: any): SignupAccount {
    return SignupAccountToJSONTyped(json, false);
}

export function SignupAccountToJSONTyped(value?: SignupAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

