/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { SignupAccount } from './SignupAccount';
import {
    SignupAccountFromJSON,
    SignupAccountFromJSONTyped,
    SignupAccountToJSON,
    SignupAccountToJSONTyped,
} from './SignupAccount';
import type { SignupMailbox } from './SignupMailbox';
import {
    SignupMailboxFromJSON,
    SignupMailboxFromJSONTyped,
    SignupMailboxToJSON,
    SignupMailboxToJSONTyped,
} from './SignupMailbox';
import type { SignupStatus } from './SignupStatus';
import {
    SignupStatusFromJSON,
    SignupStatusFromJSONTyped,
    SignupStatusToJSON,
    SignupStatusToJSONTyped,
} from './SignupStatus';

/**
 * First verification returns api_key, account and mailbox. Repeated verification returns completed IDs and recovery_url without the key.
 * @export
 * @interface SignupResult
 */
export interface SignupResult {
    /**
     * 
     */
    signup: SignupStatus;
    /**
     * Returned once; store privately. Never write to logs or chat.
     */
    apiKey?: string;
    /**
     * 
     */
    scope?: SignupResultScopeEnum;
    /**
     * 
     */
    expiresAt?: Date;
    /**
     * 
     */
    account?: SignupAccount;
    /**
     * 
     */
    mailbox?: SignupMailbox;
    /**
     * 
     */
    recoveryUrl?: string;
}


/**
 * @export
 */
export const SignupResultScopeEnum = {
    MailboxAdmin: 'mailbox_admin',
} as const;
export type SignupResultScopeEnum = typeof SignupResultScopeEnum[keyof typeof SignupResultScopeEnum];


/**
 * Check if a given object implements the SignupResult interface.
 */
export function instanceOfSignupResult(value: object): value is SignupResult {
    if (!('signup' in value) || value['signup'] === undefined) return false;
    return true;
}

export function SignupResultFromJSON(json: any): SignupResult {
    return SignupResultFromJSONTyped(json, false);
}

export function SignupResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupResult {
    if (json == null) {
        return json;
    }
    return {
        
        'signup': SignupStatusFromJSON(json['signup']),
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'expiresAt': json['expires_at'] == null ? undefined : (parseDateTime(json['expires_at'])),
        'account': json['account'] == null ? undefined : SignupAccountFromJSON(json['account']),
        'mailbox': json['mailbox'] == null ? undefined : SignupMailboxFromJSON(json['mailbox']),
        'recoveryUrl': json['recovery_url'] == null ? undefined : json['recovery_url'],
    };
}

export function SignupResultToJSON(json: any): SignupResult {
    return SignupResultToJSONTyped(json, false);
}

export function SignupResultToJSONTyped(value?: SignupResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signup': SignupStatusToJSON(value['signup']),
        'api_key': value['apiKey'],
        'scope': value['scope'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'account': SignupAccountToJSON(value['account']),
        'mailbox': SignupMailboxToJSON(value['mailbox']),
        'recovery_url': value['recoveryUrl'],
    };
}

