/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupChallenge
 */
export interface SignupChallenge {
    /**
     * 
     */
    expiresIn: number;
    /**
     * 
     */
    resendAfter: number;
    /**
     * Private signup token returned by the first request. Send only in the JSON body; never log it or show it in chat.
     */
    signupToken: string;
}

/**
 * Check if a given object implements the SignupChallenge interface.
 */
export function instanceOfSignupChallenge(value: object): value is SignupChallenge {
    if ((!('expiresIn' in (value as Record<string, any>)) && !('expires_in' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresIn'] === undefined && (value as Record<string, any>)['expires_in'] === undefined)) return false;
    if ((!('resendAfter' in (value as Record<string, any>)) && !('resend_after' in (value as Record<string, any>))) || ((value as Record<string, any>)['resendAfter'] === undefined && (value as Record<string, any>)['resend_after'] === undefined)) return false;
    if ((!('signupToken' in (value as Record<string, any>)) && !('signup_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['signupToken'] === undefined && (value as Record<string, any>)['signup_token'] === undefined)) return false;
    return true;
}

export function SignupChallengeFromJSON(json: any): SignupChallenge {
    return SignupChallengeFromJSONTyped(json, false);
}

export function SignupChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupChallenge {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresIn': json['expires_in'],
        'resendAfter': json['resend_after'],
        'signupToken': json['signup_token'],
    };
}

export function SignupChallengeToJSON(json: any): SignupChallenge {
    return SignupChallengeToJSONTyped(json, false);
}

export function SignupChallengeToJSONTyped(value?: SignupChallenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_in': value['expiresIn'],
        'resend_after': value['resendAfter'],
        'signup_token': value['signupToken'],
    };
}

