/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartAgentSignup202ResponseData } from './StartAgentSignup202ResponseData';
import {
    StartAgentSignup202ResponseDataFromJSON,
    StartAgentSignup202ResponseDataFromJSONTyped,
    StartAgentSignup202ResponseDataToJSON,
    StartAgentSignup202ResponseDataToJSONTyped,
} from './StartAgentSignup202ResponseData';

/**
 * 
 * @export
 * @interface StartAgentSignup202Response
 */
export interface StartAgentSignup202Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: StartAgentSignup202ResponseData;
}

/**
 * Check if a given object implements the StartAgentSignup202Response interface.
 */
export function instanceOfStartAgentSignup202Response(value: object): value is StartAgentSignup202Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StartAgentSignup202ResponseFromJSON(json: any): StartAgentSignup202Response {
    return StartAgentSignup202ResponseFromJSONTyped(json, false);
}

export function StartAgentSignup202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAgentSignup202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': StartAgentSignup202ResponseDataFromJSON(json['data']),
    };
}

export function StartAgentSignup202ResponseToJSON(json: any): StartAgentSignup202Response {
    return StartAgentSignup202ResponseToJSONTyped(json, false);
}

export function StartAgentSignup202ResponseToJSONTyped(value?: StartAgentSignup202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': StartAgentSignup202ResponseDataToJSON(value['data']),
    };
}

