/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartAgentSignupRequest
 */
export interface StartAgentSignupRequest {
    /**
     * Email supplied by the human who owns and authorizes this account. Do not use an AI agent mailbox or invent this value. Verification proves control of the address.
     */
    humanOperatorEmail: string;
    /**
     * Optional exact name for the first mailbox. Omit to generate a name. Platform reserved and retired name rules apply.
     */
    username?: string;
    /**
     * 
     */
    label?: string;
    /**
     * 
     */
    permissionScope?: StartAgentSignupRequestPermissionScopeEnum;
    /**
     * The human agrees to the current Terms (https://revdoku.com/terms) and service acceptable use policy (https://revdoku.com/acceptable-use), and acknowledges the privacy notice (https://revdoku.com/privacy). This is not consent to optional processing.
     */
    acceptTermsAndPolicy: boolean;
}


/**
 * @export
 */
export const StartAgentSignupRequestPermissionScopeEnum = {
    BucketRead: 'bucket_read',
    BucketWrite: 'bucket_write',
    BucketAdmin: 'bucket_admin',
} as const;
export type StartAgentSignupRequestPermissionScopeEnum = typeof StartAgentSignupRequestPermissionScopeEnum[keyof typeof StartAgentSignupRequestPermissionScopeEnum];


/**
 * Check if a given object implements the StartAgentSignupRequest interface.
 */
export function instanceOfStartAgentSignupRequest(value: object): value is StartAgentSignupRequest {
    if ((!('humanOperatorEmail' in (value as Record<string, any>)) && !('human_operator_email' in (value as Record<string, any>))) || ((value as Record<string, any>)['humanOperatorEmail'] === undefined && (value as Record<string, any>)['human_operator_email'] === undefined)) return false;
    if ((!('acceptTermsAndPolicy' in (value as Record<string, any>)) && !('accept_terms_and_policy' in (value as Record<string, any>))) || ((value as Record<string, any>)['acceptTermsAndPolicy'] === undefined && (value as Record<string, any>)['accept_terms_and_policy'] === undefined)) return false;
    return true;
}

export function StartAgentSignupRequestFromJSON(json: any): StartAgentSignupRequest {
    return StartAgentSignupRequestFromJSONTyped(json, false);
}

export function StartAgentSignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAgentSignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'humanOperatorEmail': json['human_operator_email'],
        'username': json['username'] == null ? undefined : json['username'],
        'label': json['label'] == null ? undefined : json['label'],
        'permissionScope': json['permission_scope'] == null ? undefined : json['permission_scope'],
        'acceptTermsAndPolicy': json['accept_terms_and_policy'],
    };
}

export function StartAgentSignupRequestToJSON(json: any): StartAgentSignupRequest {
    return StartAgentSignupRequestToJSONTyped(json, false);
}

export function StartAgentSignupRequestToJSONTyped(value?: StartAgentSignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'human_operator_email': value['humanOperatorEmail'],
        'username': value['username'],
        'label': value['label'],
        'permission_scope': value['permissionScope'],
        'accept_terms_and_policy': value['acceptTermsAndPolicy'],
    };
}

