/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartAgentSignupRequest
 */
export interface StartAgentSignupRequest {
    /**
     * Email address for the new account.
     */
    email: string;
    /**
     * Agree to the Terms (https://revdoku.com/terms) and Acceptable Use Policy (https://revdoku.com/acceptable-use), and acknowledge the Privacy Policy (https://revdoku.com/privacy).
     */
    acceptTermsAndPolicy: boolean;
}

/**
 * Check if a given object implements the StartAgentSignupRequest interface.
 */
export function instanceOfStartAgentSignupRequest(value: object): value is StartAgentSignupRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('acceptTermsAndPolicy' in (value as Record<string, any>)) && !('accept_terms_and_policy' in (value as Record<string, any>))) || ((value as Record<string, any>)['acceptTermsAndPolicy'] === undefined && (value as Record<string, any>)['accept_terms_and_policy'] === undefined)) return false;
    return true;
}

export function StartAgentSignupRequestFromJSON(json: any): StartAgentSignupRequest {
    return StartAgentSignupRequestFromJSONTyped(json, false);
}

export function StartAgentSignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAgentSignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'acceptTermsAndPolicy': json['accept_terms_and_policy'],
    };
}

export function StartAgentSignupRequestToJSON(json: any): StartAgentSignupRequest {
    return StartAgentSignupRequestToJSONTyped(json, false);
}

export function StartAgentSignupRequestToJSONTyped(value?: StartAgentSignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'accept_terms_and_policy': value['acceptTermsAndPolicy'],
    };
}

