/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignupChallenge } from './SignupChallenge';
import {
    SignupChallengeFromJSON,
    SignupChallengeFromJSONTyped,
    SignupChallengeToJSON,
    SignupChallengeToJSONTyped,
} from './SignupChallenge';

/**
 * 
 * @export
 * @interface StartAgentSignup202ResponseData
 */
export interface StartAgentSignup202ResponseData {
    /**
     * 
     */
    signup: SignupChallenge;
}

/**
 * Check if a given object implements the StartAgentSignup202ResponseData interface.
 */
export function instanceOfStartAgentSignup202ResponseData(value: object): value is StartAgentSignup202ResponseData {
    if (!('signup' in value) || value['signup'] === undefined) return false;
    return true;
}

export function StartAgentSignup202ResponseDataFromJSON(json: any): StartAgentSignup202ResponseData {
    return StartAgentSignup202ResponseDataFromJSONTyped(json, false);
}

export function StartAgentSignup202ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAgentSignup202ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'signup': SignupChallengeFromJSON(json['signup']),
    };
}

export function StartAgentSignup202ResponseDataToJSON(json: any): StartAgentSignup202ResponseData {
    return StartAgentSignup202ResponseDataToJSONTyped(json, false);
}

export function StartAgentSignup202ResponseDataToJSONTyped(value?: StartAgentSignup202ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signup': SignupChallengeToJSON(value['signup']),
    };
}

