/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageUpload
 */
export interface StorageUpload {
    /**
     * 
     */
    url: string;
    /**
     * 
     */
    headers: { [key: string]: string; };
}

/**
 * Check if a given object implements the StorageUpload interface.
 */
export function instanceOfStorageUpload(value: object): value is StorageUpload {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('headers' in value) || value['headers'] === undefined) return false;
    return true;
}

export function StorageUploadFromJSON(json: any): StorageUpload {
    return StorageUploadFromJSONTyped(json, false);
}

export function StorageUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUpload {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'headers': json['headers'],
    };
}

export function StorageUploadToJSON(json: any): StorageUpload {
    return StorageUploadToJSONTyped(json, false);
}

export function StorageUploadToJSONTyped(value?: StorageUpload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'headers': value['headers'],
    };
}

