/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEmailRequest
 */
export interface UpdateEmailRequest {
    /**
     * 
     */
    read: boolean;
    /**
     * 
     */
    accountId?: string;
    /**
     * Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the UpdateEmailRequest interface.
 */
export function instanceOfUpdateEmailRequest(value: object): value is UpdateEmailRequest {
    if (!('read' in value) || value['read'] === undefined) return false;
    return true;
}

export function UpdateEmailRequestFromJSON(json: any): UpdateEmailRequest {
    return UpdateEmailRequestFromJSONTyped(json, false);
}

export function UpdateEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'read': json['read'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function UpdateEmailRequestToJSON(json: any): UpdateEmailRequest {
    return UpdateEmailRequestToJSONTyped(json, false);
}

export function UpdateEmailRequestToJSONTyped(value?: UpdateEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'read': value['read'],
        'account_id': value['accountId'],
        'reason': value['reason'],
    };
}

