/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailSummary } from './EmailSummary';
import {
    EmailSummaryFromJSON,
    EmailSummaryFromJSONTyped,
    EmailSummaryToJSON,
    EmailSummaryToJSONTyped,
} from './EmailSummary';

/**
 * 
 * @export
 * @interface UpdateEmail200ResponseData
 */
export interface UpdateEmail200ResponseData {
    /**
     * 
     */
    email: EmailSummary;
}

/**
 * Check if a given object implements the UpdateEmail200ResponseData interface.
 */
export function instanceOfUpdateEmail200ResponseData(value: object): value is UpdateEmail200ResponseData {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UpdateEmail200ResponseDataFromJSON(json: any): UpdateEmail200ResponseData {
    return UpdateEmail200ResponseDataFromJSONTyped(json, false);
}

export function UpdateEmail200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmail200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'email': EmailSummaryFromJSON(json['email']),
    };
}

export function UpdateEmail200ResponseDataToJSON(json: any): UpdateEmail200ResponseData {
    return UpdateEmail200ResponseDataToJSONTyped(json, false);
}

export function UpdateEmail200ResponseDataToJSONTyped(value?: UpdateEmail200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': EmailSummaryToJSON(value['email']),
    };
}

