/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateEmail200ResponseData } from './UpdateEmail200ResponseData';
import {
    UpdateEmail200ResponseDataFromJSON,
    UpdateEmail200ResponseDataFromJSONTyped,
    UpdateEmail200ResponseDataToJSON,
    UpdateEmail200ResponseDataToJSONTyped,
} from './UpdateEmail200ResponseData';

/**
 * 
 * @export
 * @interface UpdateEmail200Response
 */
export interface UpdateEmail200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: UpdateEmail200ResponseData;
}

/**
 * Check if a given object implements the UpdateEmail200Response interface.
 */
export function instanceOfUpdateEmail200Response(value: object): value is UpdateEmail200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UpdateEmail200ResponseFromJSON(json: any): UpdateEmail200Response {
    return UpdateEmail200ResponseFromJSONTyped(json, false);
}

export function UpdateEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmail200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': UpdateEmail200ResponseDataFromJSON(json['data']),
    };
}

export function UpdateEmail200ResponseToJSON(json: any): UpdateEmail200Response {
    return UpdateEmail200ResponseToJSONTyped(json, false);
}

export function UpdateEmail200ResponseToJSONTyped(value?: UpdateEmail200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UpdateEmail200ResponseDataToJSON(value['data']),
    };
}

