/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateMailboxEmailAllowlist200ResponseData } from './UpdateMailboxEmailAllowlist200ResponseData';
import {
    UpdateMailboxEmailAllowlist200ResponseDataFromJSON,
    UpdateMailboxEmailAllowlist200ResponseDataFromJSONTyped,
    UpdateMailboxEmailAllowlist200ResponseDataToJSON,
    UpdateMailboxEmailAllowlist200ResponseDataToJSONTyped,
} from './UpdateMailboxEmailAllowlist200ResponseData';

/**
 * 
 * @export
 * @interface UpdateMailboxEmailAllowlist200Response
 */
export interface UpdateMailboxEmailAllowlist200Response {
    /**
     * 
     */
    data: UpdateMailboxEmailAllowlist200ResponseData;
    /**
     * 
     */
    success: boolean;
}

/**
 * Check if a given object implements the UpdateMailboxEmailAllowlist200Response interface.
 */
export function instanceOfUpdateMailboxEmailAllowlist200Response(value: object): value is UpdateMailboxEmailAllowlist200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UpdateMailboxEmailAllowlist200ResponseFromJSON(json: any): UpdateMailboxEmailAllowlist200Response {
    return UpdateMailboxEmailAllowlist200ResponseFromJSONTyped(json, false);
}

export function UpdateMailboxEmailAllowlist200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMailboxEmailAllowlist200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': UpdateMailboxEmailAllowlist200ResponseDataFromJSON(json['data']),
        'success': json['success'],
    };
}

export function UpdateMailboxEmailAllowlist200ResponseToJSON(json: any): UpdateMailboxEmailAllowlist200Response {
    return UpdateMailboxEmailAllowlist200ResponseToJSONTyped(json, false);
}

export function UpdateMailboxEmailAllowlist200ResponseToJSONTyped(value?: UpdateMailboxEmailAllowlist200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UpdateMailboxEmailAllowlist200ResponseDataToJSON(value['data']),
        'success': value['success'],
    };
}

