/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateBucketEmailAllowlist200ResponseData } from './UpdateBucketEmailAllowlist200ResponseData';
import {
    UpdateBucketEmailAllowlist200ResponseDataFromJSON,
    UpdateBucketEmailAllowlist200ResponseDataFromJSONTyped,
    UpdateBucketEmailAllowlist200ResponseDataToJSON,
    UpdateBucketEmailAllowlist200ResponseDataToJSONTyped,
} from './UpdateBucketEmailAllowlist200ResponseData';

/**
 * 
 * @export
 * @interface UpdateBucketEmailAllowlist200Response
 */
export interface UpdateBucketEmailAllowlist200Response {
    /**
     * 
     */
    data: UpdateBucketEmailAllowlist200ResponseData;
    /**
     * 
     */
    success: boolean;
}

/**
 * Check if a given object implements the UpdateBucketEmailAllowlist200Response interface.
 */
export function instanceOfUpdateBucketEmailAllowlist200Response(value: object): value is UpdateBucketEmailAllowlist200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UpdateBucketEmailAllowlist200ResponseFromJSON(json: any): UpdateBucketEmailAllowlist200Response {
    return UpdateBucketEmailAllowlist200ResponseFromJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlist200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBucketEmailAllowlist200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': UpdateBucketEmailAllowlist200ResponseDataFromJSON(json['data']),
        'success': json['success'],
    };
}

export function UpdateBucketEmailAllowlist200ResponseToJSON(json: any): UpdateBucketEmailAllowlist200Response {
    return UpdateBucketEmailAllowlist200ResponseToJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlist200ResponseToJSONTyped(value?: UpdateBucketEmailAllowlist200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UpdateBucketEmailAllowlist200ResponseDataToJSON(value['data']),
        'success': value['success'],
    };
}

