/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailSenderAllowlist } from './EmailSenderAllowlist';
import {
    EmailSenderAllowlistFromJSON,
    EmailSenderAllowlistFromJSONTyped,
    EmailSenderAllowlistToJSON,
    EmailSenderAllowlistToJSONTyped,
} from './EmailSenderAllowlist';

/**
 * 
 * @export
 * @interface UpdateBucketEmailAllowlist200ResponseData
 */
export interface UpdateBucketEmailAllowlist200ResponseData {
    /**
     * 
     */
    senderAllowlist: EmailSenderAllowlist;
}

/**
 * Check if a given object implements the UpdateBucketEmailAllowlist200ResponseData interface.
 */
export function instanceOfUpdateBucketEmailAllowlist200ResponseData(value: object): value is UpdateBucketEmailAllowlist200ResponseData {
    if ((!('senderAllowlist' in (value as Record<string, any>)) && !('sender_allowlist' in (value as Record<string, any>))) || ((value as Record<string, any>)['senderAllowlist'] === undefined && (value as Record<string, any>)['sender_allowlist'] === undefined)) return false;
    return true;
}

export function UpdateBucketEmailAllowlist200ResponseDataFromJSON(json: any): UpdateBucketEmailAllowlist200ResponseData {
    return UpdateBucketEmailAllowlist200ResponseDataFromJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlist200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBucketEmailAllowlist200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'senderAllowlist': EmailSenderAllowlistFromJSON(json['sender_allowlist']),
    };
}

export function UpdateBucketEmailAllowlist200ResponseDataToJSON(json: any): UpdateBucketEmailAllowlist200ResponseData {
    return UpdateBucketEmailAllowlist200ResponseDataToJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlist200ResponseDataToJSONTyped(value?: UpdateBucketEmailAllowlist200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sender_allowlist': EmailSenderAllowlistToJSON(value['senderAllowlist']),
    };
}

