/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateMailboxEmailAllowlistRequestSenderAllowlist } from './UpdateMailboxEmailAllowlistRequestSenderAllowlist';
import {
    UpdateMailboxEmailAllowlistRequestSenderAllowlistFromJSON,
    UpdateMailboxEmailAllowlistRequestSenderAllowlistFromJSONTyped,
    UpdateMailboxEmailAllowlistRequestSenderAllowlistToJSON,
    UpdateMailboxEmailAllowlistRequestSenderAllowlistToJSONTyped,
} from './UpdateMailboxEmailAllowlistRequestSenderAllowlist';

/**
 * 
 * @export
 * @interface UpdateMailboxEmailAllowlistRequest
 */
export interface UpdateMailboxEmailAllowlistRequest {
    /**
     * 
     */
    senderAllowlist: UpdateMailboxEmailAllowlistRequestSenderAllowlist;
    /**
     * 
     */
    expectedVersion: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * 
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the UpdateMailboxEmailAllowlistRequest interface.
 */
export function instanceOfUpdateMailboxEmailAllowlistRequest(value: object): value is UpdateMailboxEmailAllowlistRequest {
    if ((!('senderAllowlist' in (value as Record<string, any>)) && !('sender_allowlist' in (value as Record<string, any>))) || ((value as Record<string, any>)['senderAllowlist'] === undefined && (value as Record<string, any>)['sender_allowlist'] === undefined)) return false;
    if ((!('expectedVersion' in (value as Record<string, any>)) && !('expected_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['expectedVersion'] === undefined && (value as Record<string, any>)['expected_version'] === undefined)) return false;
    return true;
}

export function UpdateMailboxEmailAllowlistRequestFromJSON(json: any): UpdateMailboxEmailAllowlistRequest {
    return UpdateMailboxEmailAllowlistRequestFromJSONTyped(json, false);
}

export function UpdateMailboxEmailAllowlistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMailboxEmailAllowlistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'senderAllowlist': UpdateMailboxEmailAllowlistRequestSenderAllowlistFromJSON(json['sender_allowlist']),
        'expectedVersion': json['expected_version'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function UpdateMailboxEmailAllowlistRequestToJSON(json: any): UpdateMailboxEmailAllowlistRequest {
    return UpdateMailboxEmailAllowlistRequestToJSONTyped(json, false);
}

export function UpdateMailboxEmailAllowlistRequestToJSONTyped(value?: UpdateMailboxEmailAllowlistRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sender_allowlist': UpdateMailboxEmailAllowlistRequestSenderAllowlistToJSON(value['senderAllowlist']),
        'expected_version': value['expectedVersion'],
        'account_id': value['accountId'],
        'reason': value['reason'],
    };
}

