/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailSenderAllowlist } from './EmailSenderAllowlist';
import {
    EmailSenderAllowlistFromJSON,
    EmailSenderAllowlistFromJSONTyped,
    EmailSenderAllowlistToJSON,
    EmailSenderAllowlistToJSONTyped,
} from './EmailSenderAllowlist';

/**
 * 
 * @export
 * @interface UpdateMailboxEmailAllowlist200ResponseData
 */
export interface UpdateMailboxEmailAllowlist200ResponseData {
    /**
     * 
     */
    senderAllowlist: EmailSenderAllowlist;
}

/**
 * Check if a given object implements the UpdateMailboxEmailAllowlist200ResponseData interface.
 */
export function instanceOfUpdateMailboxEmailAllowlist200ResponseData(value: object): value is UpdateMailboxEmailAllowlist200ResponseData {
    if ((!('senderAllowlist' in (value as Record<string, any>)) && !('sender_allowlist' in (value as Record<string, any>))) || ((value as Record<string, any>)['senderAllowlist'] === undefined && (value as Record<string, any>)['sender_allowlist'] === undefined)) return false;
    return true;
}

export function UpdateMailboxEmailAllowlist200ResponseDataFromJSON(json: any): UpdateMailboxEmailAllowlist200ResponseData {
    return UpdateMailboxEmailAllowlist200ResponseDataFromJSONTyped(json, false);
}

export function UpdateMailboxEmailAllowlist200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMailboxEmailAllowlist200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'senderAllowlist': EmailSenderAllowlistFromJSON(json['sender_allowlist']),
    };
}

export function UpdateMailboxEmailAllowlist200ResponseDataToJSON(json: any): UpdateMailboxEmailAllowlist200ResponseData {
    return UpdateMailboxEmailAllowlist200ResponseDataToJSONTyped(json, false);
}

export function UpdateMailboxEmailAllowlist200ResponseDataToJSONTyped(value?: UpdateMailboxEmailAllowlist200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sender_allowlist': EmailSenderAllowlistToJSON(value['senderAllowlist']),
    };
}

