/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBucketEmailAllowlistRequestSenderAllowlist
 */
export interface UpdateBucketEmailAllowlistRequestSenderAllowlist {
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    entries: Array<string>;
}

/**
 * Check if a given object implements the UpdateBucketEmailAllowlistRequestSenderAllowlist interface.
 */
export function instanceOfUpdateBucketEmailAllowlistRequestSenderAllowlist(value: object): value is UpdateBucketEmailAllowlistRequestSenderAllowlist {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function UpdateBucketEmailAllowlistRequestSenderAllowlistFromJSON(json: any): UpdateBucketEmailAllowlistRequestSenderAllowlist {
    return UpdateBucketEmailAllowlistRequestSenderAllowlistFromJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlistRequestSenderAllowlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBucketEmailAllowlistRequestSenderAllowlist {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'entries': json['entries'],
    };
}

export function UpdateBucketEmailAllowlistRequestSenderAllowlistToJSON(json: any): UpdateBucketEmailAllowlistRequestSenderAllowlist {
    return UpdateBucketEmailAllowlistRequestSenderAllowlistToJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlistRequestSenderAllowlistToJSONTyped(value?: UpdateBucketEmailAllowlistRequestSenderAllowlist | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'entries': value['entries'],
    };
}

