/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateBucketEmailAllowlistRequestSenderAllowlist } from './UpdateBucketEmailAllowlistRequestSenderAllowlist';
import {
    UpdateBucketEmailAllowlistRequestSenderAllowlistFromJSON,
    UpdateBucketEmailAllowlistRequestSenderAllowlistFromJSONTyped,
    UpdateBucketEmailAllowlistRequestSenderAllowlistToJSON,
    UpdateBucketEmailAllowlistRequestSenderAllowlistToJSONTyped,
} from './UpdateBucketEmailAllowlistRequestSenderAllowlist';

/**
 * 
 * @export
 * @interface UpdateBucketEmailAllowlistRequest
 */
export interface UpdateBucketEmailAllowlistRequest {
    /**
     * 
     */
    senderAllowlist: UpdateBucketEmailAllowlistRequestSenderAllowlist;
    /**
     * 
     */
    expectedVersion: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * 
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the UpdateBucketEmailAllowlistRequest interface.
 */
export function instanceOfUpdateBucketEmailAllowlistRequest(value: object): value is UpdateBucketEmailAllowlistRequest {
    if ((!('senderAllowlist' in (value as Record<string, any>)) && !('sender_allowlist' in (value as Record<string, any>))) || ((value as Record<string, any>)['senderAllowlist'] === undefined && (value as Record<string, any>)['sender_allowlist'] === undefined)) return false;
    if ((!('expectedVersion' in (value as Record<string, any>)) && !('expected_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['expectedVersion'] === undefined && (value as Record<string, any>)['expected_version'] === undefined)) return false;
    return true;
}

export function UpdateBucketEmailAllowlistRequestFromJSON(json: any): UpdateBucketEmailAllowlistRequest {
    return UpdateBucketEmailAllowlistRequestFromJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBucketEmailAllowlistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'senderAllowlist': UpdateBucketEmailAllowlistRequestSenderAllowlistFromJSON(json['sender_allowlist']),
        'expectedVersion': json['expected_version'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function UpdateBucketEmailAllowlistRequestToJSON(json: any): UpdateBucketEmailAllowlistRequest {
    return UpdateBucketEmailAllowlistRequestToJSONTyped(json, false);
}

export function UpdateBucketEmailAllowlistRequestToJSONTyped(value?: UpdateBucketEmailAllowlistRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sender_allowlist': UpdateBucketEmailAllowlistRequestSenderAllowlistToJSON(value['senderAllowlist']),
        'expected_version': value['expectedVersion'],
        'account_id': value['accountId'],
        'reason': value['reason'],
    };
}

