/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadBlob
 */
export interface UploadBlob {
    /**
     * 
     */
    filename: string;
    /**
     * 
     */
    byteSize: number;
    /**
     * 
     */
    checksum: string;
    /**
     * 
     */
    contentType: string;
    /**
     * 
     */
    sha256: string;
    /**
     * 
     */
    purpose: UploadBlobPurposeEnum;
}


/**
 * @export
 */
export const UploadBlobPurposeEnum = {
    MailboxFile: 'mailbox_file',
} as const;
export type UploadBlobPurposeEnum = typeof UploadBlobPurposeEnum[keyof typeof UploadBlobPurposeEnum];


/**
 * Check if a given object implements the UploadBlob interface.
 */
export function instanceOfUploadBlob(value: object): value is UploadBlob {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if ((!('byteSize' in (value as Record<string, any>)) && !('byte_size' in (value as Record<string, any>))) || ((value as Record<string, any>)['byteSize'] === undefined && (value as Record<string, any>)['byte_size'] === undefined)) return false;
    if (!('checksum' in value) || value['checksum'] === undefined) return false;
    if ((!('contentType' in (value as Record<string, any>)) && !('content_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentType'] === undefined && (value as Record<string, any>)['content_type'] === undefined)) return false;
    if (!('sha256' in value) || value['sha256'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (value['purpose'] !== 'mailbox_file') return false;
    
    return true;
}

export function UploadBlobFromJSON(json: any): UploadBlob {
    return UploadBlobFromJSONTyped(json, false);
}

export function UploadBlobFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadBlob {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'byteSize': json['byte_size'],
        'checksum': json['checksum'],
        'contentType': json['content_type'],
        'sha256': json['sha256'],
        'purpose': json['purpose'],
    };
}

export function UploadBlobToJSON(json: any): UploadBlob {
    return UploadBlobToJSONTyped(json, false);
}

export function UploadBlobToJSONTyped(value?: UploadBlob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'byte_size': value['byteSize'],
        'checksum': value['checksum'],
        'content_type': value['contentType'],
        'sha256': value['sha256'],
        'purpose': value['purpose'],
    };
}

