/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BucketEmail } from './BucketEmail';
import {
    BucketEmailFromJSON,
    BucketEmailFromJSONTyped,
    BucketEmailToJSON,
    BucketEmailToJSONTyped,
} from './BucketEmail';

/**
 * 
 * @export
 * @interface VerifyAgentSignup201ResponseDataBucket
 */
export interface VerifyAgentSignup201ResponseDataBucket {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    email: BucketEmail;
}

/**
 * Check if a given object implements the VerifyAgentSignup201ResponseDataBucket interface.
 */
export function instanceOfVerifyAgentSignup201ResponseDataBucket(value: object): value is VerifyAgentSignup201ResponseDataBucket {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function VerifyAgentSignup201ResponseDataBucketFromJSON(json: any): VerifyAgentSignup201ResponseDataBucket {
    return VerifyAgentSignup201ResponseDataBucketFromJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup201ResponseDataBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'email': BucketEmailFromJSON(json['email']),
    };
}

export function VerifyAgentSignup201ResponseDataBucketToJSON(json: any): VerifyAgentSignup201ResponseDataBucket {
    return VerifyAgentSignup201ResponseDataBucketToJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataBucketToJSONTyped(value?: VerifyAgentSignup201ResponseDataBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'email': BucketEmailToJSON(value['email']),
    };
}

