/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyAgentSignup200ResponseDataSignup
 */
export interface VerifyAgentSignup200ResponseDataSignup {
    /**
     * 
     */
    status: VerifyAgentSignup200ResponseDataSignupStatusEnum;
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    bucketId: string;
}


/**
 * @export
 */
export const VerifyAgentSignup200ResponseDataSignupStatusEnum = {
    Completed: 'completed',
} as const;
export type VerifyAgentSignup200ResponseDataSignupStatusEnum = typeof VerifyAgentSignup200ResponseDataSignupStatusEnum[keyof typeof VerifyAgentSignup200ResponseDataSignupStatusEnum];


/**
 * Check if a given object implements the VerifyAgentSignup200ResponseDataSignup interface.
 */
export function instanceOfVerifyAgentSignup200ResponseDataSignup(value: object): value is VerifyAgentSignup200ResponseDataSignup {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'completed') return false;
    
    if ((!('accountId' in (value as Record<string, any>)) && !('account_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['accountId'] === undefined && (value as Record<string, any>)['account_id'] === undefined)) return false;
    if ((!('bucketId' in (value as Record<string, any>)) && !('bucket_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['bucketId'] === undefined && (value as Record<string, any>)['bucket_id'] === undefined)) return false;
    return true;
}

export function VerifyAgentSignup200ResponseDataSignupFromJSON(json: any): VerifyAgentSignup200ResponseDataSignup {
    return VerifyAgentSignup200ResponseDataSignupFromJSONTyped(json, false);
}

export function VerifyAgentSignup200ResponseDataSignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup200ResponseDataSignup {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'accountId': json['account_id'],
        'bucketId': json['bucket_id'],
    };
}

export function VerifyAgentSignup200ResponseDataSignupToJSON(json: any): VerifyAgentSignup200ResponseDataSignup {
    return VerifyAgentSignup200ResponseDataSignupToJSONTyped(json, false);
}

export function VerifyAgentSignup200ResponseDataSignupToJSONTyped(value?: VerifyAgentSignup200ResponseDataSignup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'account_id': value['accountId'],
        'bucket_id': value['bucketId'],
    };
}

