/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifyAgentSignup201ResponseData } from './VerifyAgentSignup201ResponseData';
import {
    VerifyAgentSignup201ResponseDataFromJSON,
    VerifyAgentSignup201ResponseDataFromJSONTyped,
    VerifyAgentSignup201ResponseDataToJSON,
    VerifyAgentSignup201ResponseDataToJSONTyped,
} from './VerifyAgentSignup201ResponseData';

/**
 * 
 * @export
 * @interface VerifyAgentSignup201Response
 */
export interface VerifyAgentSignup201Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: VerifyAgentSignup201ResponseData;
}

/**
 * Check if a given object implements the VerifyAgentSignup201Response interface.
 */
export function instanceOfVerifyAgentSignup201Response(value: object): value is VerifyAgentSignup201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function VerifyAgentSignup201ResponseFromJSON(json: any): VerifyAgentSignup201Response {
    return VerifyAgentSignup201ResponseFromJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': VerifyAgentSignup201ResponseDataFromJSON(json['data']),
    };
}

export function VerifyAgentSignup201ResponseToJSON(json: any): VerifyAgentSignup201Response {
    return VerifyAgentSignup201ResponseToJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseToJSONTyped(value?: VerifyAgentSignup201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': VerifyAgentSignup201ResponseDataToJSON(value['data']),
    };
}

