/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { VerifyAgentSignup201ResponseDataSignup } from './VerifyAgentSignup201ResponseDataSignup';
import {
    VerifyAgentSignup201ResponseDataSignupFromJSON,
    VerifyAgentSignup201ResponseDataSignupFromJSONTyped,
    VerifyAgentSignup201ResponseDataSignupToJSON,
    VerifyAgentSignup201ResponseDataSignupToJSONTyped,
} from './VerifyAgentSignup201ResponseDataSignup';
import type { VerifyAgentSignup201ResponseDataBucket } from './VerifyAgentSignup201ResponseDataBucket';
import {
    VerifyAgentSignup201ResponseDataBucketFromJSON,
    VerifyAgentSignup201ResponseDataBucketFromJSONTyped,
    VerifyAgentSignup201ResponseDataBucketToJSON,
    VerifyAgentSignup201ResponseDataBucketToJSONTyped,
} from './VerifyAgentSignup201ResponseDataBucket';
import type { VerifyAgentSignup201ResponseDataAccount } from './VerifyAgentSignup201ResponseDataAccount';
import {
    VerifyAgentSignup201ResponseDataAccountFromJSON,
    VerifyAgentSignup201ResponseDataAccountFromJSONTyped,
    VerifyAgentSignup201ResponseDataAccountToJSON,
    VerifyAgentSignup201ResponseDataAccountToJSONTyped,
} from './VerifyAgentSignup201ResponseDataAccount';

/**
 * 
 * @export
 * @interface VerifyAgentSignup201ResponseData
 */
export interface VerifyAgentSignup201ResponseData {
    /**
     * 
     */
    signup: VerifyAgentSignup201ResponseDataSignup;
    /**
     * Returned once; store privately. Never write to logs or chat.
     */
    apiKey: string;
    /**
     * 
     */
    scope: VerifyAgentSignup201ResponseDataScopeEnum;
    /**
     * 
     */
    expiresAt: Date;
    /**
     * 
     */
    account: VerifyAgentSignup201ResponseDataAccount;
    /**
     * 
     */
    bucket: VerifyAgentSignup201ResponseDataBucket;
}


/**
 * @export
 */
export const VerifyAgentSignup201ResponseDataScopeEnum = {
    BucketRead: 'bucket_read',
    BucketWrite: 'bucket_write',
    BucketAdmin: 'bucket_admin',
} as const;
export type VerifyAgentSignup201ResponseDataScopeEnum = typeof VerifyAgentSignup201ResponseDataScopeEnum[keyof typeof VerifyAgentSignup201ResponseDataScopeEnum];


/**
 * Check if a given object implements the VerifyAgentSignup201ResponseData interface.
 */
export function instanceOfVerifyAgentSignup201ResponseData(value: object): value is VerifyAgentSignup201ResponseData {
    if (!('signup' in value) || value['signup'] === undefined) return false;
    if ((!('apiKey' in (value as Record<string, any>)) && !('api_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['apiKey'] === undefined && (value as Record<string, any>)['api_key'] === undefined)) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if ((!('expiresAt' in (value as Record<string, any>)) && !('expires_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresAt'] === undefined && (value as Record<string, any>)['expires_at'] === undefined)) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    return true;
}

export function VerifyAgentSignup201ResponseDataFromJSON(json: any): VerifyAgentSignup201ResponseData {
    return VerifyAgentSignup201ResponseDataFromJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'signup': VerifyAgentSignup201ResponseDataSignupFromJSON(json['signup']),
        'apiKey': json['api_key'],
        'scope': json['scope'],
        'expiresAt': (json['expires_at'] == null ? json['expires_at'] : parseDateTime(json['expires_at'])),
        'account': VerifyAgentSignup201ResponseDataAccountFromJSON(json['account']),
        'bucket': VerifyAgentSignup201ResponseDataBucketFromJSON(json['bucket']),
    };
}

export function VerifyAgentSignup201ResponseDataToJSON(json: any): VerifyAgentSignup201ResponseData {
    return VerifyAgentSignup201ResponseDataToJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataToJSONTyped(value?: VerifyAgentSignup201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signup': VerifyAgentSignup201ResponseDataSignupToJSON(value['signup']),
        'api_key': value['apiKey'],
        'scope': value['scope'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'account': VerifyAgentSignup201ResponseDataAccountToJSON(value['account']),
        'bucket': VerifyAgentSignup201ResponseDataBucketToJSON(value['bucket']),
    };
}

