/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyAgentSignupRequest
 */
export interface VerifyAgentSignupRequest {
    /**
     * Six-digit email verification code.
     */
    code: string;
    /**
     * Private signup token returned by the first request. Send only in the JSON body; never log it or show it in chat.
     */
    signupToken: string;
}

/**
 * Check if a given object implements the VerifyAgentSignupRequest interface.
 */
export function instanceOfVerifyAgentSignupRequest(value: object): value is VerifyAgentSignupRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if ((!('signupToken' in (value as Record<string, any>)) && !('signup_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['signupToken'] === undefined && (value as Record<string, any>)['signup_token'] === undefined)) return false;
    return true;
}

export function VerifyAgentSignupRequestFromJSON(json: any): VerifyAgentSignupRequest {
    return VerifyAgentSignupRequestFromJSONTyped(json, false);
}

export function VerifyAgentSignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'signupToken': json['signup_token'],
    };
}

export function VerifyAgentSignupRequestToJSON(json: any): VerifyAgentSignupRequest {
    return VerifyAgentSignupRequestToJSONTyped(json, false);
}

export function VerifyAgentSignupRequestToJSONTyped(value?: VerifyAgentSignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'signup_token': value['signupToken'],
    };
}

