/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyAccountEmailDomainRequest
 */
export interface VerifyAccountEmailDomainRequest {
    /**
     * Explicit granted account for this call.
     */
    accountId?: string;
    /**
     * Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the VerifyAccountEmailDomainRequest interface.
 */
export function instanceOfVerifyAccountEmailDomainRequest(value: object): value is VerifyAccountEmailDomainRequest {
    return true;
}

export function VerifyAccountEmailDomainRequestFromJSON(json: any): VerifyAccountEmailDomainRequest {
    return VerifyAccountEmailDomainRequestFromJSONTyped(json, false);
}

export function VerifyAccountEmailDomainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAccountEmailDomainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function VerifyAccountEmailDomainRequestToJSON(json: any): VerifyAccountEmailDomainRequest {
    return VerifyAccountEmailDomainRequestToJSONTyped(json, false);
}

export function VerifyAccountEmailDomainRequestToJSONTyped(value?: VerifyAccountEmailDomainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'reason': value['reason'],
    };
}

