/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyAgentSignup201ResponseDataAccount
 */
export interface VerifyAgentSignup201ResponseDataAccount {
    /**
     * 
     */
    id: string;
}

/**
 * Check if a given object implements the VerifyAgentSignup201ResponseDataAccount interface.
 */
export function instanceOfVerifyAgentSignup201ResponseDataAccount(value: object): value is VerifyAgentSignup201ResponseDataAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function VerifyAgentSignup201ResponseDataAccountFromJSON(json: any): VerifyAgentSignup201ResponseDataAccount {
    return VerifyAgentSignup201ResponseDataAccountFromJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup201ResponseDataAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function VerifyAgentSignup201ResponseDataAccountToJSON(json: any): VerifyAgentSignup201ResponseDataAccount {
    return VerifyAgentSignup201ResponseDataAccountToJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataAccountToJSONTyped(value?: VerifyAgentSignup201ResponseDataAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

