/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifyAgentSignup200ResponseData } from './VerifyAgentSignup200ResponseData';
import {
    VerifyAgentSignup200ResponseDataFromJSON,
    VerifyAgentSignup200ResponseDataFromJSONTyped,
    VerifyAgentSignup200ResponseDataToJSON,
    VerifyAgentSignup200ResponseDataToJSONTyped,
} from './VerifyAgentSignup200ResponseData';

/**
 * 
 * @export
 * @interface VerifyAgentSignup200Response
 */
export interface VerifyAgentSignup200Response {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: VerifyAgentSignup200ResponseData;
}

/**
 * Check if a given object implements the VerifyAgentSignup200Response interface.
 */
export function instanceOfVerifyAgentSignup200Response(value: object): value is VerifyAgentSignup200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function VerifyAgentSignup200ResponseFromJSON(json: any): VerifyAgentSignup200Response {
    return VerifyAgentSignup200ResponseFromJSONTyped(json, false);
}

export function VerifyAgentSignup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': VerifyAgentSignup200ResponseDataFromJSON(json['data']),
    };
}

export function VerifyAgentSignup200ResponseToJSON(json: any): VerifyAgentSignup200Response {
    return VerifyAgentSignup200ResponseToJSONTyped(json, false);
}

export function VerifyAgentSignup200ResponseToJSONTyped(value?: VerifyAgentSignup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': VerifyAgentSignup200ResponseDataToJSON(value['data']),
    };
}

