/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.525
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyAgentSignup201ResponseDataSignup
 */
export interface VerifyAgentSignup201ResponseDataSignup {
    /**
     * 
     */
    status: VerifyAgentSignup201ResponseDataSignupStatusEnum;
}


/**
 * @export
 */
export const VerifyAgentSignup201ResponseDataSignupStatusEnum = {
    Completed: 'completed',
} as const;
export type VerifyAgentSignup201ResponseDataSignupStatusEnum = typeof VerifyAgentSignup201ResponseDataSignupStatusEnum[keyof typeof VerifyAgentSignup201ResponseDataSignupStatusEnum];


/**
 * Check if a given object implements the VerifyAgentSignup201ResponseDataSignup interface.
 */
export function instanceOfVerifyAgentSignup201ResponseDataSignup(value: object): value is VerifyAgentSignup201ResponseDataSignup {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'completed') return false;
    
    return true;
}

export function VerifyAgentSignup201ResponseDataSignupFromJSON(json: any): VerifyAgentSignup201ResponseDataSignup {
    return VerifyAgentSignup201ResponseDataSignupFromJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataSignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup201ResponseDataSignup {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function VerifyAgentSignup201ResponseDataSignupToJSON(json: any): VerifyAgentSignup201ResponseDataSignup {
    return VerifyAgentSignup201ResponseDataSignupToJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataSignupToJSONTyped(value?: VerifyAgentSignup201ResponseDataSignup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

