/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifyAgentSignup200ResponseDataSignup } from './VerifyAgentSignup200ResponseDataSignup';
import {
    VerifyAgentSignup200ResponseDataSignupFromJSON,
    VerifyAgentSignup200ResponseDataSignupFromJSONTyped,
    VerifyAgentSignup200ResponseDataSignupToJSON,
    VerifyAgentSignup200ResponseDataSignupToJSONTyped,
} from './VerifyAgentSignup200ResponseDataSignup';

/**
 * 
 * @export
 * @interface VerifyAgentSignup200ResponseData
 */
export interface VerifyAgentSignup200ResponseData {
    /**
     * 
     */
    signup: VerifyAgentSignup200ResponseDataSignup;
    /**
     * 
     */
    recoveryUrl: string;
}

/**
 * Check if a given object implements the VerifyAgentSignup200ResponseData interface.
 */
export function instanceOfVerifyAgentSignup200ResponseData(value: object): value is VerifyAgentSignup200ResponseData {
    if (!('signup' in value) || value['signup'] === undefined) return false;
    if ((!('recoveryUrl' in (value as Record<string, any>)) && !('recovery_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['recoveryUrl'] === undefined && (value as Record<string, any>)['recovery_url'] === undefined)) return false;
    return true;
}

export function VerifyAgentSignup200ResponseDataFromJSON(json: any): VerifyAgentSignup200ResponseData {
    return VerifyAgentSignup200ResponseDataFromJSONTyped(json, false);
}

export function VerifyAgentSignup200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'signup': VerifyAgentSignup200ResponseDataSignupFromJSON(json['signup']),
        'recoveryUrl': json['recovery_url'],
    };
}

export function VerifyAgentSignup200ResponseDataToJSON(json: any): VerifyAgentSignup200ResponseData {
    return VerifyAgentSignup200ResponseDataToJSONTyped(json, false);
}

export function VerifyAgentSignup200ResponseDataToJSONTyped(value?: VerifyAgentSignup200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signup': VerifyAgentSignup200ResponseDataSignupToJSON(value['signup']),
        'recovery_url': value['recoveryUrl'],
    };
}

