/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxEmail } from './MailboxEmail';
import {
    MailboxEmailFromJSON,
    MailboxEmailFromJSONTyped,
    MailboxEmailToJSON,
    MailboxEmailToJSONTyped,
} from './MailboxEmail';

/**
 * 
 * @export
 * @interface VerifyAgentSignup201ResponseDataMailbox
 */
export interface VerifyAgentSignup201ResponseDataMailbox {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    email: MailboxEmail;
}

/**
 * Check if a given object implements the VerifyAgentSignup201ResponseDataMailbox interface.
 */
export function instanceOfVerifyAgentSignup201ResponseDataMailbox(value: object): value is VerifyAgentSignup201ResponseDataMailbox {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function VerifyAgentSignup201ResponseDataMailboxFromJSON(json: any): VerifyAgentSignup201ResponseDataMailbox {
    return VerifyAgentSignup201ResponseDataMailboxFromJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataMailboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAgentSignup201ResponseDataMailbox {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': MailboxEmailFromJSON(json['email']),
    };
}

export function VerifyAgentSignup201ResponseDataMailboxToJSON(json: any): VerifyAgentSignup201ResponseDataMailbox {
    return VerifyAgentSignup201ResponseDataMailboxToJSONTyped(json, false);
}

export function VerifyAgentSignup201ResponseDataMailboxToJSONTyped(value?: VerifyAgentSignup201ResponseDataMailbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': MailboxEmailToJSON(value['email']),
    };
}

